### ISSUE TITLE
formato

### ISSUE THREAD

**Issue by solebravo** [IIC2413/Syllabus-2023-2#100]
Hola! tenia la duda de como se hacia/entregaba el control, porque en el enunciado dice que hay que subir el mismo archivo a canvas, pero no se si eso significa que hay como q abrir el archivo desde colab y completarlo, lo que no se hacer (subirlo), asi que si se refiere a eso seria bacan si me lo pueden explicar o dirigir a donde lo expliquen, o hay crear un archivo nuevo en colab, correr los comando, responder y luego subir este a canvas.
gracias de antemano!

**Comment by antoniablanco** [comment]
Hola, es necesario abrir el archivo que se subió con extensión .ipynb (Es la extención para jupyter notebook). En este archivo especifica algunas celdas que deben correr apretando en la flechita en la parte más izquierda para tener todas las dependencias necesarias. Y después en el mismo archivo deben crear sus consultas en sql en los espacios que dejaron para eso y subir esta versión editada a canvas.
