### ISSUE TITLE
Control 2 pregunta 1, puntaje obtenidos

### ISSUE THREAD

**Issue by cebabeltran** [IIC2413/Syllabus-2023-2#101]
Hola! Tengo una duda con la primera consulta del control. Resulta que el enunciado pide "la cantidad total de KOs, Asistencias y puntaje obtenidos". Cuando dice puntaje obtenidos, se refiere a la cantidad de veces que el usuario recibió un puntaje (i.e., la cantidad de filas de la tabla score), o a la suma de los puntajes totales obtenidos (sumando la columna de puntaje)?
Gracias de antemano!

**Comment by antoniablanco** [comment]
Hola, se pide la suma de todos los puntajes totales obtenidos.
