### ISSUE TITLE
Consultas C2

### ISSUE THREAD

**Issue by MariaJoseSilva** [IIC2413/Syllabus-2023-2#102]
Hola!
Tengo algunas dudas sobre las consultas

_**Consulta 1**: Para el usuario de email elizabeth@cooper.net encontrar la cantidad total de KOs, Asistencias y puntaje obtenidos en todas sus partidas._
En esta consulta se espera una única fila como respuesta? o una fila por partida 

_**Consulta 4**: Para la partida de id 256 mostrar el tiempo en segundos que cada bolsimon pasó fuera de combate._
En este caso, basta con mostrar el id_bolsimon y los segundos que pasó fuera de combate, o hay que incluir todos los atributos del bolsimon (nombre y tipo)

_**Consulta 8**: Encontrar el nombre del Bolsimon de mejor y peor winrate (% de victorias)_
Por partida, los 5 bolsimon del equipo ganador se consideran ganadores, o hay que encontrar aquel con mayor puntaje dentro de los bolsimon del equipo ganador?

Muchas gracias!

**Comment by antoniablanco** [comment]
Hola!
Consulta 1: Al hablar del total, se espera que sea una sola fila.
Consulta 4: Se espera más que el id sea el nombre del bolsimon junto a su tiempo.
Consulta 8: Al ganar una partida se considera que los 5 jugadores ganaron, pero un mismo jugador no se encuentra siempre en el mismo equipo. Por lo que este es valor es diferente entre todos. Se espera que entreguen un bolsimon con el mejor y otro con el peor winrate.

**Comment by tnaspee** [comment]
Hola!
Tenía una pregunta relacionada a esto:
en la Consulta 1, se tienen que mostrar los KOs, Asistencias y Puntaje en una misma Tabla? O se pueden mostrar la suma de los KOs, Asistencias y Puntaje por separado.

**Comment by antoniablanco** [comment]
Hola, se espera que entreguen todos los valores juntos.
