### ISSUE TITLE
Control 2 - Pregunta 3, partida en progreso

### ISSUE THREAD

**Issue by cebabeltran** [IIC2413/Syllabus-2023-2#104]
Hola! Tengo una consulta sobre la pregunta 3 del control. Resulta que el enunciado nos pide el equipo ganador de la partida 12345, pero en la tabla partida sale que el estado de ésta es "en progreso". ¿Aún así hay que calcular un ganador, o hay que responder con que aún no ha terminado?

**Comment by lfb1206** [comment]
Esto se respondió en la issue #98.
