### ISSUE TITLE
Control 2 pregunta 8

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#105]
En la pregunta 8 tenemos que calcular el winrate para cada bolsimon donde winrate serian ganadas/ totales. Las ganadas y totales cuentan a las partidas en progreso o solo a las terminadas? Se que respondieron que cuentan ambas en otra issue pero era para otra pregunta

**Comment by lpalacios1** [comment]
Efecitvamente, cuentan todas, en progreso y terminadas.

**Comment by SantiagoDLCB** [comment]
Y para calcular el winrate si un equipo no tiene puntaje en una partida lo consideramos como 0

**Comment by lpalacios1** [comment]
El winrate se calcula a partir de % de partidas ganadas/(ganadas+perdidas) por lo que en el caso de que no tenga puntaje en esta partida, no debería haberla ganado (de todas maneras hay que revisar el ganador de esa partida).
