### ISSUE TITLE
Control 2 - Mayor atributo repetido

### ISSUE THREAD

**Issue by cebabeltran** [IIC2413/Syllabus-2023-2#106]
Hola, tengo una consulta respecto al control.
En algunas de las preguntas de la parte 1, piden entregar el "mayor" de algo; por ejemplo, en la pregunta 5 piden "los ido de la pareja de jugadores que más asistencias se hayan hecho mutuamente". En estos casos, si es que al calcular la cantidad del atributo pedido hay valores máximos repetidos, ¿basta con entregar en el primer valor que aparezca en la tabla si ordenamos el atributo, o habría que imprimir los valores máximos si están empatados?
Por ejemplo, siguiendo el caso de la pregunta 5, que hayan dos pares de ids de jugadores que tengan la misma cantidad de asistencias mutuas, y que este sea el valor mayor que pide el enunciado, ¿habría que entregar uno de los dos pares de id (el que aparezca primero al hacer la consulta), o habría que devolver los dos, justificando que tienen la misma cantidad?
Gracias!

**Comment by lpalacios1** [comment]
En el caso de que se repita un valor mientras el orden este bien y sea una distinta pareja no hay problema. Es decir, si el orden es 10, 10, 9 , 8 , 7, siendo 5 parejas diferentes estaría correcto. Aprovecho de todas maneras de recalcar que las asistencias se cuentan como todas las que hizo A a B y todas las que hizo B a A, entonces ahí seria el total de la pareja (A-B) pero no deberias tener despues (B-A) porque seria la misma pareja. Espero quede claro con eso.

**Comment by cebabeltran** [comment]
Gracias por la respuesta. Tomando el ejemplo que diste, si el orden fuera 10, 10, 9, 8, 7, pero solo piden a la pareja con el mayor valor, bastaría con incluir cualquiera de las que tiene 10?

**Comment by lpalacios1** [comment]
Exacto, si por ejemplo en ese orden, tuvieses que el primer 10 es A-B y el segundo 10 B-A solo deberías incluir uno.
