### ISSUE TITLE
Consulta 6 Control 2

### ISSUE THREAD

**Issue by 00nrs** [IIC2413/Syllabus-2023-2#107]
Hola,
Respecto a la consulta 6 del control, se nos pide encontrar al usuario que jugó más partidas en un día en particular (tipo nosotros debemos especificar un día con la sentencia date_trunc('day', <fecha>))?? O simplemente se nos pide encontrar al usuario que jugó más partidas en un día cualquiera (sin fecha en particular)?

**Comment by antoniablanco** [comment]
Hola!
Se deben contar todos los días, es decir para cada jugador obtener todas las partidas para cada día por separado y compararlas.
