### ISSUE TITLE
Control 2, relacion score

### ISSUE THREAD

**Issue by tomas-jackson** [IIC2413/Syllabus-2023-2#110]
Si para una partida especifica no encontramos un id, asumimos que no consiguio ningun tipo de puntaje durante esa partida?

**Comment by antoniablanco** [comment]
Hola, para cada score existe un id_partida. En el otro sentido si una partida no tiene un score asociado no se puede decir nada del puntaje.

**Comment by tomas-jackson** [comment]
entonces en el caso de que los jugadores 0 a 9 estan en la partida 23, pero los scores de la partida 23 solo muestran a los jugadores 0 al 7, no podemos determinar nada sobre el puntajes de los jugadores 8 y 9?

**Comment by antoniablanco** [comment]
Claro

**Comment by Amegonzale** [comment]
Pregunta, si recopilo el id_jugador con la suma de sus puntajes y uno de los jugadores de la partida no sale en la tabla de score significa que tienen puntaje 0?
