### ISSUE TITLE
Control 2 Consulta 1

### ISSUE THREAD

**Issue by tnaspee** [IIC2413/Syllabus-2023-2#111]
Hola!
¿Se pueden crear tablas entremedio para responder las consultas en la primera parte?

**Comment by antoniablanco** [comment]
Hola, no se pueden crear tablas en la base de datos con los comandos Create, alt, etc. Lo que si pueden hacer en la primera parte es hacer consultas anidadas donde se renombran tablas con los comandos with, select. Es decir solo se pueden usar comando que trabajen con las tablas de las bases de datos no modificar las bases de datos.
