### ISSUE TITLE
Control 2 consulta 4 

### ISSUE THREAD

**Issue by Vicentapd** [IIC2413/Syllabus-2023-2#112]
"Para la partida de id 256 mostrar el tiempo en segundos que cada bolsimon pasó fuera de combate"
Tengo una confusión en cuanto a las relaciones
ko(id int, id_jugador int, id_victima int, id_partida int, timestamp float, segundos_reaparecer int)
usuario_partida_bolsimon(id int, id_jugador int, id_bolsimon int, id_partida int , equipo varchar(5))

Puesto que ko me entrega el tiempo en reaparecer, pero no que bolsimorón específico de usuario victima (id_victima) fue atacado, no tendría como relacionar ambas tablas a menos que asuma que se dejo ko a todos los bolsimoron, pero el enunciado dice claramente que el ko es por cada uno.

**Comment by antoniablanco** [comment]
Hola, es posible obtener el valor a partir del id_victima y el id_partida .

**Comment by Vicentapd** [comment]
pasa que id_victima e id_partida se relacionan a id_jugador e id_partida de usuario_partida_bolsimon y el usuario en cada partida tiene 5 bolsimoron, si id_victima fuera id_bolsimoron si podría saberse a cual de los bolsimoron se dejó ko

**Comment by antoniablanco** [comment]
Recuerda que puede utiliza left join que funciona diferente a solo join.
