### ISSUE TITLE
Control 2 Pregunta 9 (uso de funciones)

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#114]
En la pregunta se nos pide crear tablas para satisfacer unos requerimientos. Se pueden crear funciones para usarlas para evaluar constraints de valores que se pueden insertar en las tablas?

**Comment by lpalacios1** [comment]
Se pueden agregar constraints, pero a que te refieres con funciones?

**Comment by SantiagoDLCB** [comment]
Me refiero a los Stored Procedures que vimos en la clase del miércoles. Al final mi duda es si podemos hacer esto:

CONSTRAINT nombre_constraint CHECK (columna = funcion(variable))

Esto lo quiero hacer porque psql no me deja anidar una consulta en CHECK, entonces mi pregunta es si se pueden implementar un Stored Procedure.

**Comment by lpalacios1** [comment]
No se pueden implementar para este control.
