### ISSUE TITLE
Control 2 Parte 2

### ISSUE THREAD

**Issue by tnaspee** [IIC2413/Syllabus-2023-2#119]
Hola! Tenía la duda de que si para la parte 2, por ejemplo les tenemos que dar 6 ataques a los 49 Bolsimones, o si se puede implementar para un número reducido de ellos.
Muchas gracias

**Comment by antoniablanco** [comment]
Hola, se deben crear las tablas para en la base datos, pero no es necesario rellenarlas con datos.

**Comment by tnaspee** [comment]
Ah ya! Muchas gracias.
