### ISSUE TITLE
Control 1: Pregunta 5

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#12]
Hola! Cuando la pregunta dice "Liste todos los nombres de autores que son editores de todos los libros."" se refiere a la totalidad de todos los libros de diferentes nombre en sus diferentes versiones de año? (esta opción me causa duda porque no existe tal cosa en la base de datos) o se refiere a todos los libros en algunas de sus versiones? o directamente se refiere a los autores que son editores de todas las versiones de un mismo libro?

**Comment by antoniablanco** [comment]
Hola, esa pregunta hace referencia a un editor de todos los libros, que existen en la tabla Libro, no solo distintas ediciones de un mismo libro.

**Comment by SantiagoDLCB** [comment]
Hola, no me calza eso porque implica que una misma edición de un libro(ósea el mismo libro en distintas fechas), puede tener más de un editor. Pero eso a su vez implica que para un mismo libro tendría que haber más de una entrada para especificar a varios editores, el problema es que id_libro es una super llave y por lo tanto no puede estar duplicado, ósea no puede existir dos tuplas con todo igual menos el editor.

**Comment by lfb1206** [comment]
Respondiendo a Maria Jose, distintas ediciones se consideran distintos libros, como se puede observar en la tabla.

Respondiendo a Santiago, no existe una misma edición de un libro, hay distintas ediciones del mismo libro lo que se traduce en id_libro distinto. Estas distintas ediciones pueden tener igual o distinto editor, por lo que se debe encontrar el autor que es editor de todos los libros. Puede parecer contradictorio a lo que sale en las tablas, pero están tan solo sirven de ejercicio para la pregunta 1 y ejemplo para el resto, estas se deben realizar hipotéticamente, independiente de si el resultado vaya a ser nulo o no.
