### ISSUE TITLE
Control 2 Parte 2, sobre el nivel

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#120]
Hola! en la parte 2 se nos dice que un ataque puede tener nivel 'básico', 'intermedio' o 'avanzado'. Es necesario que creemos una columna que diga el ataque pertenece dicho nivel ? Podría simplemente crearle una tabla a cada tipo de ataque y nunca especificarlo en una columna con un atributo de texto.

**Comment by antoniablanco** [comment]
Hola, es necesario que se especifique el nivel del ataque, es decisión tuya si prefieres que sea una columna o una tabla aparte.
