### ISSUE TITLE
C2 Parte 2

### ISSUE THREAD

**Issue by MariaJoseSilva** [IIC2413/Syllabus-2023-2#121]
Hola,
En la parte 2 del control, cuando se pide "justificar que tu esquema este bien diseñado", se espera una justificación en palabras?
Gracias!

**Comment by antoniablanco** [comment]
Hola, se espera que la justificación sea teórica y este basada en la materia vista en clases.

**Comment by josegarafulic** [comment]
Eso significa que hay que tiene que ser escrita?
