### ISSUE TITLE
Control 2 Consulta 6

### ISSUE THREAD

**Issue by Eduuuuuuuuuuuuuuuuuuuuu** [IIC2413/Syllabus-2023-2#122]
En el caso en el que dos o más usuarios hayan jugado la mayor cantidad de partidas en un día, ¿Debo dejar a ambos usuarios en la tabla o solo uno random de los dos?

**Comment by antoniablanco** [comment]
Hola, en el enunciado se comenta de el jugador. Recuerda que existen comandos que te limitan la cantidad que se entrega.

**Comment by Eduuuuuuuuuuuuuuuuuuuuu** [comment]
¿Entonces en caso de empate solo dejo uno cualquiera?

**Comment by antoniablanco** [comment]
Existen comando para obtener una cantidad limite de elementos sin que sea totalmente al azar, puesto que es el mismo resultado siempre que se corre la celda.
