### ISSUE TITLE
Control 2 pregunta 8

### ISSUE THREAD

**Issue by Bjnazar** [IIC2413/Syllabus-2023-2#123]
Hola! No entiendo como saber si el bolsimon ganó o perdió siendo que solo hay kos. Y también si es que la consulta debería haber una fila por cada bolsimon bolsimon(id int, nombre varchar(30), tipo varchar(30)) o en vez una fila por cada bolsimon de cada usuario en usuario_partida_bolsimon(id int, id_jugador int, id_bolsimon int, id_partida int , equipo varchar(5)). 
De antemano muchas gracias

**Comment by antoniablanco** [comment]
Hola, el ganador es a partir del puntaje. Tu puedes saber los puntajes en score y a que partida y jugador pertenecen. 
Se espera como respuesta el nombre del bolsimon con su winrate.

**Comment by Bjnazar** [comment]
Gracias, y lo de las filas como sería? una fila por cada bolsimon de cada usuario aunque esten repetidos? o una fila por cada bolsimon de la tabla  bolsimon bolsimon(id int, nombre varchar(30), tipo varchar(30))?

**Comment by antoniablanco** [comment]
Hola, no deben repetirse los bolsimones.

**Comment by jorgee02** [comment]
Hola, pueden haber empates en los maximos puntajes de cada partida?
