### ISSUE TITLE
Control 2, Parte 2

### ISSUE THREAD

**Issue by MarquezFelipe** [IIC2413/Syllabus-2023-2#124]
Buenas, tengo una duda sobre si para el nuevo esquema solo se deben crear nuevas tablas o podría agregar atributos a tablas ya existentes, muchas gracias de antemano

**Comment by antoniablanco** [comment]
Hola, si se puede agregar nuevos atributos a las columnas existentes.

**Comment by MariaJoseSilva** [comment]
Hola!
Respecto a esta pregunta, así como se pueden agregar nuevos atributos, se pueden eliminar atributos?

Además, debemos diferenciar cuando un jugador hace una asistencia o un ko, respecto al tipo de ataque que esta utilizando?
