### ISSUE TITLE
Control 2 Consulta 4

### ISSUE THREAD

**Issue by Eliosx** [IIC2413/Syllabus-2023-2#125]
Tengo una duda acerca el resultado de la consulta 4 y es que dicen en el enunciado que un bolsimon no puede estar 2 veces en una misma partida pero cuando voy a revisar la tabla usuario_partida_bolsimon con la id_partida = 256 aparece que cada jugador tiene un solo bolsimon y en la tabla ko hay 37 turnos por lo que si o si se van a repetir los bolsimones. 
Tambien agregar que no veo sentido a segundos_reaparecer ya que en esa misma partida se puede ver como le hacen ko a un mismo bolsimon (segun lo que entiendo el usuario tiene un solo bolsimon en esa partida como explique anteriormente) 2 veces seguidas cuando la diferencia de segundos del segundo ko con el primero es en milisegundos.

**Comment by antoniablanco** [comment]
Hola, un bolsimon tras ko reaparece tras segundos_reaparecer y es posible que lo vuelvan a seleccionar para seguir jugando. Dado que es el mismo bolsimon (mismo id) el que sigue jugando, no es que este dos veces (mismo nombre distinto id).
