### ISSUE TITLE
Control 2 pregunta 3

### ISSUE THREAD

**Issue by GuilleStanke** [IIC2413/Syllabus-2023-2#126]
Encontrar los usernames y ratings de los 5 usuarios que han usado el Bolsimon Pikecho en más partidas. (4 pts)

En el caso de que entre el quinto y el sexto usuario con más partidas usando el Bolsimon Pikecho hayan jugado la misma cantidad de partidas, tengo que mostrar los con mayor rating? o cualquiera?

**Comment by antoniablanco** [comment]
Hola, no te preocupes del rating en el orden. Mientras esten según la cantidad de partidas esta bien.
