### ISSUE TITLE
Control 2 Error de output

### ISSUE THREAD

**Issue by benjazuloaga** [IIC2413/Syllabus-2023-2#128]
Hola, en algunas consultas me aparece lo siguiente y nose a que hace referencia por que no me aparece ningún error ni nada.
Gracias

![image](https://github.com/IIC2413/Syllabus-2023-2/assets/110860328/96fbd15e-e2dd-4866-8e4b-c2598af8d3e0)

**Comment by antoniablanco** [comment]
Hola, ese error a veces ocurre si es que no has corrido las celdas del principio en el último tiempo. Intenta correr todas las celdas de nuevo.

**Comment by benjazuloaga** [comment]
Hola, ya las corri y tampoco me funciona :(
