### ISSUE TITLE
Control 2, Pregunta 7

### ISSUE THREAD

**Issue by dvictorerol** [IIC2413/Syllabus-2023-2#129]
Hola, en la pregunta 7 cada puntaje está asociado con un tiempo (para una misma partida y jugador), entonces aparecen múltiples puntajes para una misma partida y jugador. Mi pregunta es si se debe tomar el puntaje con el mayor timestamp (haciendo referencia al puntaje al finalizar la partida), o si se deben sumar todos los puntajes (haciendo referencia a que es el puntaje que se obtuvo en un timestamp específico).

**Comment by antoniablanco** [comment]
Hola, se deben sumar los puntajes  de una misma partida para un mismo jugador.
