### ISSUE TITLE
Control 1 Pregunta 6 doble negación 

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#13]
Hola! En el ultimo ejercicio se pide "los nombres de los autores que no son autores de ningún libro". Esta doble negación es intencional?  Ósea están pidiendo los autores que son autores de algún libro? O realmente están pidiendo los autores que no son autores de algún libro?

**Comment by antoniablanco** [comment]
Hola, la pregunta se refiere a los autores que no son autores de algún libro.
