### ISSUE TITLE
Error en control 2: UsageError: Cell magic `%%sql` not found.

### ISSUE THREAD

**Issue by jlcruzatm** [IIC2413/Syllabus-2023-2#131]
No había tenido ningún problema con el control hasta que en la pregunta 6, se me reinició la página y ahora me aparece el siguiente error cada vez que quiero correr algun código en cualquier pregunta: UsageError: Cell magic `%%sql` not found.
Cerré la página, volví a abrir el documento y sigue sin funcionar. ¿como se arregla?

**Comment by PkAlvaro** [comment]
Vuelve a ejecutar todas las celdas desde el principio, esto ocurre cada que se reinicia colab
