### ISSUE TITLE
Dato 'costo' presente en dos tablas distintas -Proyecto 2 Impar

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#135]
Hola! En la tabla subscripciones y en la tabla proveedores entregadas, ambas tienen una columna llamada costo. Me estaba fijando y para cualquier subscripcion a un proveedor el costo se mantiene constante y es el mismo que aparece en la tabla proveedores. 
Entiendo que esto mismo ocurre con los nombres que tambien aparecen en las dos tablas, pero sucede una persona se pudo haber subscrito a un proveedor en un minuto que el costo era más bajo. 
Entonces mi pregunta es: Podemos asumir que el costo entre las dos tables va a ser siempre el mismo y que por lo tanto los datos de la fila costo en la tabla subscripciones son redundantes?

**Comment by Paldana99** [comment]
Hola, no es redudante ya que el costo de subscripcion es lo que pago el usuario en la fecha indicada. Como comentas el costo puede variar en el tiempo para un proveedor pero este no afecta al precio que pago el usuario en su momento

**Comment by SantiagoDLCB** [comment]
En ese caso. El costo de subscripcion y la fecha de inicio no es redundante con los montos de la tabla pago_v2 y sus fechas? En esencia  la unica información adicional que tendria la tabla pagos seria en caso de que haya pagado una pelicula con costo adicional.

**Comment by Paldana99** [comment]
Ahí ya dependerá de como modelizan el esquema.
