### ISSUE TITLE
consulta de los datos en usuarios_actividades.csv, grupo par

### ISSUE THREAD

**Issue by Nicolas413** [IIC2413/Syllabus-2023-2#137]
tengo una duda a que se refieren con la columna "cantidad" en esta tabla ya que lo que se ve son los usuarios y tambien las reseñas que se realiza el usuario?

**Comment by Paldana99** [comment]
esta especificado en el readme de los datos https://github.com/IIC2413/Syllabus-2023-2/tree/main/Proyecto/Entrega2/Datos
