### ISSUE TITLE
Consultas varias respecto a datos grupo impar entrega 2

### ISSUE THREAD

**Issue by panchouc** [IIC2413/Syllabus-2023-2#138]
Tengo una duda respecto al enunciado y los datos que se entregan. En la parte 2.3 dice que: pre-procesar los datos sin pérdida de información para que se ajusten a tú esquema final. Resulta que observando los datos, en varias tablas, excepto la de usuarios.csv hay columnas con campos vacíos, ¿Debemos rellenar las filas que tienen datos vacíos? o simplemente ¿Dejamos estas filas tal como están?. En caso de que debamos rellenar los archivos que tienen filas vacías, ¿Se puede hacer esto asignando números aleatorios? O podemos quizás empezar a cruzar tablas y empezar a recuperar datos desde otros archivos?

También tengo preguntas respecto a que significan algunas columnas de los datos, queria saber si

uid = ID del usuario
subs_id = ID de suscripciones
pro_id = ID del proveedor

y respecto a cid, sid, pid, ¿A qué corresponden estos ID?

Respecto al archivo `multimedia.xlsx` a que hace referencia la columna número? De antemano muchas gracias.

**Comment by Paldana99** [comment]
Hola, no se deben agregar datos. Su modelo debe ser creado de forma que estos espacios vacios queden minimos optimizando o dividiendo tablas. Esto se logra normalizando el esquema.

Si a eso se refiere esos id.
cid = capitulo id
sid = serie id
pid = pelicula id

número hace referencia al número de la temporada, fijarse que solo esta indicado para las series.
