### ISSUE TITLE
Diagrama E/R

### ISSUE THREAD

**Issue by Tomas2424** [IIC2413/Syllabus-2023-2#139]
Hola una pregunta, en un mismo "Ovalo" puedo poner todos los atributos para que se vea mas ordenado?
![Captura de pantalla 2023-10-05 125837](https://github.com/IIC2413/Syllabus-2023-2/assets/127431889/99c357fb-7ddd-43c8-a28f-f7356ed86294)

**Comment by Paldana99** [comment]
Mantenerse a como se realizo en las guías y slides. Ver Guía 4

**Comment by josegarafulic** [comment]
Si ya lo hicimos mediante el agrupamiento de los atributos en un mismo ovalo, esta incorrecto?. Porque en syllabus de años pasados habían algunas guías que lo presentaban así y no veo porque estaría mal, simplemente es otra manera. @Paldana99

**Comment by Paldana99** [comment]
Dejaría explicito que se basaron en esas guías de otro semestre, poniendo el link en el informe.
