### ISSUE TITLE
Duda con NULL

### ISSUE THREAD

**Issue by criism0** [IIC2413/Syllabus-2023-2#14]
Hola buenas! 

Tengo una duda con el manejo y como tratar en general la aparición de un NULL como valor en alguna tabla, no me queda claro si se debe considerar como un valor especial, valor desconocido y si este tiene alguna implicancia en los operadores relacionales, es decir si aplico por ejemplo una proyeccion sobre una columna de una tabla con n elementos y un null, el resultado me entregará n tuplas o n + 1 considerando el null dentro de esta proyección.

Muchas gracias de antemano!

**Comment by antoniablanco** [comment]
Hola, NULL hace referencia a que no se tiene información, en programación es una referencia a la nada. Con respecto a tu segunda pregunta, entregaría n+1 considerando null dentro de la proyección.
