### ISSUE TITLE
Conexión entre Entidades

### ISSUE THREAD

**Issue by josegarafulic** [IIC2413/Syllabus-2023-2#140]
Hola, si la entidad "pagos" tiene un atributo de id asociado a la entidad "multimedia", otro atributo asociado a "suscripciones" y otro a "proveedores", tiene que estar conectado directamente mediante una relación distinta a cada una de esos 3 entidades?

La alternativa es que si por ejemplo "pago" tiene una relación con "suscripciones", y "suscripciones" tiene una relación con "proveedor", no es necesario hacer la conexión directa entre "pagos" y "proveedor" ya que ya hay una relación existente que tiene como intermediario a "suscripción".

**Comment by Paldana99** [comment]
Esto dependerá de como modelizaron el esquema. Recordar que no tienen por que seguir como se presenta en los datos csv, Lo importante es que respecten BCNF o 3NF y justificarlo
