### ISSUE TITLE
Creación de nuevos atributos y eliminación de atributos existentes, grupo impar

### ISSUE THREAD

**Issue by franfonte** [IIC2413/Syllabus-2023-2#141]
Se pueden agregar atributos (como ids o cosas por el estilo) para simplificar las relaciones?. Tambien es posible eliminar atributos de tablas que son redundantes? (por ejemplo eliminar proveedor y costo de la tabla "subscripciones" ya que esta tabla ya contiene el id del proveedor y la tabla proveedor ya contiene su costo)

**Comment by tnaspee** [comment]
Tengo la misma duda, pero se expande por ejemplo a en la tabla multimedia, para poder normalizarla de forma más fácil, puedo quedarme con el cid sólamente, viendo que no se repiten?

**Comment by Paldana99** [comment]
Pueden modificar como quieran, pero importante es no perder información ni que se altere.
