### ISSUE TITLE
Duda tabla usuario_proveedor, grupo par

### ISSUE THREAD

**Issue by Gcamposbriceno** [IIC2413/Syllabus-2023-2#146]
Hola, no nos queda claro de qué sirve, o si sirve de algo la tabla usuario_proveedor, le falta algún dato?

**Comment by Paldana99** [comment]
como lo indica relaciona usuarios con proveedores.

**Comment by Gcamposbriceno** [comment]
Ok, eso significa que un usuario le compra todos los juegos al mismo proveedor? Porque en pagos_v2.csv se muestran pagos del mismo usuario a distintos proveedores

**Comment by Paldana99** [comment]
No necesariamente, un usuario puede comprar a distintos proveedores.
