### ISSUE TITLE
Duda sobre suscripciones grupo par

### ISSUE THREAD

**Issue by martineyz** [IIC2413/Syllabus-2023-2#147]
A partir de los datos entregados no me queda claro como saber de que proveedor es la suscrpcion de un usuario a un juego.  Esto me parece raro ya que en proveedores hay más de un proveedor para un mismo juego de suscripcion.

**Comment by Paldana99** [comment]
En pagos se relaciona cada pago de un usuario con un juego hacia un proveedor.

**Comment by eiacobelli** [comment]
Tengo la misma duda. No entiendo como funcionan las filas de la tabla pagos, cuando está vacío el campo de proveedor. Un usuario puede suscribirse a un juego sin pasar por un proveedor?

**Comment by ktherine0** [comment]
tengo la misma duda que el compañero, si no hay información del proveedor o videojuego en un pago, sigue siendo importante? o que significa eso? que pago sin un proveedor? o por ejemplo sin elegir un videojuego?

**Comment by coniossai** [comment]
Hola!! Todos tenemos la misma duda. Ya han preguntando como 3 veces a través de issues y todavía no contestan. Pueden contestar por favor?

**Comment by Paldana99** [comment]
Disculpen la demora, para los juegos de subscripcion se trata de un error. Pueden ustedes poner un id_proveedor aleatorio sin problema

**Comment by martineyz** [comment]
> Disculpen la demora, para los juegos de subscripcion se trata de un error. Pueden ustedes poner un id_proveedor aleatorio sin problema

Para asignar el id de forma aleatoria, ¿hay que tener en cuenta que el proveedor esté relacionado con el usuario en usuario_proveedor o no es necesario?

**Comment by Paldana99** [comment]
sería lo optimo para mantener consistencía
