### ISSUE TITLE
[entrega 2] duda sobre el concepto de 'subgenero inmediato'

### ISSUE THREAD

**Issue by ibgarrido** [IIC2413/Syllabus-2023-2#148]
Hola!, en el enunciado, con respecto a la realizacion de la busqueda de peliculas a un genero o a un subgenero inmediato, al decir subgenero inmediato se refiere a que este subgenero haya sido utilizado como genero? (Por ejemplo hay peliculas y/o series que poseen en genero un subgenero). 

Saludos.

**Comment by Paldana99** [comment]
No, se refiere a que pertenezca a unos de los subgéneros inmediatos del seleccionado. Por ejemplo si tenemos la película A de genero G1 y película B de subgénero SG1.
Si sabemos que SG1 es subgénero de G1.
Entonces la consulta debe retornar tanto A como B
