### ISSUE TITLE
Duda plataformas proveedores grupo par

### ISSUE THREAD

**Issue by TomasAltermatt** [IIC2413/Syllabus-2023-2#149]
Hola, viendo los datos de la tabla proveedores noté que cada proveedor solo provee juegos para una plataforma en particular. ¿Se puede asumir que siempre será así, o debemos generalizar igualmente el esquema para considerar varias plataformas por proveedor?

**Comment by Paldana99** [comment]
Es mejor mantener la generalización, de forma que un proveedor pueda tener varias plataformas si quisiera. No debería complicar el modelo.

**Comment by TomasAltermatt** [comment]
Entiendo, muchas gracias!
