### ISSUE TITLE
Duda sobre tipo de datos en los csv

### ISSUE THREAD

**Issue by rmezaa** [IIC2413/Syllabus-2023-2#150]
Hola! Tengo una duda acerca de como se nos entregan los datos, ya que en el caso de multimedia, id_pelicula e id_serie son de tipo float, pero en proveedores son de tipo int, siendo el mismo valor pero en diferente formato. En el caso de querer hacer joins donde los id sean iguales, ¿es más recomendable pasar el float a int en la consulta, o editar los csv (los nuevo csv adaptados) y pasarlos a int (haciendo una leve modificación a los datos pero sin pérdidas al fin y al cabo)? Gracias

**Comment by Paldana99** [comment]
Si no hay perdida de información preferir usar int para los id.
