### ISSUE TITLE
ejecución archivo php

### ISSUE THREAD

**Issue by adribastiasm** [IIC2413/Syllabus-2023-2#153]
Hola! Si queremos ver nuestro php visualmente, cómo lo hacemos? Hay que instalarse algún programa?

**Comment by Paldana99** [comment]
a que se refieren con visualizar?

**Comment by gsinay** [comment]
Hola @Paldana99 ! Creo que tengo la misma duda. En mi caso me refiero a como poder "abrir" el archivo index.php que está dentro del servidor en algún browser tipo chrome para poder ir probando nuestras consultas.

**Comment by Paldana99** [comment]
Si suben los archivos a la carpeta Sites pueden ver los cambios en:
https://bachman.ing.puc.cl/~grupoXX
o navegar directamente a algun archivo
https://bachman.ing.puc.cl/~grupoXX/nombre_carpeta/nombre_archivo.php

**Comment by adribastiasm** [comment]
No me funcionaa, me sale "The requested URL was not found on this server"

**Comment by Paldana99** [comment]
Me falto un backslask ahi actualize la url

**Comment by adribastiasm** [comment]
Ahí sii, gracias :)
