### ISSUE TITLE
E2 Grupo Par - géneros y subgéneros

### ISSUE THREAD

**Issue by MariaJoseSilva** [IIC2413/Syllabus-2023-2#155]
Hola!
En la issues #73de la E1, se aclaran que  "No, un género no puede ser subgénero"

En los csv entregados se encuentra el archivo genero_subgenero donde dos de sus filas son
> genero - subgenero
> FPS - Supervivencia
> Guerra - FPS

Para que lograr que se cumpla lo planteado en la issue mencionada, es necesario que FPS sea género o subgénero, pero no ambas. Mi pregunta es, si queda a nuestro criterio como categorizar a FPS (como género o subgénero)? Lo mismo ocurre en otros casos

Muchas gracias!

**Comment by Paldana99** [comment]
Hola!
2 opciones o pueden borrar esa fila que provoca el error. O hacer la diferencia de que FPS subgénero es distinto a FPS genero. Dado que cuando se hagan consultas SQL deberían diferenciarse por la columna en que se busca cada una.

**Comment by MarquezFelipe** [comment]
Hola, no es que se puedan borrar "el error" ya que absolutamente todos los subgeneros son también géneros, lo cual choca completamente con que un género no pueda ser subgénero. Asumo que se rectificará esa respuesta ya que si no no podría exisitir ningún subgénero.

**Comment by Paldana99** [comment]
La solución dada no rompe con lo que dices. Recomiendo dejar escrito el supuesto que tomaron si así lo hicieron para facilitar la corrección.

**Comment by Paldana99** [comment]
Igual revisar la version 3 del archivo, no se encuentra el error que se indica.
