### ISSUE TITLE
E2 Grupo par - Horas de juego/Atributo Cantidad

### ISSUE THREAD

**Issue by MariaJoseSilva** [IIC2413/Syllabus-2023-2#156]
Hola!
En la E1 se mencionaba que la plataforma debe tener registro de las horas de juego, en la E2 no se menciona nada al respecto, asumimos que ya no se debe considerar? o por el contrario hay que considerar las entregas como acumulativas?

También, tengo la duda sobre a qué hace referencia el atributo _cantidad_ del csv _usuarios_actividades_. 

Muchas gracias!

**Comment by Paldana99** [comment]
cantidad hace referencia a la cantidad de horas jugadas.
Ver readme de datos https://github.com/IIC2413/Syllabus-2023-2/tree/main/Proyecto/Entrega2/Datos
