### ISSUE TITLE
E2 grupo par, videojuego con id 49

### ISSUE THREAD

**Issue by cristobalSaravia** [IIC2413/Syllabus-2023-2#157]
Hola, creo que encontré un problema en los datos de actividades. 
En usuarios_actividades hay una reseña del usuario con id 102 a un juego con id 49 (linea 1120):
![image](https://github.com/IIC2413/Syllabus-2023-2/assets/110921243/72ff3562-f3b1-4cb9-8a9a-4be181458455)
Pero buscando en la tabla de videojuegos, no existe un videojuego con id 49.

**Comment by Paldana99** [comment]
Hola gracias por notarlo, en ese caso pueden eliminar la reseña

**Comment by cristobalSaravia** [comment]
Por si acaso, hay otra reseña con id_videojuego =2 que tiene el mismo problema, pero creo que solo son estas dos las que tienen problemas, el resto está bien.
