### ISSUE TITLE
Manejo de Nulos

### ISSUE THREAD

**Issue by josegarafulic** [IIC2413/Syllabus-2023-2#159]
Tenía la consulta si en alguna tabla se puede guardar los datos de tanto las películas como los capítulos?. Que cuando sea película, el dato de capitulo quede en nulo y viceversa. O eso sería incorrecto y todas las tablas tienen que estar separadas por series/capítulos y películas?

Mi segunda duda es acerca de la tabla que muestra los proveedores con las películas o capítulos que incluyen. Se puede poner en la misma tabla una columna de precio y que sea nulo siempre que el material este incluido en la suscripción? O habría que hacer una tabla separada con los materiales que no se incluyen en las suscripciones y su respectivo precio?

**Comment by Paldana99** [comment]
La idea es evitar al máximo tener columnas que incluyan muchos nulos ya que se consideraría como mal modelo de bdd. Si bien pueden crear atributos si lo estiman convenientes evitar tener muchos nulos
