### ISSUE TITLE
Duda relaciones entre tablas y preguntas 5 y 6

### ISSUE THREAD

**Issue by cebabeltran** [IIC2413/Syllabus-2023-2#16]
Hola! Estoy un poco confundido en cuanto a los atributos y sus relaciones entre tablas:
- ¿Qué representa la tabla _Pub_Autor_? Entiendo que el _id_autor_ hace referencia a los nombres de la tabla _Autor_, pero no comprendo a qué se refiere (o qué significa) el _id_pub_ y la _posición_autor_.
- No entiendo a qué se refiere la tabla _Publicacion_. Asumo que el atributo titulo no son títulos de libros, ya que no coinciden con los títulos de la tabla _Libros_, pero no sé si estoy en lo correcto. y ¿el _id_pub_ hace referencia al atributo del mismo nombre en la tabla _Pub_Autor_?

También tengo consultas con respecto a las preguntas 5 y 6:
- En la pregunta 5, se refiere a los autores que son "editores de todos los libros". Me confunde esta premisa, ya que en la tabla _Libros_ cada libro solo tiene un _id_editor_, y estos valores no coinciden en toda la columna, por lo que no habría un autor que sea "editor" de todos los libros de la tabla _Libro_. No sé si estoy malinterpretando el enunciado o las relaciones entre tablas.
- En la pregunta 6 se piden los autores que "no son autores de ningún libro", no entiendo cómo sabemos quién es el autor de algún libro. La tabla _Libro_ solo hace referencia a los editores (que según entiendo representan autores, pero no necesariamente a los autores de dicho libro), ¿hay algún otro atributo en alguna tabla que tenga correlación entre un libro y su autor?

Muchas gracias de antemano!

**Comment by andrius6789** [comment]
😥

**Comment by RICARDOOVIEDO** [comment]
Por si no leyeron el anuncio de los profesores, la pregunta 5 y 6 fueron eliminadas del control 1! Saludos
