### ISSUE TITLE
Tabla Pagos

### ISSUE THREAD

**Issue by josegarafulic** [IIC2413/Syllabus-2023-2#160]
La tabla pagos que se nos entrega tiene tanto los pagos de peliculas específicas como los pagos de subscripciones. Es necesario separar en 2 tablas para que no hayan tantos NULL?

Archivo imagen.

<img width="604" alt="Captura de pantalla 2023-10-14 a la(s) 18 01 24" src="https://github.com/IIC2413/Syllabus-2023-2/assets/81305523/9bec6004-cd4d-438b-861c-1737e492e2e2">

**Comment by Paldana99** [comment]
Hola!
Tener una columna con tantos NULL es considerado como mala practica y es una consecuencia de un mal diseño de bdd. La idea es evitar que una columna tenga tantos null, por lo que si separarlo probablemente sea una buena solución, ademas que facilita cumplir con BCNF o 3NF
