### ISSUE TITLE
Duda diagrama ER

### ISSUE THREAD

**Issue by Pabloleiva00** [IIC2413/Syllabus-2023-2#161]
Hola, quería consultar cual es el diagrama que debemos presentar la la E2:
- Diagrama de la E1.
- Diagrama de la E1 con las acotaciones de los ayudantes en la corrección.
- Diagrama que se ajuste a los datos de la E2.

Muchas gracias de antemano.

**Comment by Paldana99** [comment]
El diagrama debe representar a como armaron su bdd. Es decir que deben tomar las correcciones que les hicieron en la E1 pero igualmente se pueden apoyar en los datos que se les entrego, para corregir aun mas.
Recuerden que los datos entregados deben manejarlos y limpiarlos de forma que se adapten a su modelo que crearon. Y recuerden que deben de cumplir con la normalización
