### ISSUE TITLE
Datos Subgeneros - Grupo Impar

### ISSUE THREAD

**Issue by MatiasAPineda** [IIC2413/Syllabus-2023-2#162]
Tengo una duda con respecto al csv de los subgeneros. Los datos Null, osea, los generos que no tiene subgenero, pueden ser rellenados con subgeneros arbitrarios? o solo hay que separar la tabla en generon con subgenero y los que no para minimizar la cantidad de nulos?

**Comment by Paldana99** [comment]
No todos los géneros tienen necesariamente un subgénero. Por lo que no deben rellenar los datos. Y si es buena idea separar los datos para minimizar los nulos
