### ISSUE TITLE
Diagrama E/R

### ISSUE THREAD

**Issue by tnaspee** [IIC2413/Syllabus-2023-2#164]
Hola! Como hay que normalizar el modelo relacional, el modelo E/R que hay que entregar es el normalizado también? O ese lo dejamos sin normalizar, y al pasarlo a modelo relacional hacemos los cambios.
Por que si tenemos que hacer también el modelo E/R normalizado a partir del modelo relacional, como que se daría vuelta el orden del enunciado.
Muchas gracias y saludos

**Comment by Paldana99** [comment]
Hola el modelo E/R y relacional son lo mismo pero visualizados diferente. Por lo que si uno esta normalizado el otro igual. La justificación la deben hacer en el relacional ya que es mas sencillo, pueden ocupar la guiá 5 como ejemplo.
