### ISSUE TITLE
Proveedores Grupo Par

### ISSUE THREAD

**Issue by MarquezFelipe** [IIC2413/Syllabus-2023-2#165]
Buenas, hay 3 tablas que hacen uso de proveedores, la tabla del mismo nombre (con ids del 1 al 6), la tabla usuario_proveedor (con ids de proveedores del 1 al 6) y la tabla pagos, que por algún motivo hace referencia a proveedores con ids múltiplos de 10 (10, 20, 30, 40, 50, 60), es esto último un typo y deben ser divididos por 10?
Aprovecho de preguntar por la utilidad de la tabla usuario_proveedor siendo que en la de pagos se relacionan ya usuarios con proveedores y teniendo en cuenta que un usuario se relaciona con distintos proveedores dependiendo el juego, hace sentido mantener los ids relaciondos en la tabla de pagos y separarlos en otra tabla no trae beneficios sino que incluso confusión al no dar info de que juego está pagando el usuario a ese proveedor sabiendo que puede poseer mútiples juegos. Muchas gracias

**Comment by Paldana99** [comment]
La version 2 de los datos no tiene este error de multiplos de 10.
Dependerá de como modelen, queda a su decision como relacionan usuario y proveedor. importante mantener la normalizacion
