### ISSUE TITLE
modelo entidad/relación a modelo relacional

### ISSUE THREAD

**Issue by lolenn10** [IIC2413/Syllabus-2023-2#166]
Hola buenas, en el enunciado cuando dicen traspasar el modelo entidad/relación al modelo relacional se refiere a modificar el mismo modelo entidad/relación agregando sus llaves, atributos etc, o crear un nuevo diagrama?

**Comment by Paldana99** [comment]
Hola pueden ver la guía 4 como ejemplo. Pero incluyendo lo que se pide en el enunciado.
