### ISSUE TITLE
Atributo "cantidad" [Grupo Par]

### ISSUE THREAD

**Issue by matiasolivab** [IIC2413/Syllabus-2023-2#167]
Hola! He visto varias issues no respondidas sobre el atributo cantidad del csv usuarios_actividades por lo que me gustaria saber a que hace referencia este.

Gracias

**Comment by JoseTomasIbanez** [comment]
Tenemos la misma duda!!

**Comment by spoblete44** [comment]
misma duda tb :(

**Comment by Paldana99** [comment]
Hola en el readme de los datos esta especificado.
https://github.com/IIC2413/Syllabus-2023-2/tree/main/Proyecto/Entrega2/Datos
