### ISSUE TITLE
Precio peliculas arrendadas constante en el tiempo Grupo Impar

### ISSUE THREAD

**Issue by benjahuenchunir** [IIC2413/Syllabus-2023-2#170]
En el issue [#135](https://github.com/IIC2413/Syllabus-2023-2/issues/135) se dijo que el atributo "costo" presente en el archivo proveedores y arriendos no es redundante, pues puede variar con el tiempo, siendo uno de ellos el costo actual y el otro bajo el cual se inscribió el usuario en ese momento.

¿Para el valor "precio" del archivo proovedores que simboliza el precio para arrendar la pelicula se debe considerar esto mismo?

**Comment by Paldana99** [comment]
Si puede seguir la misma idea.
