### ISSUE TITLE
Consulta 6, grupo impar

### ISSUE THREAD

**Issue by VicenteSanMartin** [IIC2413/Syllabus-2023-2#172]
Hola! La consulta 6 dice "Dado un username ingresado por el usuario, muestre todas las series para las cuales el usuario ha visto más de un capítulo durante el último año". Respecto a eso, si un usuario ve dos veces un mismo capítulo de una serie en el último año, eso contaría como que el usuario vio más de un capítulo de esa serie?

**Comment by Paldana99** [comment]
Diría que si, dejaría anotado igual en el informe que lo tomaron como supuesto.
