### ISSUE TITLE
Significado Atributos Grupo Impar

### ISSUE THREAD

**Issue by maxo2727** [IIC2413/Syllabus-2023-2#173]
- En los datos multimedia, a que se refiere el atributo "numero"?
- En los datos proveedores, a que se refiere el atributo "disponibilidad"?

**Comment by caramelnico** [comment]
Tenemos la misma duda con mi pareja.

**Comment by Paldana99** [comment]
numero es el numero de la temporada
Como se menciona en la entrega 1 es la cantidad de tiempo de días que estará disponible
