### ISSUE TITLE
Inconsistencia visualizaciones de series ultimo año.

### ISSUE THREAD

**Issue by gsinay** [IIC2413/Syllabus-2023-2#175]
Hola. Creo que hay un error en el enunciado. En la consulta 6 de los grupos impares se pide mostrar las visualizaciones hechas por los usuarios en el último año. Sin embargo, las visualizaciones en los datos entregados son del 2020-2021, por lo que la consulta siempre retorna vacía. ¿Consideramos un rango mayor (3 años) para realizar la consulta?

**Comment by lpalacios1** [comment]
Si,  considera un rango mayor para realizar la consulta.
