### ISSUE TITLE
Grupo impar - duda genero subgénero

### ISSUE THREAD

**Issue by leslydelahozb** [IIC2413/Syllabus-2023-2#177]
Hola, con mi compañera tenemos una duda sobre cómo identificar los géneros y subgéneros de las series y películas de los datos que nos entregaron, ya que en la tabla multimedia este sólo la columna género. Además, en la tabla género-subgénero los subgéneros también son géneros, por lo que no sabemos como distinguir entre estos, ya que según el enunciado de la entrega 1 una película puede tener uno o más géneros y subgéneros.

**Comment by monserratf** [comment]
Hola! aún leyendo la issue #155 no me queda claro, ya que recomiendan borrar el error, pero todos lo subgéneros son también géneros y no se especifica en los datos entregados, ya que solo está la columna de género, ¿uno puede asumir que no hay subgéneros?

**Comment by Paldana99** [comment]
No se puede asumir. 
Solo se recomienda borrar cuando sucede lo mostrado en la issue, el cual solo pasa con FPS. O se puede tomar la solución que se identifique por columna, dado que a nivel consulta se realiza la diferencia igual.
