### ISSUE TITLE
E2 Géneros y subgéneros - Grupo Par

### ISSUE THREAD

**Issue by MariaJoseSilva** [IIC2413/Syllabus-2023-2#178]
Hola!

Dentro de las issues de la E1, se indica que un subgénero está si o si asociado a un género único, sin embargo, dentro de los csv entregados el subgénero RPG es subgénero de los géneros Simulador y Aventura, es decir, no se cumple esta condición.
¿Qué podemos hacer en este caso?

Otra duda que tengo, se relaciona sobre cuales géneros los consideramos como tal. Por ejemplo, en el archivo genero_subgenero.csv, se tiene
> genero, subgenero
> Turn-based strategy (TBS), null
> Estrategia,` Turn-based strategy (TBS)

TBS se encuentra en la columna género y no tienen ningún subgénero asociado, pero también  se encuentra en la columna subgénero, indicando que es subgénero de  Estrategia. ¿Podríamos asumir que TBS es solo subgénero y no es género? o es mejor considerar que todos los subgéneros son también géneros. 

Mi pregunta va enfocada a la consulta 4, en la que se le pide al usuario seleccionar un género, sobre cuales nombres desplegar para que el usuario seleccione.

Muchas gracias!

**Comment by Paldana99** [comment]
Hola ver #155 debería responder las dudas

**Comment by adribastiasm** [comment]
Tengo la misma duda y en la issue 155 no logré entender. Un subgenero si o si está asociado a un genero y en caso contrario hay que eliminar las filas??

**Comment by Paldana99** [comment]
Si ven algo que contradice el enunciado, pueden hacer un supuesto y dejarlo por escrito.
