### ISSUE TITLE
Nombre de atributos 1 b)

### ISSUE THREAD

**Issue by martineyz** [IIC2413/Syllabus-2023-2#18]
En la pregunta 1 b) se puede asumir que uno de los 2 atributos es renombrado para que se llamen igual y así poder realizar la sustraccion correctamente?

**Comment by lfb1206** [comment]
Para realizar una sustracción no es necesario que los nombres de los atributos sean iguales.

**Comment by MariaJoseSilva** [comment]
Hola!
Tengo una confusión respecto a la materia, porque había entendido lo mismo que el compañero/a. En este caso que los atributos son distintos, el atributo de la tabla resultante que nombre recibe?
Gracias, buen fin de semana.

**Comment by lfb1206** [comment]
Hola! Recibe el nombre del atributo al cual le están realizando la resta.
