### ISSUE TITLE
E2 - Horas de juego - Grupo Par

### ISSUE THREAD

**Issue by ktherine0** [IIC2413/Syllabus-2023-2#180]
Hola, tengo una duda respecto a que para el mismo usuario y videojuego salen dos cantidades, no entiendo si es un error o efectivamente puede haber más de un dato de horas de juego para un mismo usuario y videojuego.
![image](https://github.com/IIC2413/Syllabus-2023-2/assets/127222331/c34440d3-b9ee-46ed-91d1-8379119b5ff1)

**Comment by lolenn10** [comment]
Tenemos la misma duda

**Comment by matiasolivab** [comment]
Nosotros tambien tenemos la misma duda!

**Comment by andrius6789** [comment]
x3

**Comment by Paldana99** [comment]
Pueden eliminar los duplicados
