### ISSUE TITLE
acceso (No se pudo conectar a la base de datos) 

### ISSUE THREAD

**Issue by LunaGarces** [IIC2413/Syllabus-2023-2#181]
#### Hola, al tratar de usar los datos de nuestras tablas, la pagina me arroja este error, pero la contraseña en data.php esta correcta, que es lo que puede estar fallando? 

 No se pudo conectar a la base de datos: PDOException: SQLSTATE[08006] [7] connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL: password authentication failed for user "grupo19" connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL: password authentication failed for user "grupo19" in /home/grupo19/Sites/config/conexion.php:6 Stack trace: #0 /home/grupo19/Sites/config/conexion.php(6): PDO->__construct() #1 /home/grupo19/Sites/consultas/1.-consulta.php(6): require('...') #2 {main}

**Comment by Paldana99** [comment]
la constraseña funciona en ssh? no hay algún espacio o mayúscula? estan apuntando a la bdd correcta e2?

**Comment by LunaGarces** [comment]
Puedo acceder súper bien, el problema lo tira al tratar de hacer las consultas, yo creo que mi error es quizá en lo otro que mencionas, pero la verdad no se como verificarlo
Sent from my iPhone

On 17-10-2023, at 19:43, Pablo Aldana ***@***.***> wrote:

﻿

la constraseña funciona en ssh? no hay algún espacio o mayúscula? estan apuntando a la bdd correcta e2?

**Comment by Nicolas413** [comment]
Hola me dio el mismo error, pero las credenciales estan bien y no se a modificado nada de conexion.php.

**Comment by LunaGarces** [comment]
Revise lo que me mencionan y cambie el port, para verificar que ese no fuera el error, pero aun no puedo acceder a las tablas desde la pagina :(
Cualquier ayuda la agradezco

El 17-10-2023, a las 22:48, Nicolas413 ***@***.***> escribió:



Hola me dio el mismo error, pero las credenciales estan bien y no se a modificado nada de conexion.php.

**Comment by Giovannicopello77** [comment]
Tengo el mismo error no me deja conectarme a mi base de datos desde mi aplicación web

**Comment by Paldana99** [comment]
para visualizarlo en web deben acceder a la url: https://bachman.ing.puc.cl/~grupoXX/
en data el host es localhost y port 5432 tal como esta definido en el archivo conexion.php de la ayudantía. Que no es necesario modificar

**Comment by Srencoret** [comment]
Me pasa que accedo a ese url con el número del grupo, el host lo tengo como localhost y el puerto 5432 y aun así no funciona. No he modificado el archivo conexión por lo que no se qué podría estar mal

**Comment by LunaGarces** [comment]
Me pasa eso to mismo

On 18-10-2023, at 13:08, Srencoret ***@***.***> wrote:

﻿

Me pasa que accedo a ese url con el número del grupo, el host lo tengo como localhost y el puerto 5432 y aun así no funciona. No he modificado el archivo conexión por lo que no se qué podría estar mal

**Comment by Paldana99** [comment]
me podrían enviar una copia de su archivo config a pablo.aldana@uc.cl

**Comment by Paldana99** [comment]
La contraseña que indican en el archivo data.php debe ser del usuario de psql postgres sql. No aquella que se utiliza para ssh. Recomendamos que sean iguales para no tener confusión.

**Comment by renaa-m** [comment]
Hola!! Con mi compañero estamos con el mismo problema:( en teoría nuestras claves de ssh y psql son iguales y no sabemos que hacer.

**Comment by Paldana99** [comment]
prueben cambiando la contraseña de psql
