### ISSUE TITLE
Requerimientos datos esquemas

### ISSUE THREAD

**Issue by rmezaa** [IIC2413/Syllabus-2023-2#184]
Hola, para el esquema relacional hay que mencionar si el tipo de dato si es int, float, las keys etc, ¿pero es necesario decir que es not null?
Y por otro lado, ¿es necesario poner el tipo de dato tanto en el esquema relacional como en el diagrama E/R? O basta con el esquema, para que no tenga tanta información el E/R.
Gracias.

**Comment by andrius6789** [comment]
up
