### ISSUE TITLE
Duda modelo E/R

### ISSUE THREAD

**Issue by cebabeltran** [IIC2413/Syllabus-2023-2#186]
Hola, tengo una duda relacionada al diagrama E/R y cómo representar ciertas relaciones. Si en el modelo tenemos una tabla de Pagos, con el atributo pago_id y los atributos de usuario_id y subscripcion_id, ¿Pagos sería una entidad o una relación? Porque en cierto sentido relaciona a las tablas usuario y suscripción, pero tiene su propia llave (pago_id). Gracias de antemano!

**Comment by Paldana99** [comment]
Dependerá de como lo modelen, pero lo mas importante es que vean las dependencias para cumplir con BCNF o 3NF. Tal vez deban crear más tablas para cumplir con eso.
