### ISSUE TITLE
Relación publicación y libro.

### ISSUE THREAD

**Issue by ktherine0** [IIC2413/Syllabus-2023-2#19]
Hola, tengo una confusión sobre que es una publicación y que relación tiene con el libro? porque el id de la publicación (que tiene su titulo) se relaciona con un libro que tiene otro titulo. Entonces, una publicación seria por ejemplo una reseña con tal titulo de tal libro?
No entiendo realmente en que relación se qué autor es el "autor" de tal libro. Porque en la tabla libro solo mencionan el editor, que entiendo no es lo mismo que el autor. Y el autor de una publicación se relaciona con un libro, pero no se si eso significa que es autor del libro.
Espero entiendan mi confusión, gracias.

**Comment by Nicolas413** [comment]
tengo una duda con lo mismo, cual seria el autor de un libro si estos se relacionan con las publicaciones? o las publicaciones son como "editoriales"?

**Comment by RICARDOOVIEDO** [comment]
El editor en la tabla Libro es el autor. No se si eso hace que quede más claro tu pregunta!
