### ISSUE TITLE
grupo par, datos faltantes

### ISSUE THREAD

**Issue by lolenn10** [IIC2413/Syllabus-2023-2#190]
En videojuegos_V2, tanto la id_videojuego 49 como la 2 no se encuentran en los datos. Pero en usuarios_actividades  si existe el id_videojuego 49 y el 2. Modificamos los datos para que existan? 

Muchas gracias de antemano.

**Comment by Paldana99** [comment]
Pueden agregarlo o eliminarlo, deja en el informe cualquier modificación que hicieron para que el ayudante este al tanto
