### ISSUE TITLE
Duda sobre consultas

### ISSUE THREAD

**Issue by rmezaa** [IIC2413/Syllabus-2023-2#191]
Hola! Como en las consultas hay que hacer joins entre tablas, y no especifican que atributos mostrar, por ejemplo en la p1 impar que es muestre todas las peliculas juntos sus proovedores, hay que mostrar solo el nombre de cada pelicula o todos sus atributos? Porque en general dice muestre las series o muestre las peliculas. O puede quedar a interpretacion de nosotros y lo ponemos en el documento como supuesto? Como son varios joins si hacemos select * son muchos atributos y algunos repetidos.

**Comment by Paldana99** [comment]
Efectivamente, como estamos creando un sitio web, mostrar atributos que sean útiles para un usuario. hacer select * puede ser excesivo. Por ejemplo para películas mostrar su id, y titulo, con su genero. etc...
Lo importante es que un ayudante pueda ver rápidamente si la consulta arroja un resultado coherente.
