### ISSUE TITLE
Grupo impar. Pregunta 6, ningún dato en el último año.

### ISSUE THREAD

**Issue by aLotOfGluten** [IIC2413/Syllabus-2023-2#194]
¡Hola! Tengo una duda acerca de la pregunta 6 de grupo impar.

Hay que buscar todas las series para las cuales un usuario partícular haya visto más de un capítulo en el último año, pero no hay ningún capítulo en los datos que tenga como fecha el año 2022 o 2023.

¿Hay que suponer alguna fecha? O ¿es correcto utilizar la función current_date?

¡Gracias!

**Comment by Paldana99** [comment]
Hola,
#175 como se dijo ahí puedes considerar un rango mayor para que se muestre algún resultado. Puedes tomar un rango de 3 años.
