### ISSUE TITLE
problemas con servidor

### ISSUE THREAD

**Issue by LunaGarces** [IIC2413/Syllabus-2023-2#197]
hola, el dia de hoy no he podido conectarme al servidor, al intentarlo arroja el siguiente error, agradecería si me pueden ayudar 

Status:      	Connecting to bases.ing.puc.cl...
Response: 	fzSftp started, protocol_version=11
Command: 	open "grupo19@bases.ing.puc.cl" 22
Error:         	ssh_init: nodename nor servname provided, or not known
Error:         	Could not connect to server
Status:      	Waiting to retry...
Status:      	Connecting to bases.ing.puc.cl...
Response: 	fzSftp started, protocol_version=11
Command: 	open "grupo19@bases.ing.puc.cl" 22
Error:         	ssh_init: nodename nor servname provided, or not known
Error:         	Could not connect to server

**Comment by Paldana99** [comment]
hola, no es bases.ing.puc.cl si no que bachman.ing.puc.cl
