### ISSUE TITLE
Problemas consultas web

### ISSUE THREAD

**Issue by Rotopikus** [IIC2413/Syllabus-2023-2#198]
Hola, para crear las consultas en la página web utilizamos el mismo código que la ayudantía, pero al momento de ejecutarlo nos sale un error en el POST. ¿A qué se puede deber? Verificamos si había un error con la base de datos y no era eso.

**Comment by Paldana99** [comment]
A primeras, es difícil indicarles. Revisen que el código php esta correcto, que los nombres de variables están bien etc...
