### ISSUE TITLE
Existencia de archivos.csv en grupoXX/Entrega2

### ISSUE THREAD

**Issue by andrius6789** [IIC2413/Syllabus-2023-2#199]
Buenas tardes, estamos teniendo problemas al poblar la base de datos teniendo los archivos.csv de forma local. Puedo subir un Archivo.sql de la forma que explica la wiki junto con los Archivos.csv en la carpeta Entrega2 para facilitar esto?

**Comment by Paldana99** [comment]
Si es lo que se espera que hagan, o simplemente solo el .csv y poblarlo mediante los comandos por consola.

**Comment by MariaJoseSilva** [comment]
Hola!
Es necesario que los .csv estén en la carpeta Entrega2? Esto no se menciona en el enunciado y nosotros usamos otra carpeta, para que en la carpeta Entrega2 esté  de forma exclusiva el PDF de la entrega. 
Gracias

**Comment by Paldana99** [comment]
no necesario, pero asi ustedes mantienen un orden igual, ya que para la proxima entregan habran nuevos csv
