### ISSUE TITLE
Número de Temporadas

### ISSUE THREAD

**Issue by josegarafulic** [IIC2413/Syllabus-2023-2#200]
Entiendo que en la tabla multimedia "número" es la temporada del capítulo. Mi pregunta es acerca de la consulta 2, que se considera como "series al menos n temporadas"?. Una serie que solo tiene en la base de datos capítulos de la 5 y 6 temporada, estaría bien asumir que tiene 2 temporadas y no 6?

**Comment by Paldana99** [comment]
Si pueden asumir que no es necesario que estén todas las temporadas en la bdd.

**Comment by Paldana99** [comment]
Anotarlo igual en el informe como suposición
