### ISSUE TITLE
Entrega 2. Servidor caido.

### ISSUE THREAD

**Issue by DTP-2B** [IIC2413/Syllabus-2023-2#205]
Estoy tratando de comprobar mis consultas para ver si funcionan, pero el servidor está fuera de servicio. ¿Qué puedo hacer? Necesito entregar esto mañana y esto está retrasando mi entrega. El error es el siguiente:

No se pudo conectar a la base de datos: PDOException: SQLSTATE[08006] [7] connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL: remaining connection slots are reserved for non-replication superuser connections in /home/grupo90/Sites/config/conexion.php:6 Stack trace: #0 /home/grupo90/Sites/config/conexion.php(6): PDO->__construct() #1 /home/grupo90/Sites/consultas/consulta_juegos_proveedores.php(8): require('...') #2 {main}

**Comment by tgellonag** [comment]
Tambien estoy teniendo este problema a ratos

**Comment by spoblete44** [comment]
Hola, tambien estoy teniendo este problema

**Comment by jorgee02** [comment]
Buenas, yo también tengo el problema y justo ahora estaba cargando las consultas ;(

**Comment by Paldana99** [comment]
Lo notifico, veremos cual es el problema

**Comment by DTP-2B** [comment]
El error se mostraba en el ssh y en el navegador

> Lo notifico, veremos cual es el problema. El error se muestra cuando hacen ssh? cuando ven el el navegador?

**Comment by Paldana99** [comment]
Acabo de revisar en el navegador en el siguiente link:
https://bachman.ing.puc.cl/~grupo90/consultas/consulta_juegos_proveedores.php
Y no logro ver el error. Pueden volver a verificar?

**Comment by Paldana99** [comment]
Viendo el error, se debió a una sobrecarga del servidor. Vuelve a estar disponible

**Comment by jorgee02** [comment]
gracias!

**Comment by VicenteNeary** [comment]
hola a mi todavía no me deja conectar al servidor desde filezilla, desde ayer que no se puede conectar.
