### ISSUE TITLE
Duda posibilidad de aplazar fecha de entrega 2

### ISSUE THREAD

**Issue by diegoherrerag2000** [IIC2413/Syllabus-2023-2#211]
Hola buenas!! espero que estén bien.

Me gustaría consultar si podría haber una posibilidad de que se aplace la entrega, puesto para mi grupo la carga académica que se tuvo posterior a la semana de receso fue más alta de lo esperado. 

Se agradece toda consideración!!.

**Comment by blampasona18** [comment]
Me sumo a la solicitud por favor! Algunos grupos mandamos a recorregir y recién estuvieron el miércoles, por lo que tuvimos solo 3 días para trabajar
Saludos de antemano y por favor considerar esto!

**Comment by Paldana99** [comment]
Hola, se aplazo la entrega para mañana sabado a las 23:59

**Comment by blampasona18** [comment]
Muchas gracias!!
