### ISSUE TITLE
Bloqueo de bases de datos

### ISSUE THREAD

**Issue by DiegoAHA** [IIC2413/Syllabus-2023-2#212]
Estaba trabajando ahora (19:30hrs) en la página con las bases de datos y de la nada se nos bloqueó el acceso y ya no podemos usar las bases de datos para revisar nuestro proyecto. Dejo esto como constancia, ya que dudo que me puedan dar una solución en los 20 minutos que me quedan.

**Comment by franancic** [comment]
Hola! podrías ser más específico con el problema? el servidor está funcionando bien

**Comment by CarlangaUC** [comment]
Hola, solo queria añadir que a nuestro grupo paso lo mismo, va y vuelve a veces.

**Comment by Paldana99** [comment]
Por favor copiar el tipo de error para poder ver el origen del problema

**Comment by franancic** [comment]
No están teniendo problemas con algún archivo especifico de la página o el archivo data de config? El miércoles durante el taller varios tenían problemas con esto, y era por esto; pero problema del servidor no es (nadie podría conectarse a la base de datos)

**Comment by CarlangaUC** [comment]
Era temporal mas que nada, a veces las consultas arrojaban ese error pero al intentar denuevo si dejaba.
