### ISSUE TITLE
Error en entrar a la base de datos desde el terminal

### ISSUE THREAD

**Issue by cgandarillas2** [IIC2413/Syllabus-2023-2#213]
Hola, estoy teniendo un error al entrar a la base de datos desde el terminal: 
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
Feliz si me podrían ayudar a solucionarlo.

**Comment by santuber** [comment]
Hola! yo desde las 19:10 que no puedo ingresar a la base de datos, ni tampoco visualizar la pagina web, creo que se cayó, espero puedan solucionarlo pronto!!
muchas gracias :)

**Comment by jlucero9** [comment]
holaa yo tambien estoy con el mismo problema :( 
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory

**Comment by santuber** [comment]
se me olvido decir que también estoy con el mismo :( 
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?

**Comment by Paldana99** [comment]
Ahí se reinicio, y esta funcionando.
