### ISSUE TITLE
Error al entrar al server

### ISSUE THREAD

**Issue by Amegonzale** [IIC2413/Syllabus-2023-2#217]
Hola,
Sucede que no me deja entrar al ssh, me tira este error:
<img width="606" alt="image" src="https://github.com/IIC2413/Syllabus-2023-2/assets/64616076/477334d8-2fab-4c77-a9f7-1c5d75e9a107">
La contraseña que ingrese es la correcta, ayuda.

**Comment by tomastrivino** [comment]
Hola. Mismo problema por acá.
<img width="682" alt="Captura de pantalla 2023-10-29 a la(s) 21 35 25" src="https://github.com/IIC2413/Syllabus-2023-2/assets/98418205/aaa22d74-3dae-4c04-abd2-9b6a15f1a481">
Se nos ha hecho complicado comenzar a trabajar porque no podemos acceder al servidor, a pesar de que no está caído (porque no es un error del tipo timeout). ¿Están cerrados mientras dure la corrección de la entrega 2?, si es así, ¿cuándo podremos trabajar? Se nos ha complicado un poco por esa parte, puesto que tenemos muchas pruebas en fechas próximas a la entrega del proyecto y, a parte de estar caído el server, hubo una cierta demora en la publicación de los datos. Porfa avisen qué se puede hacer :c

**Comment by Mateodlcc** [comment]
Hola! El acceso al servidor fue restringido momentáneamente, sin embargo se está trabajando para poder rehabilitarlo.
Esto quiere decir que hoy, a lo largo del día, el servidor volverá a estar disponible.
De momento, no habrá cambios en los plazos de entrega pero se tendrá en cuenta y se informará a los profesores.
