### ISSUE TITLE
Entrega 3: 3.3 - Suscripciones y grupos pares

### ISSUE THREAD

**Issue by hansjkl** [IIC2413/Syllabus-2023-2#218]
El enunciado describe una sección de los sitios qué debe permitir a los usuarios buscar y ver las suscripciones disponibles. Sin embargo, esto solamente describe cómo debe ser implementado para los grupos impares y no los pares. Debe implementarse algo similar con las suscripciones de videojuegos? O se debe implementar solo la de suscripciones de streaming?

**Comment by tomastrivino** [comment]
![image](https://github.com/IIC2413/Syllabus-2023-2/assets/98418205/67732527-b647-4d15-9df4-0ca1276d4b96)

**Comment by ypne** [comment]
r: si

**Comment by Amegonzale** [comment]
Si a cual de las dos?

**Comment by ypne** [comment]
ambas
