### ISSUE TITLE
grupo par Entrega 3: Constraint género

### ISSUE THREAD

**Issue by cristobalSaravia** [IIC2413/Syllabus-2023-2#219]
Hola, no me queda claro a que se refiere el constraint de la parte Genero_subgenero.
![image](https://github.com/IIC2413/Syllabus-2023-2/assets/110921243/2901f9f3-5e4b-43dc-bf15-ddc30dd00f83)

**Comment by Mateodlcc** [comment]
A lo que se refiere con esto el enunciado es a que el género debe ser diferente del subgénero.
Para ello, la notación es <> y no ><, por lo que se trata de un error de tipeo.
