### ISSUE TITLE
Diccionario grupo impar, constraint en rojo

### ISSUE THREAD

**Issue by tomas-jackson** [IIC2413/Syllabus-2023-2#220]
Hay una seccion del diccionario que me confunde un poco. Al definir los atributos de la tabla de usuarios, para el nombre se escribe UNIQUE y UNICO EN EL SISTEMA pero en color rojo. Interpreto eso como que no deberia tener esos constraints? De otro modo, si dos personas distintas llamadas Juanito Perez quisieran hacer una cuenta, esto no seria posible.

Eso, gracias c:

**Comment by Mateodlcc** [comment]
Saludos! Es parte del proyecto que sean capaces de detectar este tipo de situaciones y posibles inconsistencias. Para solucionarlo, son libres de tomar las medidas que crean correspondientes (sea tenerla en cuenta o no), debo comentarles que hay una solución bastante mejor que la otra. Cualquiera sea la decisión que tomen, deben documentarlo en el README a modo de dar a entender a los correctores la lógica detrás de sus decisiones.

Aprovecho también de racalcar la importancia que tiene el README para este tipo de proyectos ya que es, como ya mencioné, la manera formal de comunicarse con quienes corregirán sus entregas.
