### ISSUE TITLE
Problemas con la fecha de nacimiento grupo par/impar

### ISSUE THREAD

**Issue by PkAlvaro** [IIC2413/Syllabus-2023-2#221]
Buenas, quisiera escribir esta issue para informar que en los datos entregados para grupos pares e impares, en la hoja 'usuario_actividades' un mismo usuario tiene distintas fechas de nacimiento, lo que obviamente no tiene sentido, nosotros como grupo dejamos la primera fecha de cada usuario que resultaba al filtrar los datos de forma ascendente para poder avanzar con la entrega, pero queremos que quede constancia en cualquier caso.

Saludos.

**Comment by Amegonzale** [comment]
gracias compañero 🤝

**Comment by Mateodlcc** [comment]
Perfecto! La constancia debe quedar en el README tal como mencioné en #220.
