### ISSUE TITLE
Sobre la importación de datos y encriptación 😿 

### ISSUE THREAD

**Issue by tomastrivino** [IIC2413/Syllabus-2023-2#222]
Hola.
<img width="903" alt="image" src="https://github.com/IIC2413/Syllabus-2023-2/assets/98418205/209eda9a-6f49-4062-a105-f41558ca9e26">
<img width="383" alt="image" src="https://github.com/IIC2413/Syllabus-2023-2/assets/98418205/93b925f6-7b71-49bf-b5ac-eeff75cf0ff2">

# Importación de los datos
En esta parte, tengo entendido que la importación de datos, pagos y encriptación de contraseñas debe hacerse en un sólo archivo php, ¿verdad?
Noté que en el servidor no existe php-CLI, por lo que asumo que este archivo debe ser ejecutado por medio de la página (es decir, debe estar en `Sites`). Ahora bien, dada la naturaleza para la que usamos php usualmente, ¿la importación debe hacerse por medio de una "página"? ¿o basta con que sea un script, a lo python, que se ejecute apenas te metes a la página y que no retorna respuesta alguna? (o con la que no se puede interactuar). No sé si me explico, pero siento que es muy diferente meterse a `bachman.ing.puc.cl/~grupoXX/importar_datos.php` (ojo: el archivo sería público, sin contraseña ni nada) y que salgan botones con opciones, a meterse a esa página y que por detrás se ejecute el script (es decir, se muestre la página en blanco).

Además, en el caso de que fuese un script, quisiera asegurarme que fuese lo siguiente:

Al momento de ejecutar el archivo:

- Se extraen usuarios del grupo par que no están presentes en la tabla del grupo impar
- Luego, se migran esos datos al grupo impar.
- Después, se migran los pagos del grupo par al grupo impar.
- Finalmente, una vez hecho lo anterior, se encriptan todas las contraseñas de la tabla de usuarios del grupo impar, que ahora incluye los usuarios que extrajimos de la del grupo par en el primer paso.

¿Es así? Agradecería cualquier aclaración que nos pueda orientar sobre cómo llevar a cabo este procedimiento.

# Encriptación
Desde php8, se exige que se ocupe una "llave" como argumento a `crypt()`. ¿Esta puede ser inventada por nosotros?
Adicionalmente, quería consultar si es adecuado asumir que se ejecutará el archivo de importación na única vez, puesto que, acorde a los pasos que explicité anteriormente, se encriptarían todas las contraseñas de todos los usuarios. Ejecutar este paso más de una vez provocaría que, en un segundo intento, se encripten contraseñas que ya fueron encriptadas anteriormente (se encripten hashes), y por ende después no funcionaría la verificación de contraseñas al momento del login. Adjunto foto de un ejemplo.
<img width="623" alt="image" src="https://github.com/IIC2413/Syllabus-2023-2/assets/98418205/860d1c99-137e-4947-ba86-b24249a65015">

¡Muchas gracias! :D

**Comment by hansjkl** [comment]
Tal vez se puede encriptar las contraseñas en ambos servers previo a transferir los usuarios? Así se evita el problema del encriptado doble

**Comment by ypne** [comment]
Estimados
vamos por partes 
- datos, pagos y encriptación de contraseñas debe hacerse en un sólo archivo php, ¿verdad?
- R: no es necesario, los cargadores se pueden hacer via CLI desde la shell. La encriptación la pueden hacer antes separado del cargador. Lo importante es que se haga y sea Reproducible

**Comment by tomastrivino** [comment]
@ypne Respecto a usar shell, a qué te refieres exactamente? a crear un archivo `.sh`. que haga esto (cosa que no vimos en el curso si no me equivoco)?
Porfa aclárame esa parte c:

Gracias.

**Comment by tomastrivino** [comment]
Hola.
En verdad sí hay PHP-CLI, sólo que no se ejecuta con `php-cli` sino que con `php`. My bad. No hay que responder nada más entonces. Todo okay, muchas gracias!

**Comment by ypne** [comment]
ok cerrado enntonces
