### ISSUE TITLE
Procesamiento para carga de datos

### ISSUE THREAD

**Issue by carlosiskindacool** [IIC2413/Syllabus-2023-2#223]
Hola,
con respecto al enunciado en el apartado 3.2, no me queda claro a qué se refiere con 'modificar los scripts de carga'. En particular, debemos subir el procedimiento de procesamiento de datos desde los archivos xlsx o simplemente se refiere a los scripts de carga desde archivos ya procesados?

**Comment by ypne** [comment]
P: modificar los scripts de carga'
R:Se refiere a que si hicieron scripts de carga en la E2, deben modificarlos, sino deben construirlos
P: debemos subir el procedimiento de procesamiento de datos desde los archivos xlsx o simplemente se refiere a los scripts de carga desde archivos ya procesados?
R: Pueden subirlos directo de los xlsx o bajar cada Tab a texto (CSV) y cargarlos desde ahí. No deben procesar los archivos a mano (para normalizarlos) y luego subirlos, esta es tarea de los cargadores.

**Comment by carlosiskindacool** [comment]
el script debe ser un archivo php o hay libertad para el formato de los cargadores?
