### ISSUE TITLE
[Proyecto - parte 3] Duda sobre esquema relacional entre parejas de un mismo grupo.

### ISSUE THREAD

**Issue by ibgarrido** [IIC2413/Syllabus-2023-2#224]
1. Para ambas parejas que componen el grupo, cada una debe usar un esquema relacional distinto de la otra pareja?

**Comment by antoniablanco** [comment]
Hola, para esta entrega ambas parejas deben ocupar el mismo esquema realcional. Que contenga una integración de ambas bases de datos.

**Comment by ypne** [comment]
3.  Requerimientos
Su aplicación deberá integrar la base de datos de la plataforma de meta streaming con la meta tienda de videojuegos. Para ello se deben manejar cada una en forma independiente en el servidor respectivo de modo mantener dos conexiones abiertas.
No se permite migrar el esquema a la base de datos de uno de los grupos excepto que se indique expresamente
