### ISSUE TITLE
Error en formato de datos para tildes (´)

### ISSUE THREAD

**Issue by franfonte** [IIC2413/Syllabus-2023-2#226]
Hola, en el grupo impar todos los tildes y las ñ aparecen erróneamente, por ejemplo √≥, √∫, etc. ¿Seria posible que resuman los datos con el formato de texto correcto?

**Comment by ypne** [comment]
La "Sanitización" de input es parte del problema, lo deen manejar los cargadores y dejar documentado en el Readme

**Comment by franfonte** [comment]
Y podemos sanitizar los datos antes de cargarlos a las bases de datos y a la pagina web? por ejemplo arreglarlos en excel y subirlos sanitizados a la base de datos
