### ISSUE TITLE
duda de carga de datos entrega 3

### ISSUE THREAD

**Issue by diegoherrerag2000** [IIC2413/Syllabus-2023-2#228]
Hola!! espero que estén bien, tengo una duda sobre el ítem de la carga de datos de la entrega 3, ¿a modo general a que se refieren con la carga de datos, específicamente a lo de modificar los scripts de carga de datos?.

Gracias!!

**Comment by ypne** [comment]
Deben generar scripts para cargar los datos desde los archivos excel entregados (o convertir en CSV) e insertarlos directamente en las tablas del Schema generado a partir del modelo E/R.
 Los cargadores deben ser reejecutables ya que se probarán en la corrección. 
No se permite cargar las tablas directamente y luego manipularlas manualmente en la  base de datos para llegar al Schema.
