### ISSUE TITLE
proyecto 3 tablas y datos

### ISSUE THREAD

**Issue by adribastiasm** [IIC2413/Syllabus-2023-2#229]
Hola! En el enunciado sale que tenemos habilitada una base de datos en grupoxxe3 con las tablas y los datos, sin embargo, nuestra base de datos esta vacía (pusimos el menor grupo). Por si podrían explicar que sucede.

**Comment by SantiagoDLCB** [comment]
Lo mismo ocurre con nosotros. Como se soluciona?

**Comment by franancic** [comment]
Deben crear las tablas en cada grupo y poblarla con los [datos](https://github.com/IIC2413/Syllabus-2023-2/tree/main/Proyecto/Entrega3/Datos) que se entregaron junto al enunciado de la [E3](https://github.com/IIC2413/Syllabus-2023-2/tree/main/Proyecto/Entrega3). 
Luego, deben conectar ambas bases de datos (no dejar todo en 1 misma base de datos) para la página

**Comment by franancic** [comment]
Copio del enunciado: 
3. Requerimientos
Su aplicación deberá integrar la base de datos de la plataforma de meta streaming con la meta
tienda de videojuegos. Para ello **se deben manejar cada una en forma independiente en el servidor**
respectivo de modo **mantener dos conexiones abiertas.**
No se permite migrar el esquema a la base de datos de uno de los grupos excepto que se
indique expresamente
