### ISSUE TITLE
Duda Pregunta 6

### ISSUE THREAD

**Issue by Nicolas413** [IIC2413/Syllabus-2023-2#23]
"Liste todos los nombres de los autores que no son autores de ning´un libro." tengo una duda con respecto a la pregunta, en si a la tabla Libros y el autor del libro, ¿los autores de los libros se encuentran en Pub_Autor?, si eso es así, entonces puedo asumir que todos los libros han sido publicados, para poder obtener referencias a los autores?, o es otro tipo de relacion la que se plantea en las tablas Libro, Publicacion y Pub_Autor.

Y otra duda el titulo que aprece en Publicacion es algo asi como el titulo del libro para el publico, o es aparte del Libro ese titulo, o representa a alguna editorial?

**Comment by ConstanzaBaeza** [comment]
Tengo la misma duda, como sabemos cuales no son autores, si solo se nos presenta informacion de autores

**Comment by RICARDOOVIEDO** [comment]
Por si no vieron el anuncio, los profesores decidieron eliminar esa pregunta del control! Saludos
