### ISSUE TITLE
Hoja de Pagos Grupo Par

### ISSUE THREAD

**Issue by Gcamposbriceno** [IIC2413/Syllabus-2023-2#230]
En el diccionario de datos se especifica que el id_proveedor en la hoja de pagos es not null, sin embargo, en el excel que se nos pasó la columna id_proveedor es nula para todos los juegos de suscripción. Este problema ya pasó en la entrega anterior.

**Comment by antoniablanco** [comment]
Hola, todas aquellas inconsistencias que encuentren deben ser a través de los cargadores, según las estrategias explicadas en el enunciado, y deben ser documentado en su read.me. 
Saludos!
