### ISSUE TITLE
Datos excel impar

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#231]
Hola! El enunciado dice que se nos va a entregar las tablas en formato csv, pero se nos entrega en excel. Además creo que hay un problema con estos archivos porque por ejemplo la hoja 'genero' tiene mal guardados lo nombres de los generos por lo tildes. Por ejemplo 'Ciencia ficción'  aparece como 'Ciencia ficci√≥n'

**Comment by antoniablanco** [comment]
Hola, dentro de excel pueden exportar las tablas como csv o trabajar con ellas en .xlsx. 
Sobre los tildes, es parte de la limpieza que se espera realicen y documenten en el read me.

**Comment by SantiagoDLCB** [comment]
Gracias! Y en ese caso la limpieza la debemos hacer en el script de procedimiento de carga mismo o puede ser manual?

**Comment by ypne** [comment]
P:  El enunciado dice que se nos va a entregar las tablas en formato csv, pero se nos entrega en excel.
R: Pueden usar los Excel directos o exportar a CSV

P:Además creo que hay un problema con estos archivos porque por ejemplo la hoja 'genero' tiene mal guardados lo nombres de los generos por lo tildes
R: Deben realizar la Sanitización o higiene de datos, no solo de entrada desde los archivos sino que desde cualquier input

P: Sobre los tildes, es parte de la limpieza que se espera realicen y documenten en el read me.
R: Si

P: Y en ese caso la limpieza la debemos hacer en el script de procedimiento de carga mismo o puede ser manual?
R: Ambas formas son válidas, puede ser que en el caso de las tildes sea mejor hacerlo interno en el sistema ya que eso permite reutilizar la función en la sanitización de los input desde la misma aplicación. En el caso de las fechas de nacimiento es más claro que es mejor hacerlo en el INSERT ya que si el username existe, se descarta el dato.
