### ISSUE TITLE
Procedimiento de carga y datos nuevos 

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#232]
Hola! No termino de entender a que se refieren con procedimiento de carga. 

Debemos incluir los script que usamos para crear la base de datos completa con los archivos csv? O son solo los scripts de carga de datos que son ingresados por un usuario.

En caso de que se deba incluir los scripts de carga de la base de datos, ya no se puede ocupar DataGrip entonces?

**Comment by ypne** [comment]
P: Debemos incluir los script que usamos para crear la base de datos completa con los archivos csv?ee
R: Deben generar scripts de carga. La carga debe ser automatizada por estos scripts.

P: ya no se puede ocupar DataGrip entonces?
R: Para cargar no. Se puede usar como herramienta auxiliar para verificar CONSTRAIN pero no se ocupa en esta entrega

**Comment by SantiagoDLCB** [comment]
Pero en ese caso cada vez que se abra la pagina se debe crear la base de datos entera?  O deben estar ahi para revision no más
