### ISSUE TITLE
Script de carga y lenguaje de programacion

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#233]
El script de carga puede estar hecho en otro lenguaje para procesar los datos y despues subirlos con sql o tiene que tener extension.sql . Si es asi, este lenguaje puede ser python?

**Comment by Paldana99** [comment]
Como se indica en en Readme de la E3, se debe de realizar con PHP.

**Comment by ypne** [comment]
pasado 3 dias de la respuesta se cierra el issue
