### ISSUE TITLE
Fecha_nacimiento datos grupo par.

### ISSUE THREAD

**Issue by CValenzuela2** [IIC2413/Syllabus-2023-2#234]
Hola, en el archivo "usuarios_actividades" hay disitintas fechas de nacimiento asociadas al mismo usuario en los datos otorgados al grupo par. Esto se debe a que si un usuario hace más de una reseña, el atributo fecha_nacimiento es distinto de la fecha_nacimiento de la reseña anterior. Para los grupos impares no existe este problema porque no tienen reseñas.

Por lo tanto, para mantener la congruencia de los datos entre ambos grupos, ¿Podríamos eliminar el atributo "fecha_nacimiento" para los usuarios? Y de no ser posible esa solución, cómo se podría arreglar el problema?

Saludos, y gracias de antemano

**Comment by Paldana99** [comment]
Hola, se discutió sobre el tema en #221 #220

**Comment by CValenzuela2** [comment]
Perfecto, muchas gracias

**Comment by ypne** [comment]
P: ¿Podríamos eliminar el atributo "fecha_nacimiento" para los usuarios?
R: Este dato se usa en consultas, no se puede eliminar. No se debe eliminar ningún atributo definido en el diccionario de datos.
