### ISSUE TITLE
Porveedores de subscripciones (datos par)

### ISSUE THREAD

**Issue by martineyz** [IIC2413/Syllabus-2023-2#235]
Hola, todas aquellas inconsistencias que encuentren deben ser a través de los cargadores, según las estrategias explicadas en el enunciado, y deben ser documentado en su read.me. 
Saludos!

_Originally posted by @antoniablanco in https://github.com/IIC2413/Syllabus-2023-2/issues/230#issuecomment-1803845468_

El problema es que todos los juegos de subscripcion carencen del dato id_proveedor, entonces si eliminamos esos datos, no habría ningun pago de subscripcion.

**Comment by ypne** [comment]
P: El problema es que todos los juegos de subscripcion carencen del dato id_proveedor
R: De suscripción extraigan el ID del juego y de Proveedores pueden sacar el proveedor

**Comment by martineyz** [comment]
> P: El problema es que todos los juegos de subscripcion carencen del dato id_proveedor R: De suscripción extraigan el ID del juego y de Proveedores pueden sacar el proveedor

Pero hay más de un proveedor por juego de subscripcion. Como se elige.
