### ISSUE TITLE
Datos Entrega 3

### ISSUE THREAD

**Issue by LucasReds** [IIC2413/Syllabus-2023-2#236]
Para la entrega 3, nuevamente hay que modificar los archivos y subirlos según nuestro esquema a la bdd, o podemos seguir usando los que ya subimos para la entrega 2?

**Comment by antoniablanco** [comment]
Hola, es necesario que vuelvan a modificar los archivos pero esta vez cada cambio debe ser explicado como se solucionó en el read me. Y es necesario que los errores los encuentren con los script de carga, explicando que estrategia realizaron (según las que están en el enunciado)

**Comment by ypne** [comment]
P: Para la entrega 3, nuevamente hay que modificar los archivos y subirlos según nuestro esquema a la bdd, o podemos seguir usando los que ya subimos para la entrega 2?
R: NO hay que modificar los archivos de carga, se deben implementar los cargadores automáticos. Si hay errores que implique cambios en los datos se debe documentar en el readme. 
La corrección es posterior a la carga.

**Comment by ypne** [comment]
pasado 2 dias de la respuesta se cierra el issue
