### ISSUE TITLE
Proveedores suscripcion grupo par

### ISSUE THREAD

**Issue by Vicentapd** [IIC2413/Syllabus-2023-2#237]
Ya se ha hablado en varias ocasiones pero sigue sin parecerme claro,

En las tablas se puede llegar sencillamente a los proveedores de los juegos de pago único, sin embargo para los de suscripcion se tiene en la tabla de suscripcion donde no se relaciona a un proveedor. En una solución dijeron "De suscripción extraigan el ID del juego y de Proveedores pueden sacar el proveedor", el problema ahí es que no hay solo un proveedor que ofrezca los juegos de suscripcion, y por otro lado en la tabla usuario_proveedor existen casos donde el usuario tiene asociado dos proveedores que proveen el mismo juego, por tanto esta tabla tampoco es util para solucionar el problema.

Es posible forzar que las suscripciones tengan un solo proveedor y no tomar en cuenta la tabla usuario_proveedor, así asociar todas las suscripciones de los juegos al proveedor que se deje?

**Comment by ypne** [comment]
P: Es posible forzar que las suscripciones tengan un solo proveedor y no tomar en cuenta la tabla usuario_proveedor, así asociar todas las suscripciones de los juegos al proveedor que se deje?
R: Si tienen otra solución mejor que esta pueden hacerla y documentarla en el Readme. No es necesario forzar  (CONSTRAIN) las suscripciones a un solo proveedor. Si y solo si al Normalizar esa tabla es redundante se eliminará sola.
