### ISSUE TITLE
Correspondenica porveedor-suscripcion

### ISSUE THREAD

**Issue by martineyz** [IIC2413/Syllabus-2023-2#239]
P: El problema es que todos los juegos de subscripcion carencen del dato id_proveedor
R: De suscripción extraigan el ID del juego y de Proveedores pueden sacar el proveedor

_Originally posted by @ypne in https://github.com/IIC2413/Syllabus-2023-2/issues/235#issuecomment-1804342262_
        
Entiendo que se puede obtener la ID de juego pero es imposible obtener el proveedor a partir de ella ya que hay multiples proveedores para el mismo juego de subscripcion. La tabla usuario_proveedor tampoco reduce a 1 las opciones. Se que ya hay varias issues respecto a esto pero no encuentro ninguna respuesta que clarifique el tema y como todas están cerrdadas me veo obigado a crear una nueva. Gracias de antemando.

Pd: Se agradecería que no se cerraran las issues inmediatemente despues de dar una respuesta ya que no da la oportuindad de terminar de aclarar las dudas.

**Comment by ypne** [comment]
R: Así es, la respuesta entregada es una opción para suplir esta deficiencia asignando un proveedor al video juego. Dejaré esta issue abierta

**Comment by martineyz** [comment]
> R: Así es, la respuesta entregada es una opción para suplir esta deficiencia asignando un proveedor al video juego. Dejaré esta issue abierta

A cual respuesta te refieres?

**Comment by ypne** [comment]
R: a las respuestas de los comentarios anteriores en el issue

**Comment by martineyz** [comment]
> R: a las respuestas de los comentarios anteriores en el issue

Pero cual es esa respuesta? El problema es que hay más de una opcion para proveedor por cada suscripcion. Mi duda es como se elige cual. Lo hacemos de forma aleatoria?

**Comment by ypne** [comment]
R: Elije uno que lo provea
