### ISSUE TITLE
Duda sobre las propuestas de transacciones en el enunciado

### ISSUE THREAD

**Issue by martineyz** [IIC2413/Syllabus-2023-2#240]
![image](https://github.com/IIC2413/Syllabus-2023-2/assets/127438338/2dadbac0-0e12-4350-accc-f7edc9df77e2)
Respecto a esta parte de el enunciado me surgen 2 dudas.:

Primero respecto a la alternativa a), cuando dice "corregir el dato y volver a cargar completa", ¿Se refiere a que el script tiene que corregir automaticamente cualuier problema con los datos que se encuentre y seguir tratando de hace la transaccion hasta que no haya errores? ¿Simplemente que pare la transaccion y manulamente corregir el error informado? se agradecería una aclaracion al respecto.

Respecto a la alternativa c), ¿a que se refiere con "cargar los registros"?

gracias de antemano.

**Comment by ypne** [comment]
P: ¿Se refiere a que el script tiene que corregir automaticamente cualuier problema con los datos que se encuentre y seguir tratando de hace la transaccion hasta que no haya errores? ¿Simplemente que pare la transaccion y manulamente corregir el error informado?
R: Si el script corrigiera el dato automáticamente no sería necesario detenerse. La idea de la alternativa a) es que se detiene el cargador al primer error, se corrige manualmente el dato o la condición que lo produjo, se borra todo lo cargado y se ejecuta de nuevo.

P: ¿a que se refiere con "cargar los registros"?
R: se procesa la tabla entera dejando un registro de los errores, luego se corrigen todos y sin borrar los datos cargados anteriormente se corre el script con los datos previamente erróneos.
Nota: la corrección se deerá hacer manualmente en la condición que produjo el error y eso no es necesariamente el dato.
