### ISSUE TITLE
Pregunta sobre cargadores de datos

### ISSUE THREAD

**Issue by rmezaa** [IIC2413/Syllabus-2023-2#241]
Hola, todavía no logramos comprender bien en como actúan los cargadores de datos. ¿Son los encargados de leer los datos csv, adecuarlos a nuestros esquemas, y asegurarse de que los datos cumplan los constraints de las tablas? ¿O cómo? Porque en el inciso 3.2 dice que en importación de usuarios hay que crear un cargador en php que extraiga los usuarios de la base de datos, ¿a qué se refiere con extraerlos de la base de datos y hacia donde los mueve?

**Comment by ypne** [comment]
P: los cargadores de datos. ¿Son los encargados de leer los datos csv, adecuarlos a nuestros esquemas, y asegurarse de que los datos cumplan los constraints de las tablas?

R: Los cargadores son los encargados de polar las talas asociadas al Schema de cada ase de datos Par e Impar. El encargado de verificar los Constrain es el DBMS. Los cargadores solo deben tomar cada linea del CSV, realizar el INSERT de los atributos en las tablas de la Base normalizada que ustedes construyan para ambos grupos

P: ¿a qué se refiere con extraerlos de la base de datos y hacia donde los mueve?
R: El enunciado en 3.2 se refiere exclusivamente a que la carga de los usuarios y pagos del grupo PAR en las tablas del grupo IMPAR. Pueden hacerlo directo del CSV si es que no han cargado los datos del grupo impar o, si ya los cargaron extraerlos de la ase IMPAR y cargarlo en la PAR.
