### ISSUE TITLE
Minimo de stored Procedures y triggers

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#242]
Hola! Tengo una duda respecto a la pauta de evaluación de los temas de stored procedures y triggers. Hay muchas cosas que se pueden hacer tanto con stored procedures y triggers, como directamente en php. En ese sentido existe algún mínimo de stored procedures a implementar o algo en particular que deba hacer si o si con stored procedures y triggers?

**Comment by ypne** [comment]
P: existe algún mínimo de stored procedures a implementar o algo en particular que deba hacer si o si con stored procedures y triggers?
R: Si, En el enunciado aparece lo que se debe implementar con Triggers y Stored Procedures
