### ISSUE TITLE
Duda calsificacion videojuegos

### ISSUE THREAD

**Issue by martineyz** [IIC2413/Syllabus-2023-2#243]
En el diccionario de datos se especificica que las caslficaciones pueden ser  ESRB o PEGI:
![image](https://github.com/IIC2413/Syllabus-2023-2/assets/127438338/c34c8bf4-76af-4253-b36d-945e2fecaa6a)

Sin embargo en los datos en sí, ningun juego tiene esas clasificaciones.

**Comment by ypne** [comment]
R: Los ESRB si la tienen M, T, E10, etc. Los PEGI estan escritos en palabras en lugar de números, pueden transformarlos o dejarlos así. Lo importante es que haya una Tabla de clasificación con los valores
