### ISSUE TITLE
Duda usario_actividades datos grupo par

### ISSUE THREAD

**Issue by martineyz** [IIC2413/Syllabus-2023-2#244]
![image](https://github.com/IIC2413/Syllabus-2023-2/assets/127438338/b7a29136-7a48-421c-a03b-ee3ca2a54ae3)
En el diccionario de datos hay una fecha que dice ser la fecha de visualización, pero no entiendo a que se refiere con visualización en el contexto de lo videojuegos. Gracias.

**Comment by ypne** [comment]
P: a que se refiere con visualización en el contexto de lo videojuegos
R: Fecha que se ejecutó el video juego

**Comment by martineyz** [comment]
@ypne 

Que se ejectó por ultima o por primera vez?

Respecto a este mismo dato, me di cuenta que nisiquiera existe en los datos que nos entregaron.

**Comment by ypne** [comment]
R: me das un ejemplo?

**Comment by martineyz** [comment]
> R: me das un ejemplo?

![image](https://github.com/IIC2413/Syllabus-2023-2/assets/127438338/1993e888-2ce9-48e6-a27d-09d9553f364f)

No hay nigun dato llamado fecha

**Comment by ypne** [comment]
R: Toda la razón, falta esa columna lo corregiré

**Comment by ypne** [comment]
corregido
