### ISSUE TITLE
Duda fecha_inicio subscripciones (grupo par)

### ISSUE THREAD

**Issue by martineyz** [IIC2413/Syllabus-2023-2#245]
![image](https://github.com/IIC2413/Syllabus-2023-2/assets/127438338/c6b06ae2-e086-43bb-8050-e7c3cb234667)
A que se refiere con que la fecha sea >= 1 mes?

**Comment by ypne** [comment]
P:  >= 1 mes
R: Está poco claro (fecha fin - fecha inicio)  >=1 mes corregiré el enunciado. Muchas gracias
