### ISSUE TITLE
Duda correccion de datos

### ISSUE THREAD

**Issue by martineyz** [IIC2413/Syllabus-2023-2#246]
![image](https://github.com/IIC2413/Syllabus-2023-2/assets/127438338/af27a3c7-258f-49c7-b264-053ab5c0d83a)
Cuando dice "corregir el dato", ¿se refiere a cambiarlo en el csv o se pude cambiar el script de carga para que altere/ingore ese dato (o grupo de datos)?

**Comment by ypne** [comment]
P: ¿se refiere a cambiarlo en el csv o se pude cambiar el script de carga para que altere/ingore ese dato (o grupo de datos)?
R: Ambas alternativas son válidas, el cambio en el script se puede hacer previo por lo tanto (por ejemplo corregir acentos) se puede capturar en el script y evitar que se detenga ante ese error
