### ISSUE TITLE
Duda parte item 3.5 y 36

### ISSUE THREAD

**Issue by martineyz** [IIC2413/Syllabus-2023-2#247]
![image](https://github.com/IIC2413/Syllabus-2023-2/assets/127438338/95202ec2-5abf-4702-91be-4a328ef1d191)

3.5: 

1) No me queda muy claro que debe mostrarse el pagina. Se me ocurren 2 alternarivas: 
1- 3 entrdas de texto, 1 para el nombre de tabla, 1 para los atributos y una para las condiciones.
2- una entrada de texto para una consulta entera.
Si esque se refiere a otra cosa se agradecería una aclaración.

2) Respecto al mismo item, ¿a que se refieren con incluir las validacioens necesarias?

3.6:

¿A que se refieren con "Una subscripción puede estar cancelada pero seguir estando activa hasta la fecha de finalización"?

**Comment by ypne** [comment]
Muy buena la pregunta
P: Se me ocurren 2 alternarivas
R: La alternativa es la 1, pero si quieren hacer la 2 puede también puede ser.

P: a que se refieren con incluir las validacioens necesarias?
R: Sanitización o Higienización  del input. Está en la materia de clases

P: ¿A que se refieren con "Una subscripción puede estar cancelada pero seguir estando activa hasta la fecha de finalización"?
R: Cuando se pagan suscripciones, se hace en general mes adelantado pero puedes cancelarla en cualquier momento, eso significa que a pesar de estar cancelada, se puede tener el servicio hasta el fin de mes

**Comment by martineyz** [comment]
Respecto a esta pagina, ¿como se supone que el usuario sepa los tombres de tablas y atributos que existen?

**Comment by ypne** [comment]
R: Puedes asumir que los usuarios saen los nomres de las talas y atriutos ya que la consulta inestructurada es para usuarios avanzados que conocen el schema
