### ISSUE TITLE
Petición enunciado E3

### ISSUE THREAD

**Issue by santuber** [IIC2413/Syllabus-2023-2#248]
Hola! podrían subir bien el enunciado por favor?, aparece con las correcciones y no se entiende bien :)
Gracias!!!!

**Comment by panchouc** [comment]
Me sumo a la petición de mi compañero

**Comment by Tamarindinho** [comment]
x3

**Comment by SantiagoDLCB** [comment]
x4

**Comment by ypne** [comment]
R: Solicité a la ayudante que sua una nueva versión, en todo caso los issues mas importantes los he ido agregando en el readme que tamién está suido
