### ISSUE TITLE
Página ayudantía 4

### ISSUE THREAD

**Issue by yjuniorr** [IIC2413/Syllabus-2023-2#249]
Hola, será posible que envíen un link para ver el funcionamiento de la página de la ayudantía 4 sin tener que subir todo a mi servidor? 
gracias de antemano!

**Comment by RubenMarambio** [comment]
Hola, la página que usaron en la ayudantía 4 es https://bachman.ing.puc.cl/~grupo137/

**Comment by yjuniorr** [comment]
Gracias!
