### ISSUE TITLE
Scheduling del chequeo de suscripciones y actualizacion de vistas.

### ISSUE THREAD

**Issue by tomas-jackson** [IIC2413/Syllabus-2023-2#250]
Intentando implementar las funcionalidades mencionadas en el titulo de la issue descubrí que cron y por ende, crontab, estan desactivados en el servidor. Por mas que investigué, no encontre otra forma de automatizar el proceso de refresh. Me imagino que la idea no es manualmente correr el codigo cada noche, por esto pregunto si existe otra alternativa, o si existe la posibilidad de activar la funcionalidad de cron. O a lo mejor solo necesito buscar un poco mas.

De todos modos, espero su respuesta :)

Adjunto imagen de terminal
<img width="396" alt="image" src="https://github.com/IIC2413/Syllabus-2023-2/assets/127408636/beea1373-f1f2-44ca-87e3-f89d13db52da">

**Comment by ypne** [comment]
R: aunque no es esrictamente necesario usar cron, solicitaré que se les active

**Comment by SantiagoDLCB** [comment]
Hola! Podrian informar cuando se active?

**Comment by SantiagoDLCB** [comment]
Tengo otra duda al respecto, cual es el path del archivo cron ya que para inicializar una tarea cron es necesario darle un path al archivo

**Comment by ypne** [comment]
R: man cron
