### ISSUE TITLE
Sobre el diccionario Tabla Visualizaciones

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#252]
Hola! Tengo una duda respecto a lo que se entrega en el diccionario de grupo impar:
> Visualizaciones
> uid:INT NN Id de usuario CONSTRAIN debe existir en la BD
> pid, INT Id de película CONSTRAIN debe existir en la BD
> sid: INT id de la serie, CONSTRAIN debe existir en la BD
> cid: INT Número de capítulo de la serie CONSTRAIN el par sid-cid debe existir en la
> BD
> fecha: DATE NN fecha de la visualización CONSTRAIN (fecha <= fecha actual) y
> ((suscripciones.fecha_inicio <=fecha <=suscripciones<=fecha_termino) o (pagos.fecha <=
> fecha))

Cuando dice pagos.fecha <= fecha se refiere a si pago la pelicula como un adicional o si renovo su subscripcion con el proveedor

**Comment by ypne** [comment]
P: Cuando dice pagos.fecha <= fecha se refiere a si pago la pelicula como un adicional o si renovo su subscripcion con el proveedor
R: Tomando la restricción completa 
1.- fecha <= fecha actual.  Quiere decir que la fecha de visualización tiene que ser anterior o igual a la actual
2.- suscripciones.fecha_inicio <=fecha <=suscripciones.fecha_termino indica que la visualización dee estar en el rango de la suscripción
3.- pagos.fecha <= fecha aplica para las compras

**Comment by SantiagoDLCB** [comment]
Gracias! Solo para ver que me quedo claro, por compras, se refiere a pagar por peliculas fuera de un plan de susbscripcion

**Comment by ypne** [comment]
R: correcto
