### ISSUE TITLE
Sobre el manejo de errores - Entrega 3

### ISSUE THREAD

**Issue by K-hil** [IIC2413/Syllabus-2023-2#253]
Hola, tenemos una duda en el enunciado sobre la carga la de datos. Entendemos que los cargadores deben captar los errores y una opción es detener la transacción, corregir y volver a subir. Eso significa que el procedimiento sería algo así?:

1. correr cargador
2. en caso de detectar error terminar transaccion y alertar 
3. corregir error ya sea con codigo o manualmente
4. correr cargador nuevamente

Es este el procedimiento o se espera que la corrección de datos también se haga en el cargador?
Otra duda, los cargadores deben activarse cada vez que se abra la pagina o solo debemos incluirlos en Sites y correrlos manualmente cuando sea necesario por medio del shell?

**Comment by ypne** [comment]
P:  Eso significa que el procedimiento sería algo así?: .....
R: El que detecta los errores es en general (hay excepciones) el DBMS evaluando CONSTRAIN y hay 3 estrategias: 1.- detenerse al primer error, borrar la tabla corregir el error y volver a cargar toda la tabla 2.- detenerse al primer error corregir y seguir subiendo datos desde el punto de detención, sin borrar los anteriores y 3.- registrar todos los errores y una vez terminado de subir la tabla corregir y suir solo los datos corregidos, sin borrar los anteriores.
