### ISSUE TITLE
Duda sobre los usuarios y registro

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#254]
Hola! En el diccionario del enunciado se menciona que tanto el nombre de un usuario como su username deben ser unicos en la base de datos. Pero en la seccion de registrar un usuario solo se menciona que se debe checkear que el username sea unico y no se dice nada al respecto del nombre. Que se debe hacer realmente con el nombre? Porque tampoco tiene mucho sentido lo que aparece en el diccionario, ya que perfectamente pueden haber dos personas distintas con el mismo nombre que quieran usar la plataforma y de hecho existe ese caso en las tablas entregadas, realmente haria mas sentido que no puedan haber dos usuarios con el mismo mail pero eso si se permite por algun motivo.

Tambien no termino de entender la parte de los permisos de los usuarios. 

> Se deben asignar los permisos que correspondan (read, write, update, etc.) según
> corresponda, tanto a las tablas como al sistema operativo de modo de poder realizar todas
> las acciones

En ninguna parte de los archivos entregados se nos dice que permisos tienen los usuarios ya existentes, pero debemos agregarle permisos a usuarios nuevos. Tampoco entiendo cual es el criterio "segun corresponda" para asignar dichos permisos

**Comment by ypne** [comment]
P:  Que se debe hacer realmente con el nombre?
R: Ustedes deciden, podrían eliminar la restricción Unique pero deen documentarlo en el readme
P: Tampoco entiendo cual es el criterio "segun corresponda" para asignar dichos permisos
W: En las talas donde se lee, el privilegio es read y donde se escribe es read write o update

**Comment by SantiagoDLCB** [comment]
Pero en ese caso todos los usuarios tendrian los mismos permisos para cada tabla o no?

**Comment by ypne** [comment]
si

**Comment by SantiagoDLCB** [comment]
Cual es el path relativo del cron cuando queremos añadir una tarea que implique correr un archivo? El path es relativo a el documento php que realiza un exec para llamar a cron o es relativo a otra carpeta?
