### ISSUE TITLE
Duda sobre el manejo de errores.

### ISSUE THREAD

**Issue by carlosiskindacool** [IIC2413/Syllabus-2023-2#255]
Hola, con respecto al apartado 3.2, en relación al script de carga, en particular en relación al manejo de errores, según entiendo se deben subir los datos a la BDD utilizando archivos CSV mediante las querys y dependiendo del tipo de error presente tomar alguna de las tres opciones presentes en ese apartado (3.2) del enunciado. Es correcto esto? O debe elegirse una de las tres opciones para abordar cualquier error presente durante la carga de los datos a los modelos?
Esto lo pregunto ya que en el caso particular de, por ejemplo, cargar una Reseña que no tiene id_usuario, en teoría, podría (o no) recuperarse este dato faltante ya sea consultando otros modelos o otorgando algún input.

**Comment by ypne** [comment]
P: subir los datos a la BDD utilizando archivos CSV mediante las querys 
R: Así es, subir mediante un script+ queries desde los csv

P: Cargar una Reseña que no tiene id_usuario, en teoría, podría (o no) recuperarse este dato faltante 
R: Correcto si falta un dato pero este se puede recuperar de otra tabla (n o modelo) se hace, sino toman otra acción como eliminar el dato de origen. Todo documentado en el readme.

**Comment by carlosiskindacool** [comment]
entiendo. entonces puedo asumir que efectivamente hay que ir abordando cada error con alguna de las tres opciones del enunciado según sea el tipo de error? 
y con respecto a lo del ejemplo del dato faltante en Resenas, en teoría puede resolverse para los archivos CSV dados, sin embargo entiendo que los scripts de carga deben ser generales para cualquier subida de datos a la base de dato, no? no implicaría abordar este tipo de error de subida de esta forma hardcoding?
a lo que voy es que, suponiendo que puedo obtener un dato faltante de otra manera, debo asumir que esta manera es consultando alguno de los archivos CSV dados para esta entrega?

**Comment by ypne** [comment]
R: La idea es que nada esté hard coded. Si el dato no lo encuentras en otra relación define una estrategia de solución, no los cargas  o asumes la relación que te falta. Todo documementado en la entrega
