### ISSUE TITLE
Base de Datos grupoXXe3 vacía

### ISSUE THREAD

**Issue by CrisDonosoMaass** [IIC2413/Syllabus-2023-2#258]
Hola, estaba leyendo el enunciado y me llamó la atención que se menciona esto:
![Captura de pantalla 2023-11-12 205657](https://github.com/IIC2413/Syllabus-2023-2/assets/106105065/9b48c3d4-026a-4803-9dc2-a14c522c37f8)

Pero al momento de ver la base de datos en PSQL esta está vacía,
![Captura de pantalla 2023-11-12 210243](https://github.com/IIC2413/Syllabus-2023-2/assets/106105065/dd3a768e-b252-4173-b03a-d0001b6be34c)

Agradecería si aclararan esta información ya que no sé si es un error de nuestra BDD o algo más.

**Comment by ypne** [comment]
R: Ustedes deen crear el modelo E/R, Schema y tablas para el proyecto y luego cargarlas

**Comment by josegarafulic** [comment]
Pero no me queda claro @ypne , hay que crear todas las tablas de nuevo en la base de datos de grupoXX3 para posteriormente poblarlas?
O la idea es exportar las tablas ya pobladas de la base de datos de la entrega 2 a la base de datos nueva de grupo 3?

**Comment by ypne** [comment]
R: Las tablas creadas puedes modificarlas pero deben cargar de nuevo los datos para usar los cargadores
