### ISSUE TITLE
Duda sobre el anuncio de aclaraciones y el preprocesamiento

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#259]
Hola! En el anuncio aparece lo siguiente: "La carga de datos se debe hacer DIRECTO A LAS TABLAS del modelo definido por ustedes desde los archivos csv o excel entregados,  SIN PREPROCESAMIENTO   alguno."

Sobre esto:

1. Esto significa que no puedo crear tablas iniciales para cargar los datos entregados? Y despues a partir de estas en el mismo cargador crear las tablas definitivas de nuestro esquema? Esto lo pregunto porque no tiene sentido no poder hacerlo, ya que hay tablas de nuestros esquemas que dependen de más de una tabla por lo que necesitaría cargar la información previamente para despues crear las tablas finales. De hecho en el enunciado mismo se da ejemplos de tablas que dependen de dos tablas como la de usuarios que debe cargar los datos de los pares en la de los impares

2. Si se refieren a la modificación manual de los datos como preprocesamiento. He visto en issues anteriores que si dan por permitido hacerlo. De hecho frente a muchos casos como las fechas y otras cosas se  ha respondido diciendo que se pueden preprocesar.  Entonces debemos eliminar la existencia de dichas issues? Podrian hacer un listado de las issues que quedan como invalidas?

3. No termina de quedar claro que seria preprocesar, es modificar a mano o es modificar con codigo antes de subirlo a la base de datos propiamente tal? Más específicamente pueden dar un ejemplo de preprocesamiento no permitido? 

4. En caso de que no este permitido lo que mencione al inicio sobre la creación de tablas, es posible extender el plazo? Ya que esto no se menciono en el enunciado original y ya ha pasado mucho tiempo desde el inicio del proyecto, ademas que aun no recibimos el feedback de nuestros proyecto anterior.

**Comment by ypne** [comment]
P: Esto significa que no puedo crear tablas iniciales para cargar los datos entregados? 
R: Así es, se dee crear el modelo E/R, Schema normalizado, tablas y luego polar desde los archivos csv

P: No se deben preprocesar los datos, se deben crear los cargadores realizar la carga, detectar los errores y luego solucionarlos. Hay diferentes tipos de errores:
1.- caracteres inválidos, estos pueden carturarlos en el cargador(PHP) y reemplazarlos antes de insertarlos
2.- Violaciones a UNIQUE

**Comment by SantiagoDLCB** [comment]
Entonces para dejarlo super claro. Si yo creo todos los esquemas primero y entre estos esquemas primero creo la tablas Multimedia, Pelicula, Capitulo y Serie. Puedo poblar primero multimedia directo desde el csv sin realizar cambios y despues poblar las otras 3 tablas a partir de multimedia, para posteriormente elimnarlo todo esto desde un mismo script que lo hace automáticamente. Este proceso para poblar las tablas Pelicula, Capitulo y Serie, contaria como un postproceso?

**Comment by ypne** [comment]
P:Puedo poblar primero multimedia directo desde el csv sin realizar cambios y despues poblar las otras 3 tablas a partir de multimedia
R:SI
P: Este proceso para poblar las tablas Pelicula, Capitulo y Serie, contaria como un postproceso?
R: Mas o menos, el POST PROCESO es solo sore los errores
