### ISSUE TITLE
pregunta 6

### ISSUE THREAD

**Issue by Eduuuuuuuuuuuuuuuuuuuuu** [IIC2413/Syllabus-2023-2#26]
"Liste todos los nombres de los autores que no son autores de ning´un libro." ¿Esto se refiere a los autores que han publicado o editado libros o cualquiera de los dos?

**Comment by RICARDOOVIEDO** [comment]
Me dijeron los profesores que están discutiendo esa pregunta, y que mandarán un anuncio pronto!
