### ISSUE TITLE
Dudas Diccionario, Booleans seccion par

### ISSUE THREAD

**Issue by UCFelipeIGS** [IIC2413/Syllabus-2023-2#260]
Hola!

Tenemos dudas sobre si tenemos que utilizar todos los parametros y contrains tal como dice el diccionario y almacenarlos, al final seguirlo al pie de la letra eso o simplemente utilizar esa info para crear nuestras tablas a nuestra conveniencia? Por ejemplo, puedo crear una tabla (en base a dependencias funcionales) y crear suscripciones finalizadas y suscripciones no necesariamente finalizadas en base a un boolean estado?

y respecto a lo que dicen que DEBE ESTAR EN BD, tenemos que asegurarnos que exista en la info de la tabla original videojuegos o que tambien se cumpla para subtablas?

Muchas gracias!!

**Comment by ypne** [comment]
P: Tenemos dudas sobre si tenemos que utilizar todos los parametros y contrains tal como dice el diccionario 
R: Si, la única excepción es que **_podrían_** eliminar el UNIQUE del nombre del usuario pero dee ser justificado en el readme

P: simplemente utilizar esa info para crear nuestras tablas a nuestra conveniencia?
R: Pueden generar el modelo E/R a su conveniencia pero la D dee estar en 3NF o BCNF

P: crear suscripciones finalizadas y suscripciones no necesariamente finalizadas en base a un boolean estado?
R: Ese dato ya está en los archivos

P: DEBE ESTAR EN BD, tenemos que asegurarnos que exista en la info de la tabla original videojuegos o que tambien se cumpla para subtablas?
R: qué es una sutala para ustedes? la restricción DEBE ESTAR EN BD indica que si van a usar un ID este registro debe existir previamente en la entidad, excepto claro que estén insertando un nuevo dato en la entidad.
Por ejemplo, si van a cargar una visualización de una película, ésta dee existir.
