### ISSUE TITLE
3.4 Compras E3

### ISSUE THREAD

**Issue by MariaJoseSilva** [IIC2413/Syllabus-2023-2#261]
Hola, 
Tengo algunas preguntas sobre el punto 3.4 Compras, página de _one time purchases_, debido a que los detalles de la página están enfocados en la compra de películas y no de videojuegos. 

> 1. Inciso b: que la suscripción  al proveedor este vigente. Esto no aplica a los videojuegos debido a que la suscripción es directo al videojuego y no al proveedor. Para este caso (videojuegos), podría ser verificar si el usuario tiene una cuenta en el proveedor elegido?

> 2. Inciso d:  se debe generar la compra en las tablas del grupo impar que estén involucradas. Qué se debe hacer para el caso de los videojuegos, que se manejan en las tablas del grupo par?

> 3. Inciso e: se debe generar un store procedure al final de la compra. En este caso ¿Cómo se determina el final de la compra? 

Muchas gracias!

**Comment by lpalacios1** [comment]
1) inciso b. Si verifica si el usuario tiene cuenta en el proveedor elegido. 
2) inciso d En el caso de los videojuegos, son pagos unicos, a través de proveedores, entonces tiene que ser consistente la compra proveedor-videojuego. 
3) "contenga los botones cancelar
y OK para cancelar toda la compra o ejecutarla respectivamente." En el caso de apretar OK o cancelar se determina el final de la compra (ya sea cancelada o aceptada será el final)
