### ISSUE TITLE
3.6 Enunciado E3

### ISSUE THREAD

**Issue by JaviL13** [IIC2413/Syllabus-2023-2#264]
Hola, quería hacer una consulta sobre la parte 3.6 del enunciado. ¿cómo es posible que una suscripción este cancelada y activa al mismo tiempo?

**Comment by ypne** [comment]
R: El concepto es diferente, cuando se cancela una suscripción el servicio sigue funcionando hasta la fecha de fin porque, en general se pagan por mes adelantado. Por eso, para ver si hay unna visualización hay que fijarse en la fecha de término no en la cancelación.

**Comment by JaviL13** [comment]
Ya, entonces, si que una cuente esta activa no esta relacionada con el estado de la subscripción con que lo esta ??
