### ISSUE TITLE
Vista materializada página Mi Perfil

### ISSUE THREAD

**Issue by VicenteSanMartin** [IIC2413/Syllabus-2023-2#266]
Hola! En relación a la página Mi Perfil que se solicita que creemos en el ítem 3.1.2, tenemos una duda sobre si es necesario que los datos del usuario estén en una vista materializada. Esto ya que un usuario puede registrarse (crear un usuario nuevo) e intentar ver su información personal, pero como la vista materializada se hace cada 1 día entonces no le aparecerían sus datos personales.

**Comment by ypne** [comment]
R: Así es, eso no es un error, el objetivo es que aprendan a usar las vistas materializadas, no es necesario que hagan la programación para arreglarlo. Si quieren pueden agregar un cartel de .... su información será desplegada mañana

**Comment by VicenteSanMartin** [comment]
Gracias!
