### ISSUE TITLE
Error en Diccionario Proveedores grupo impar

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#267]
Hola! creemos que errores en el diccionario en la seccion de proveedores.

> Proveedores
> id, INT NN id del proveedor
> nombre: TEXT NN nombre del proveedor
> costo: FLOAT costo de la serie CONSTRAIN (costo o precio debe existir en la BD)
> sid: INT Id de la serie CONSTRAIN debe existir en la BD
> pid,:INT id de la película CONSTRAIN debe existir en la BD
> precio: FLOAT precio mensual de la suscripción
> disponibilidad: INT Cantidad de películas disponibles (debe existir para cada pid)

Se nos entrego esto en el enunciado pero observamos dos errores o inconsistencias.

En primer lugar, creemos que las definiciones de costo y precio estan invertidas, dadas las tablas entregadas, ya que en la columna  precio de las tablas no todos los proveedores tienen un precio asociado pero si un costo, lo cual significaria que hay proveedores gratis y que todas las peliculas y series son pagadas adicionalmente, lo cual no tiene sentido.

En segundo lugar, creemos que la definicion de costo tiene otro problema ademas de estar invertida, ya que por lo que entendemos solo las pelliculas se pueden pagar por fuera como un adicional, no las series, ademas que en caso de que fueran las series no tendria sentido con el atributo disponibilidad.

**Comment by ypne** [comment]
R: Estan invertidas, lo corrijo
