### ISSUE TITLE
Carga de datos

### ISSUE THREAD

**Issue by cristobal-contreras** [IIC2413/Syllabus-2023-2#268]
Hola una duda, la carga de los datos desde el archivo csv a la respectiva base de datos en psql se debe hacer si o si con un script de php? O eso queda a elección de cada grupo (usar python por ejemplo)? 
En el caso de que se deba usar si o si un script de php, hay algún material disponible en el curso que nos oriente en eso?

**Comment by ypne** [comment]
R: en PHP, si hay material en el curso y se hizo en ayudantía

**Comment by cristobal-contreras** [comment]
En qué ayudantía? En el código subido de la última ayudantía (Ayudantía 4 sobre procedimiento almacenados) no hay ningún script de php de carga de datos.

**Comment by ypne** [comment]
R: Ayudantía 3

**Comment by CarlangaUC** [comment]
Hola!

Estuve buscando en la ayudantia y no encontre nigun codigo asociado a esto, soy solo yo?

**Comment by ypne** [comment]
R: ejecutar la query COPY tu_tabla FROM '$rutaArchivoCsv' WITH (FORMAT csv, HEADER, DELIMITER ',')
