### ISSUE TITLE
Actualización datos grupo par

### ISSUE THREAD

**Issue by Vicentapd** [IIC2413/Syllabus-2023-2#269]
Hola, me gustaría consultar en cuanto al cambio de los datos del grupo par, notamos que ya no existe suscripciones, sin embargo sigue existiendo subs_id en la tabla de pagos, y anteriormente este entregaba información sobre el juego referenciado. Con la información actual no es posible saber a que proveedor se le pago por la suscripcion y este cambio de datos altera las relaciones que habiamos hecho con anterioridad.
Podrían explicarnos los cambios realizados y como estos mejoran el problema que anteriormente comunicamos en cuanto a la dificultad de asociar pagos de suscripciones a proveedores.

**Comment by ypne** [comment]
R: Pueden agregar un proveedor cualquiera que provea el servicio

**Comment by hansjkl** [comment]
¿Y qué hacemos respecto a la tabla faltante de suscripciones en los datos actualizados?

**Comment by ypne** [comment]
la subniremos
