### ISSUE TITLE
Sobre el desarrollo de las preguntas Control 1

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#27]
Hola! En la pregunta 1 solo tenemos que entregar las cantidades respectivas o debemos explicar el procedimiento mediante el cual llegamos a esa conclusión?

Por otra parte en el resto de preguntas, aparte de escribir la consulta en algebra relacional, debemos explicar dichas consultas?

**Comment by RICARDOOVIEDO** [comment]
Con respecto a la primera, con solamente la cantidad de consultas es suficiente! Y con las otras preguntas, la consulta es suficiente. Si quieres poner una explicación puedes hacerlo pero no se te corregirá distinto por hacerla.

Saludos.
