### ISSUE TITLE
Duda de enunciado E3

### ISSUE THREAD

**Issue by jpedrodelrio** [IIC2413/Syllabus-2023-2#270]
Hola! No entiendo si ahora en la pagina principal hay que mostrar todas las consultas de ambos grupo, par e impar, es decir ahora hay que mostrar 14 consultas cada una conectada a su respectiva base de datos? Otra cosa el enunciado esta muy confuso seria bueno si pueden mandar algun anuncio explicando mejor este tipo de cosas ya que no esta muy claro y esta enredado de entender de que se quiere especificamente.

**Comment by ypne** [comment]
P:  es decir ahora hay que mostrar 14 consultas cada una conectada a su respectiva base de datos?
R: No hay que implementar las consultas de la E2
