### ISSUE TITLE
Control 3 pregunta 1 "votantes por primera vez"

### ISSUE THREAD

**Issue by j-mv** [IIC2413/Syllabus-2023-2#271]
Hola,

No me queda claro a qué se refieren con "votantes por primera vez". ¿El número de registros es la cantidad de veces que alguien ha votado? Me confundo porque el número de registros tiene el mismo valor para todos.

**Comment by lfb1206** [comment]
Hola! Para esta pregunta te recomiendo revisar cuando fue la votación previa al plebiscito del 2020 (datos que se utilizan en el control), si quieres irte a la segura escribe el supuesto que realizaste.
