### ISSUE TITLE
Duda pregunta 1b Control 3

### ISSUE THREAD

**Issue by Gcamposbriceno** [IIC2413/Syllabus-2023-2#272]
Hola! 

En la pregunta 1b del control se pide lo siguiente:

Calcule el tamaño del padrón electoral y de los votantes por primera vez.

1. No me queda claro si el padrón electoral cuenta a todas las personas registradas, o únicamente a los que votaron
2. Tampoco me queda claro cómo determinar quién es elegible como votante por primera vez (a través del grupo de edad? o como se vota cada 4 años serían los menores de 22?). Además, hay que contar sólo a quienes votaron?

Por favor ruego claridad en la respuesta🙏 . Las respuestas a issues durante el semestre han sido bastante poco satisfactorias.

**Comment by ypne** [comment]
R1: Artículo 31.- El Servicio Electoral deberá elaborar dos padrones electorales, uno para electores que sufraguen en territorio nacional, y otro para electores que sufraguen en el extranjero. Cada uno de estos padrones, contendrá la nómina de los electores inscritos en el Registro Electoral que reúnen los requisitos necesarios para ejercer el derecho a sufragio conforme a los antecedentes conocidos por él, dentro o fuera de Chile, y según lo dispuesto en el artículo siguiente, según corresponda.
    Cada elector podrá figurar en un Padrón Electoral y sólo una vez en él.
R2: las últimas votaciones han sido 2022 2021 2020 y 2017. Asuman que todos que cumplen 18 años ese año pueden votar

**Comment by martineyz** [comment]
Respecto a esto, se podría dar una respuesta más clara?

Especificamente las siguientes preguntas (en el contexto del control)

1. Que determina si un ciudadno es parte o no del padron electoral? 

2. Que determina que un ciudadno haya votado por primera vez?

Porfavor ceñirse a los elementos de la base de datos prorcionada en las respuestas, ya que no tendríamos porque tener conocimientos de la terminologia del proceso electorar para el contexto de este ramo. Gracias de antemano.

**Comment by lfb1206** [comment]
Hola! Los datos que se utilizan son reales, te recomiendo revisar este [link](https://es.wikipedia.org/wiki/Censo_electoral) para aclarar tus dudas sobre que es un padrón electoral. Sobre tu segunda consulta, respondí ello en el issue #271. 

Sobre lo que expones ("no tendríamos por qué tener conocimientos de la terminología del proceso electoral para el contexto de este ramo"), al trabajar con datos externos se requiere investigar e informarse sobre los conceptos, es por esto que se dan tres días para realizar el control. Estos no son conceptos complejos ni difíciles de encontrar y sí se puede considerar dentro del contexto del ramo, ya que es una habilidad que vas a necesitar al trabajar con bases de datos ajenas.

¡Mucha suerte!
