### ISSUE TITLE
Control 3 pregunta 1-b

### ISSUE THREAD

**Issue by jpedrodelrio** [IIC2413/Syllabus-2023-2#273]
Cuando aparece:
1. Calcule el tamaño del padron electoral, se refiere a todos los que estan habilitados para sufragar, o solo a los que votaron??
2.  Calcule los votantes por "primera vez" se refiere a los que tienen 19 años de edad? pq el numero de registros es 1 para todos

**Comment by palacioscb** [comment]
Hola. tengo la misma segunda duda

**Comment by lfb1206** [comment]
Esta pregunta ya se respondió en otras issues.
