### ISSUE TITLE
Control 3: pregunta 1-g

### ISSUE THREAD

**Issue by martineyz** [IIC2413/Syllabus-2023-2#274]
Cuando dice 'percentil de edad', se refiere a rango de edad?

**Comment by ypne** [comment]
R: https://dle.rae.es/percentil

**Comment by martineyz** [comment]
Que perecentiles habría que graficar? Ya que si dice percentiles en general yo entiendo que serían los 100 percentiles, osea 100 valores en el eje X, lo cual me parece un poco absurdo considerando el tamaño del grafico. Para el calculo de percentiles se considera desde la edad minima presente en la tabla hasta la maxima o se cuenta desde el 0?

**Comment by lfb1206** [comment]
Para realizar los percentiles se debe de considerar la edad mínima y máxima de los datos, ojo que la edad mínima no es necesariamente el percentil 0.

**Comment by IsabellaKPM** [comment]
Hola, tengo una duda similar, por ejemplo si hago un gráfico de barras con los percentiles 0%-25%, 25%-50%, 50%-75% y 75%-100% en el eje X escritos de esa forma está bien? tipo sólo con 4 barritas?

**Comment by martineyz** [comment]
> Para realizar los percentiles se debe de considerar la edad mínima y máxima de los datos, ojo que la edad mínima no es necesariamente el percentil 0.

Pero que percentiles debemos graficar? Como comenté hay 100 percentiles (1% al 100%), no me parece muy razonable graficar los 100. 

Otra duda que me surge es que tipo de grafico se debe usar (lineas, barras, etc..)

**Comment by lfb1206** [comment]
Hola! Les recomiendo usar un scatter plot, hace más amigable la vista del gráfico. Sobre cuantos percentiles hay que graficar, deben de adaptar los datos a percentiles y eso les entregara cuantos percentiles se grafican, spoiler, existen funciones de pandas para obtener eso, investiguen.

**Comment by martineyz** [comment]
> Hola! Les recomiendo usar un scatter plot, hace más amigable la vista del gráfico. Sobre cuantos percentiles hay que graficar, deben de adaptar los datos a percentiles y eso les entregara cuantos percentiles se grafican, hint, existen funciones de pandas para obtener eso, investiguen.

Investigando encontré la función que divide los datos en percentules, pero hay que pasarle como parametro que percentiles queremos. ¿Queda a nuestro criterio en cuantos percentiles dividimos? ¿O hay alguna funcion que divide en percentiles sin especificar cuales? (Para seguir investgando si es el caso)

**Comment by lfb1206** [comment]
Hay una que no hay que pasarle qué percentiles quieren.

**Comment by martineyz** [comment]
> Hay una que no hay que pasarle qué percentiles quieren.

Las unicas que pude encontrar son pd.qcut y np.percentile pero ambas requieren un q como argumento (cantidad de divisiones). ¿Sería posible que me digas a que funcion te refieres o como buscarla? No se como más buscar la verdad.

**Comment by lfb1206** [comment]
Claramente, no te puedo indicar qué función utilizar, busca la mejor forma de realizarlo y, por último, deja explicitado que asumiste para resolver el problema. Como recomendación sobre como buscarla, realiza la búsqueda en inglés, suelen aparecer más soluciones de esta forma.

**Comment by martineyz** [comment]
Lamentablemente no pude encontrar dicha funcion, en todas las paginas se hablaba de qcut que pide un numero de divisiones o cut que pide el intervalo de bins. ¿Es psobile usar qcat y determinar bajo mi criterio el numero de percentiles a usar (pj 10), especificandolo en la respuesta?  Teniendo en cuenta que en el enunciado simplemente dice 'indique el número de personas que votaron y los que no por percentil de edad'.

**Comment by martineyz** [comment]
O por lo menos graficar todos lo percentiles ya que en el enunciado dice literalmente 'por percentil de edad', lo cual deberían ser los 100 si no se especifica.

**Comment by PSepulvedaS** [comment]
Como se dijo anteriormente, deben encontrar la mejor forma de graficar según su criterio, no podemos estar indicando qué librería utilizar. Acerca de los percentiles, dejen explícitos los supuestos que hicieron a la hora de graficar.

**Comment by UCFelipeIGS** [comment]
Hola, sobre dicha funcion creo que la encontre pero no me funciono bien, es posible ocupar numpy library? Porque solo de esta manera me funcionaron los percentiles, con cut de pandas no daban bien las medidas.

**Comment by lfb1206** [comment]
Sí, es posible utilizar esa librería.
