### ISSUE TITLE
error en php

### ISSUE THREAD

**Issue by LunaGarces** [IIC2413/Syllabus-2023-2#276]
hola, soy del grupo 19, tengo un problema con una consulta en php que tengo dentro del index html que muestra la pagina, por alguna razón la consulta se printea literalmente en mi pagina, la consulta no se ejecuta.

**Comment by lpalacios1** [comment]
Puede que tengas errores dentro de como llamas el php. Si la consulta se esta printeando literalmente en la pagina, significa que nunca se "activa" la función de php. Podrias revisar parentesis u otros errores de sintaxis. Avisame si sigue el problema.
