### ISSUE TITLE
Pregunta 1-b

### ISSUE THREAD

**Issue by cattpuccino** [IIC2413/Syllabus-2023-2#277]
Cuando habla de padrón electoral, ¿se considera a los que tienen la capacidad de votar? ¿Y cuando habla de ciudadanos, son los que pueden votar o la población completa?

**Comment by panchouc** [comment]
Me sumo a la pregunta, cuando preguntan tamaño padrón electoral, se refiere a la cantidad de personas que existe en la base de datos?

**Comment by ypne** [comment]
R: "Para este control trabajaremos con una base de datos real (anonimizada) del SERVEL acerca del plebiscito, he indica si cada ciudadano voto o no en el plebiscito del 2020."

**Comment by lfb1206** [comment]
Esta consulta se respondió en la issue #271 y en la #272.

Mucha suerte!
