### ISSUE TITLE
Control 3: Pregunta  2 b)

### ISSUE THREAD

**Issue by martineyz** [IIC2413/Syllabus-2023-2#278]
En el item 2.  de esta parte, hay 2 consultas (SELECT * FROM Persona WHERE id=55552. SELECT * FROM Persona WHERE nombre=’John Doe’), hay que reponder el costo para cada una o como?

**Comment by ypne** [comment]
R: solo SELECT * FROM Persona WHERE nombre=’John Doe’

**Comment by lfb1206** [comment]
Se actualizó el control y envió anuncio, pido disculpa por las molestias que pudo haber ocasionado este error, por suerte se podía observar que era la misma consulta por la que se preguntaba previamente en la pregunta.

Muchas suerte!
