### ISSUE TITLE
Control 3: Salidas truncadas

### ISSUE THREAD

**Issue by jorgee02** [IIC2413/Syllabus-2023-2#279]
Hola, se pueden usar comandos como el de que se ponga max rows y esas cosas para evitar que las salidas sean truncadas?

**Comment by lfb1206** [comment]
Hola! Tan solo la consulta a) podría requerir mostrar una tabla, todas las otras piden números o gráficos, por lo que no deberían de tener salidas truncadas.

**Comment by jorgee02** [comment]
Hola, disculpa por no explicarme bien. Me refería a la pregunta 1

**Comment by lfb1206** [comment]
En efecto, en la pregunta 1 tan solo se piden números, exceptuando la pregunta 1 a). ¿En cuál pregunta de la pregunta 1 tienes duda?

**Comment by jorgee02** [comment]
En la c y d por ejemplo se puede mostrar una salida que sería quizás más grafico. Pensaba eso!

**Comment by lfb1206** [comment]
Si quieres representarlo con gráficos, está bien, al utilizar matplotlib no se debería de cortar la figura, por lo que no debiese ser problema. Te recomiendo más realizarlo entregando números como resultados, siento que simplifica bastante el problema, estilo, x personas no votaron e y personas votaron.

**Comment by jorgee02** [comment]
No sisi, cuando dije más grafico me refería a que es más claro, porque sería una salida. Pero ya logré hacerlo, muchas gracias!!
