### ISSUE TITLE
Consultas integradas en ambas bases de datos 30pt

### ISSUE THREAD

**Issue by Nicolas413** [IIC2413/Syllabus-2023-2#280]
¿A que se refieren con integradas en ambas bases de datos?, ¿hay que poseer dos bases para esta entrega o solamente una conjunta?

**Comment by ypne** [comment]
R: Punto 3 "3.	Requerimientos
Su aplicación deberá integrar la base de datos de la plataforma de meta streaming con la meta tienda de videojuegos. Para ello se deben manejar cada una en forma independiente en el servidor respectivo de modo mantener dos conexiones abiertas.
No se permite migrar el esquema a la base de datos de uno de los grupos excepto que se indique expresamente."
