### ISSUE TITLE
Control 3: Preguntas 1b, 1f

### ISSUE THREAD

**Issue by IsabellaKPM** [IIC2413/Syllabus-2023-2#281]
Holaa, en las preguntas 1b y 1f ¿se requiere que el código entregue ambas respuestas juntas o pueden ser dos líneas aparte?.
Por ejemplo tengo dos prints en la 1b, uno con el tamaño del padrón y otro con los votantes por primera vez, cada uno con códigos distintos de panda y no sé si en realidad debería hacer un sólo código que entregue inmediatamente ambas cosas (como en una tablita de dos columnas o algo así) o si está bien que sean por separado y eso no importa.

**Comment by lfb1206** [comment]
Da lo mismo, lo que te acomode más. Lo importante es que se puede entender cuál resultado corresponde a cada uno, el formato no es tan relevante.
