### ISSUE TITLE
Problemas con RAM google colab

### ISSUE THREAD

**Issue by cebabeltran** [IIC2413/Syllabus-2023-2#283]
Hola!
He estado teniendo unos problemas al trabajar el .ipynb en google colab, ya que se me suele reiniciar el entorno al correr celdas de código debido a que "se utiliza toda la RAM disponible". Hay alguna forma de solucionar esto o alguna recomendación de otro programa para trabajar notebooks de Jupyter? Gracias de antemano!

**Comment by lfb1206** [comment]
Hola! Puede ser que leer muchas veces el csv produzca que se utilice toda la RAM, aparte de esto, no debería de existir problema con que se cope la RAM. De seguir con el problema, te recomiendo correr las celdas necesarias para continuar realizando el resto de las preguntas y al final revisar que todos los resultados estén impresos.
