### ISSUE TITLE
Duda pregunta 1b

### ISSUE THREAD

**Issue by cebabeltran** [IIC2413/Syllabus-2023-2#284]
Hola! Tengo una duda con la pregunta 1b del control 3. Cuando dice "los votantes por primera vez" a qué se refiere? Tengo entendido que serían las personas que no habían votado antes. De ser este el caso, qué valor refleja esto en la tabla de datos? no entiendo a qué haría referencia. Gracias de antemano!

**Comment by lfb1206** [comment]
Esta pregunta ya fue respondida en otra issue
