### ISSUE TITLE
2b enunciado primary key + hojas ocupadas al 75%

### ISSUE THREAD

**Issue by UCFelipeIGS** [IIC2413/Syllabus-2023-2#287]
Hola!
En ningun momento se especifica cual es la primary key, cual es (nombre o id)? Tambien hay una posterior consulta del nombre, siendo que no esta indexado como hash ni b+tree, se supone que esta bien dicha consulta ya que no tendria indices realmente? Ademas cuando se menciona "y las hojas están ocupadas al 75%." me imagino que se refiere a que cada pagina de la hoja esta ocupada al 75%, pueden corroborar? 

Muchisimas gracias!

**Comment by UCFelipeIGS** [comment]
Muchisimas gracias, entendi!

**Comment by Bjnazar** [comment]
> El primary key es id Si los nombres no están indexados, la consulta es menos eficiente Si las hojas están ocupadas al 75%, significa que en promedio, cada página de hoja del B+Tree está llena en un 75% de su capacidad.

Hola!
Esta capacidad de las hojas aplica para punteros? O sea, en el caso de que el árbol sea unclustered y sus páginas tengan punteros a las páginas con las tuplas, tambien está lleno hasta el 75% de su capacidad en punteros?

**Comment by lpalacios1** [comment]
Creo que si pero no estoy absolutamente seguro. Puedes dejarlo como supuesto ante la duda.
