### ISSUE TITLE
Control 3, P1 nombre dato 

### ISSUE THREAD

**Issue by catalinamirandah** [IIC2413/Syllabus-2023-2#290]
Hola, ¿quería consultar qué indica la columna 'Número de registros'?

**Comment by GabQuiroz** [comment]
Hola, no es relevante para contestar las preguntas del control, puedes ignorarlo.

**Comment by josegarafulic** [comment]
@GabQuiroz Yo asumi que numero de registros era la cantidad de veces que había votado. Que variable usamos si no esa para determinar cuantas veces ha votado?

**Comment by GabQuiroz** [comment]
Ah entiendo, para eso debes usar la edad de los votantes. Como se dijo en la issue #271, revisa cuando fue la última votación previa al plebiscito del 2020 para contestar la pregunta relacionada a eso y anota igual tus supuestos.
