### ISSUE TITLE
c3 duda 1c,d,e

### ISSUE THREAD

**Issue by UCFelipeIGS** [IIC2413/Syllabus-2023-2#291]
Hola!
Tengo unas dudas respecto a lo entendido por lo requerido:
1c: en el momento que hablamos que votaron y no votaron por rango de edad, en las que votaron por rango de edad es que sufrago + su edad esta en el rango de edad y en las que no votaron incluimos a las que su edad no esta en el rango + las que no sufragaron a pesar de que su edad este o no en el rango?

1d en los que no votaron, solo me baso en el hecho que sufragaron o no? O se debe analizar de una manera distinta.

1e. con chilenos suponemos que automaticamente por estar en el padron son chilenos, cierto?

Muchas gracias!

**Comment by GabQuiroz** [comment]
Hola, contestando tus preguntas:

1c: Hay que obtener, para cada rango de edad, la cantidad de personas que votaron y la cantidad de personas que no han votado que están en dicho rango de edad.

1d: Si alguien votó es que sufragó, si no, significá que no sufragó.

1e: No necesariamente, puedes ser extranjero y estar en el padrón.

**Comment by UCFelipeIGS** [comment]
Super! Muchas graciass
