### ISSUE TITLE
Control 3, P2

### ISSUE THREAD

**Issue by solebravo** [IIC2413/Syllabus-2023-2#292]
Hola! queria saber y en la pregunta 2 en la parte de los costos basta con poner el resultado o hay que explicitar el desarrollo.
gracias de antemano!

**Comment by lfb1206** [comment]
Siempre es bueno explicitar un desarrollo, así el corrector puede entender el proceso y tanto dar mejor feedback como entregar puntaje parcial, de aplicar.
