### ISSUE TITLE
Control 3, P3.b orden datos

### ISSUE THREAD

**Issue by catalinamirandah** [IIC2413/Syllabus-2023-2#293]
En la parte b de la pregunta 3, ¿asumimos que las transacciones ocurren en paralelo?

**Comment by UCFelipeIGS** [comment]
Yo tampoco entiendo eso, tiene un orden predeterminado o es tan solo un conjunto de tareas? Y la pregunta es acorde si una combinacion de las diversas acciones de la tx 1 con otra de la tx 2 puede provocar un error de ese tipo? Si ese fuera el caso se menciona 1 ejemplo o todos los posibles casos?

**Comment by PSepulvedaS** [comment]
Respondiendo a la primera pregunta, las transacciones ocurren en paralelo. Con respecto a lo otro, no les puedo responder a esa pregunta, deben averiguarlo ustedes o por último dejen supuestos.

**Comment by CrisDonosoMaass** [comment]
> Respondiendo a la primera pregunta, las transacciones ocurren en paralelo. Con respecto a lo otro, no les puedo responder a esa pregunta, deben averiguarlo ustedes o por último dejen supuestos.

Con paralelo te refieres a que la primera accion de T1 y T2 ocurren a la vez y así sucesivamente, o puede que T1 este recién en su primera acción y T2 ya haya terminado?

**Comment by panchouc** [comment]
Me sumo a la duda, cuando dices en paralelo, te refieres como a tener 2 threads corriendo al mismo tiempo? Pues de lo que entiendo, se podría dar que una de las transacciones acceda a uno de los recursos antes que el otro, es decir, que si bien están corriendo en paralelo, el orden de precedencia de las operaciones podría variar de caso a caso, es correcto eso?

**Comment by panchouc** [comment]
También tengo una duda, dado que tenemos por ejemplo W(B, A*2), se asume indirectamente que para hacer la operación del write, se debe hacer primero un read a la variable A?

**Comment by MariaJoseSilva** [comment]
Hola! 
En esta misma pregunta, es válido asumir que las transacciones no han terminado? O finalizan con el último elemento que se muestra?

Muchas gracias.

**Comment by RaiEscalona** [comment]
Al final, pueden asumir que cada W o R de la T1 se hace antes que la T2 y en orden secuencial hacia abajo.
