### ISSUE TITLE
Control 3: Pregunta 2a

### ISSUE THREAD

**Issue by IsabellaKPM** [IIC2413/Syllabus-2023-2#295]
Holaa. En la pregunta 2a en el segundo punto ("Mencione cómo cambian los costos de busqueda para consultas de igualdad y rango.") ¿se deben indicar los cambios de costos _**sólo**_ para el B+Tree que indicamos en el primer punto ("Explique cómo se puede hacer que un B+Tree pueda indexar el atributo edad de la relación Persona.") o para todos los tipos (Hash y B+Tree ambas variaciones)?. Graciaas.

**Comment by RaiEscalona** [comment]
Solo hay que indicar los costos para el B+ tree
