### ISSUE TITLE
Consulta inestructurada, proyecto.

### ISSUE THREAD

**Issue by martineyz** [IIC2413/Syllabus-2023-2#296]
Rspecto a este tema tengo algunas dudas:

1. En el enunciado dice "dejando el resultado en el archivo consulta.txt".  ¿En que formato se daja el resultado?

2. ¿No hay que mostrar el resultado de la consulta en la pagina? (Me parece que sería mucho más funcional que guardarlo en un archivo) 

3. Cuando trato de escribir un archivo mediante el script php desde la web me sael este error: Warning: file_put_contents(../consulta.txt): Failed to open stream: Permission denied in /home/grupo61/Sites/consulta.php on line 48. ¿Como se podría solucionar?

**Comment by martineyz** [comment]
Respecto a esto mismo, cuando trato de escribir un archivo, me sale esto: Warning: file_put_contents(../consulta.txt): Failed to open stream: Permission denied in /home/grupo61/Sites/consulta.php on line 48. Como se podría solucionar?

**Comment by j-mv** [comment]
Como solucionaste este error? Warning: file_put_contents(../consulta.txt): Failed to open stream: Permission denied in /home/grupo61/Sites/consulta.php on line 48.

gracias

**Comment by martineyz** [comment]
@j-mv Hola! Primero que nada, me di cuenta que había puesto mal la ruta, ya que el php que estaba ejecutando se encontraba directamente en Sites (sobraba el ../). Además le di lo siguientes permisos a la web para que pueda ejecutar y escribir en la carpeta SItes:

chmod o+w Sites
chmod o+x Sites
chmod o+w /home/grupoXX/Sites
chmod o+x /home/grupoXX/Sites
chmod o+w /home/grupoXX
chmod o+x /home/grupoXX

Estos comandos se deben ejecutar en terminal (reemplaza XX por tu número de grupo). 

La verdad no se seguro cual o cuales de todos esos arregló el problema pero puedes ir probando. Espero que te sirva.
