### ISSUE TITLE
p3b cantidad de contraejemplos

### ISSUE THREAD

**Issue by UCFelipeIGS** [IIC2413/Syllabus-2023-2#297]
Hola!

Respecto a la pregunta de si es posible o no los casos (WW, RW, WR), con tan solo mostrar un caso en el que se podria dar WW (por ejemplo), cumplo con la respuesta o hay que mostrar todos los casos?

Muchas gracias!

**Comment by RaiEscalona** [comment]
En la pregunta dicen que deberías indicar si es posible algún tipo de conflicto por cada caso, por lo que al dar una explicación y mostrar un ejemplo de cada caso, deberías estar bien.
