### ISSUE TITLE
Subida .tex control 1

### ISSUE THREAD

**Issue by panchouc** [IIC2413/Syllabus-2023-2#3]
Hola! Quería pedir si pudiesen subir el .tex del pdf del control 1 para escribir sobre este. De antemano gracias.

**Comment by franfonte** [comment]
Si porfavor

**Comment by RICARDOOVIEDO** [comment]
No sé si existe uno. Voy a conversarlo con los ayudantes!

**Comment by RICARDOOVIEDO** [comment]
Hay un archivo, el profesor me lo mandará dentro del día.
