### ISSUE TITLE
Entrega 3 3.2 c)

### ISSUE THREAD

**Issue by tnaspee** [IIC2413/Syllabus-2023-2#300]
Hola! En el enunciado, en la parte de cómo manejar los errores en la carga de datos, la opción c) dice: "como tercera opción generar un log de errores para corregir y luego cargar solamente los esos registros."

Con esto se refiere a que una vez terminada la carga de datos, se lee el log generado y se corrigen todos los errores en él? Cargando así los datos que tuvieron errores en un principio?

**Comment by ypne** [comment]
R: si

**Comment by tnaspee** [comment]
Y en el caso de por ejemplo los errores que se originan por el constrain de que la fecha del pago debe ser menor a la actual, ¿qué hacemos para corregirla? ¿Le cambiamos la fecha a la actual? Ya que por lo que dice en el enunciado no deberíamos dejar afuera esta entrada de datos.

**Comment by ypne** [comment]
R: Si exkste ese caso haye opciones
1.- verificar que los dos formatos de fecha sean iguale DDMMAA o MMDDAA
2.- Si en. realidad está el prolema
2.1 puede asumir que el pago fue adelantado y deen ajustar la fecha de inicio y fin. a la fecha de pago y fin un mes despues
2.2 es un registro erroneo ny elimionarlo. La solución la eligen ustedes
