### ISSUE TITLE
Datos genero Grupo par en dos tablas

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#302]
Hola! en las tablas de grupo par existen dos columnas que le asignan un genero a un videojuego.
Estas son Video Juego Genero y Videojuego.
```
Video juego genero
id_videojuego: INT NN id del video juego
nombre: TEXT NN género o subgénero del video juego debe existir en la D
```

```
Videojuego
id_videojuego: INT NN id del video juego CONSTRAIN debe existir en la BD
titulo: TEXT NN nombre del video juego CONSTRAIN debe existir en la BD
puntuación: INT NN Puntuación del videojuego
clasificación: TEXT NN CONSTRAIN valores de ESRB o PEGI
fecha_de_lanzamiento: DATE NN fecha de lanzamiento del juego
beneficio_preorden TEXT beneficios de preorden
10
mensualidad: FLOAT NN valor de la suscripción
nombre: TEXT NN Género o subgénero CONSTRAIN debe existir en la BD
```

En ambas tablas la informacion del genero esta en la columna nombre. Mi duda es, cual de las dos consideramos ? Estan duplicadas por error? Se tienen que considerar las dos tablas?

**Comment by ypne** [comment]
P:  Hay varias cosas que se pueden hacer dependiendo de, entre otras cosas, el orden de carga. Todo dependerá del modelo. Ya que hay dependencias entre ambos. CHeckearon que los generos sean los mismos? hay conflictos?
Si los hay, agrego los generos a la otras tabla? Los elimino? es decisión de ustedes

**Comment by SantiagoDLCB** [comment]
Acabamos de checkear y son identicos los generos de ambas tablas para cada videojuego. Nuestra duda es : Podemos asumir que siempre lo van a hacer y que por lo tanto solo debemos cargarlos desde una sola tabla? En caso de que se pueda, desde cual tabla recomienda cargar? Finalmente si es un error la duplicacion pueden subir una nueva version de las tablas con eso corregido

**Comment by ypne** [comment]
R: El COSTRAIN indica nombre: TEXT NN Género o subgénero CONSTRAIN debe existir en la BD, deben controlar eso. Si viene uno diferente debieran ingresarlo en la Base para no perder datos. cuando normalicen esas talas van a cambiar.
