### ISSUE TITLE
Control 3: P3a. Error en el enunciado?

### ISSUE THREAD

**Issue by IsabellaKPM** [IIC2413/Syllabus-2023-2#303]
Hola. En la tablita que contiene el log redo de la pregunta 3a hay un error de enunciado? Durante las clases vimos que todas las transacciones que ya habían hecho COMMIT pero no END antes de un <START CKPT (T1, ..., Tn)> se les debía hacer un END antes del \<END CKPT\>. Pero aunque la transacción T1 cumple con estas condiciones (se le hizo START y COMMIT antes del \<START CKPT (T2, T3)\> pero no END) no se hace ningún \<T1, END\> antes del \<END CKPT\>. ¿Es esto intencional o un error de enunciado?. Muchas graciaas.

**Comment by ypne** [comment]
R: eso fue visto en clases
