### ISSUE TITLE
Cancelacion automatica de suscripciones

### ISSUE THREAD

**Issue by martineyz** [IIC2413/Syllabus-2023-2#305]
En el enunciado dice que se deben cancelar las suscripciones todos los días a las 00:00. Con esto se refiere a la hora del servidor o a la hora nuestra?

**Comment by antoniablanco** [comment]
Hola, las 00 es el mismo sin importar el huso horario.

**Comment by ypne** [comment]
las 00 es la misma para cada Huso horario.

**Comment by ypne** [comment]
Las 00 es la misma para cada Huso horario
