### ISSUE TITLE
Contraseñas registro 

### ISSUE THREAD

**Issue by cataguzmanw** [IIC2413/Syllabus-2023-2#306]
Hola! En el enunciado no menciona que al registrar un usuario nuevo este deba escoger una contraseña sino que solo un username, nombre y fecha de nacimiento, Debo agregar la opción de escoger contraseña verdad? Sino como va a saber el usuario su contraseña?

**Comment by ypne** [comment]
R: si claro, sino no  podrá volver a entrar. El usuario elige su contraseña
