### ISSUE TITLE
Sobre la migracion de usuarios y pagos

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#307]
Hola! Tenemos una duda respecto a la migracion de usuarios y pagos y como afecta esto a las otras tablas. Cuando en el diccionario se nos dice por ejemplo que un id_usuario debe pertenecer a la base de datos, debemos considerar ambas bases de datos o solo la que estamos cargando?. En caso de que sean ambas no seria necesario hacer una migracion doble, osea todo lo de los pares a los impares y todo lo de los impares a los pares? Esto porque si no una tabla que tiene por foreign key alguno de estos atributos compartidos no consideraria los datos de la otra base de datos. 

De manera similar si yo deseo crear un usuario , no me basta con crear dicho usuario solo en la base de datos del grupo impar ya que si despues deseo crear una compra de un videojuego por ejemplo, la tabla subscripcion que tiene como llave foranea al id_usuario no va a poder insertar el dato por que no existiria dicho dato en la tabla de usuarios de esa bdd

**Comment by ypne** [comment]
P: a ver si esto te lo aclara
la fase  1 es cargar los datos (con argapores) en esa fase trasladas los usuarios de PAR a IMPAR y esa tabla queda común. Luego traspasa ,los pagados de par a impar y nuevamente queda común.
Luego de esto pones la DB online
La fase 2 son las transacciones donde usarás la tabla de pago y usuarios común a los dos modelos.  PAR se quedan sin talas de usuarios y pagos.
en resumen, primero integras y luego permitas transaccones. Cualquir cosa me llamas por zoom, estaré agten

**Comment by SantiagoDLCB** [comment]
Si entiendo esa parte. El problema es otro, por ejemplo ¿que sucede si al momento de cargar los datos en par se intenta agregar una subscripcion o un pago a un usuario que no existe en la tabla de usuarios de par pero si existe en impar? Porque dado lo entregado en el diccionario el constraint no lo permitiria.

**Comment by ypne** [comment]
R: como en in principìo los usuarios par e impar pueden ser diferentes, solo deben agregar  el nuevo Usuarios. Cuando están migrado la base no está online, solo cuando terminen la integración se deben agregar usuarios- Al integrar todios los usuarios par que no estan en impar se agregar.
