### ISSUE TITLE
llave foránea de distinta base de datos para integrar pagos

### ISSUE THREAD

**Issue by GuilleStanke** [IIC2413/Syllabus-2023-2#308]
Para integrar los pagos PAR en la base de datos IMPAR necesito hacer tablas con una llave foránea que es una llave primaria en una tabla de la base de datos PAR, ¿es necesario crear el atributo que es llave primaria en PAR como llave foránea en IMPAR? ¿Cómo se podría hacer esto si son de dos bases de datos distintas?

**Comment by antoniablanco** [comment]
Las dos bases de datos deben ser independientes, es decir no deben estar relacionadas directamente en el schema entre ellas. Si es necesario relacionarlas pueden realizarlo por fuera en el código, pero sin que la existencia de una bdd requiera de la otra.
