### ISSUE TITLE
Posible caída servidor

### ISSUE THREAD

**Issue by cristobal-contreras** [IIC2413/Syllabus-2023-2#311]
Hola, puede ser que se haya caído el servidor? Me aparece esto: 
![Captura de pantalla 2023-11-18 221756](https://github.com/IIC2413/Syllabus-2023-2/assets/89169552/ca69b60e-a620-42fc-9d74-659bd47e6240)

**Comment by ypne** [comment]
R: No, esto correspon de a que el certificado expiró

**Comment by cristobal-contreras** [comment]
Cómo puedo solucionarlo?

**Comment by ypne** [comment]
cómo estan entrando? dime la linea.

**Comment by ypne** [comment]
ya se camió el certificado, ahora está ok
