### ISSUE TITLE
Entrega 3 parte 5 tabla Proveedores

### ISSUE THREAD

**Issue by weibac** [IIC2413/Syllabus-2023-2#313]
Cito textual la especificación de la tabla proveedores presente en la sección 5 del enunciado:

**Proveedores**
    id, INT NN id del proveedor
    nombre: TEXT NN nombre del proveedor
    costo: FLOAT precio mensual de la suscripción
    sid: INT Id de la serie CONSTRAIN debe existir en la BD
    pid,:INT id de la película CONSTRAIN debe existir en la BD
    precio: FLOAT costo de la serie CONSTRAIN (costo o precio debe existir en la BD)
    disponibilidad: INT Cantidad de películas disponibles (debe existir para cada pid)

Preguntas:
- Sobre el atributo precio:
  - ¿Hay un error de enunciado? Viendo los datos y los enunciados anteriores uno se hace la idea que este atributo hace referencia al precio de arriendo de películas, no series.
  - ¿Qué significa "costo o precio debe existir en la BD"?
    - ¿"costo o precio" se refiere solo al atributo precio, siendo "costo" un sinónimo redundante en vez de una referencia al atributo costo?
    - ¿Es "debe existir en la BD" una referencia a la tabla Pagos?
- Sobre el atributo disponibilidad:
  - ¿Qué significa "debe existir para cada pid"?
    - Viendo los datos, solo las películas en arriendo tienen este atributo no vacío. ¿Es correcto asumir que este atributo debería estar presente solo en las películas disponibles para arriendo?
- General
  - ¿Es correcto asumir que "CONSTRAIN" se refiere a "CONSTRAINT"? 

Comentario: Entiendo que introducir errores en el set de datos se corresponda con el objetivo pedagógico del curso, pero introducir errores en el enunciado parece un tanto excesivo.

**Comment by ypne** [comment]
P: Sobre el atributo precio: ¿Hay un error de enunciado? Viendo los datos y los enunciados anteriores uno se hace la idea que este atributo hace referencia al precio de arriendo de películas, no series.
P: Puede ser serie o película tal como pasa en la realidad, gracias por la aclaración

P: ¿Qué significa "costo o precio debe existir en la BD"?
R: Significa que para usar el valor de un atriuto, este debe estar registrado previamente en la ase de datos, por ejemplo solo pueden comprar algo que tenga precio.

P: ¿"costo o precio" se refiere solo al atributo precio, siendo "costo" un sinónimo redundante en vez de una referencia al atributo costo?
R: Coincido contigo que no es el nombre más afortunado, venía así desde la E2 por lo que se mantuvo, lo importante es la descripción del atributo

P: ¿Es "debe existir en la BD" una referencia a la tabla Pagos? 
R: El valor de la entidad debe estar definida

P: Sobre el atributo disponibilidad:¿Qué significa "debe existir para cada pid"?
R: Que si van a comprar debe haber disponiilidad 
P: Viendo los datos, solo las películas en arriendo tienen este atributo no vacío. ¿Es correcto asumir que este atributo debería estar presente solo en las películas disponibles para arriendo?
General
R: Esa es una característica particular de este set de datos
¿Es correcto asumir que "CONSTRAIN" se refiere a "CONSTRAINT"?
P: CONSTRAIN es un verbo, CONSTRAINT es un sustantivo. la idea es que usen la sentencia de postgress que restrinja el atributo
