### ISSUE TITLE
Entrega 3: carga de datos

### ISSUE THREAD

**Issue by franmolinam** [IIC2413/Syllabus-2023-2#316]
Hola, no nos queda muy claro aún el poblamiento de las tablas mediante script. Entendemos que hay que hacer un archivo php que se encargue de leer los datos del csv y pasarlos a las tablas correspondientes, pero no entendemos donde correr este archivo. Debería haber un botón en la pagina que se encargue de ejecutar esto y que se poblen las tablas antes de hacer todo el resto de funciones? Gracias!

**Comment by ypne** [comment]
R: No es necesario que se haga por una página, lo pueden hacer por linea de comando.

**Comment by franmolinam** [comment]
Pero se refiere a ejecutar el script desde la linea de comando? Hacer por ejemplo php script.php?

**Comment by ypne** [comment]
R: si
Todas las instrucciones deben estar en el readme

**Comment by franmolinam** [comment]
En ese caso seria necesario tener instalado php para poder correr el script desde la linea de comando?

**Comment by Magda0n** [comment]
> En ese caso seria necesario tener instalado php para poder correr el script desde la linea de comando?

Tengo la misma duda, estoy teniendo muchos problemas de instalación.

**Comment by CarlangaUC** [comment]
Me sumo

**Comment by ypne** [comment]
R: php está instalado
