### ISSUE TITLE
Entrega 3, limpieza de datos

### ISSUE THREAD

**Issue by tperezv2004** [IIC2413/Syllabus-2023-2#317]
Hola, podemos limpiar los datos csv en pandas, osea borrar los duplicados, hacer los CONSTRAIN, etc...? sabemos que hay que hacer un archivo php que se encargue de leer los datos del csv y pasarlos a las tablas

**Comment by ypne** [comment]
R: No, primero deen cargarlos y luego con lo que estimen conveniente post procesas solo los errores
