### ISSUE TITLE
Entrega 3: 3.3 videojuegos

### ISSUE THREAD

**Issue by tomasrodriguez1** [IIC2413/Syllabus-2023-2#319]
Cuando hacen referencia a que hay que poner todos los proveedores de los juegos y las peliculas y series, dan a entender que cada proveedor tiene ciertas suscripciones las cuales hay que mostrar. No obstante, con los datos entregados, no se puede relacionar las suscripciones que existen. Además, viendo los datos, se puede ver que existe una suscripción por videojuego y no por proveedor, lo que no coincide con lo que es pedido. Mi pregunta es: ¿Qué se hace en este caso donde los datos entregados no cumplen con los requisitos pedidos en el enunciado, específicamente para los videojuegos en el punto 3.3?

**Comment by ypne** [comment]
R: Puedes elegir al menos un proveedor por video juego e incluirlo en los datos
