### ISSUE TITLE
Guía 02 SQL

### ISSUE THREAD

**Issue by tnaspee** [IIC2413/Syllabus-2023-2#32]
Hola!
No pude asistir al segundo módulo de la clase del miércoles, por lo que me al tratar de hacer la guía no me quedó muy claro en donde se tiene que correr el jupyter notebook, si en nuestro PC o en el servidor, ya que el servidor me dice que no tiene instalado jupyter, y en mi PC me salen muchos errores a la hora de correr el código.

Muchas gracias por la ayuda.

**Comment by RICARDOOVIEDO** [comment]
Yo te recomiendo ocupar el código de Google Collab! Mucho más fácil

**Comment by tnaspee** [comment]
Ahí si me sirve! Muchas gracias.
