### ISSUE TITLE
Entrega 3: Tipo de encriptación de contraseñas

### ISSUE THREAD

**Issue by IsabellaKPM** [IIC2413/Syllabus-2023-2#320]
Hola. Hicimos el código de Usuarios y acceso pero no sabemos qué encriptación se usó en las contraseñas que están en los datos que nos entregan, la función crypt() pide un salt adicional que si uno lo deja como un string vació sólo entrega *0 para cualquier contraseña y la función hash() pide un formato (como MD5) para encriptar la contraseña, queríamos saber qué tipo de encriptación se usó en las contraseñas que están en los datos que nos dieron (esto para encriptar también el input del usuario y compararlo con la contraseña guardada en la DB).

**Comment by ypne** [comment]
R: Las contraseñas de los archivos están en texto plano
