### ISSUE TITLE
Ayuda entrega 3 - Metodo Post

### ISSUE THREAD

**Issue by cattpuccino** [IIC2413/Syllabus-2023-2#322]
Hola! Para hacer el registro de usuario utilizo un forms en el archivo `views/signup.php` con el método post que redirige a un controlador `includes/signup.inc.php` que recibe los datos de los forms y redirige de ser necesario. 
El problema es que el controlador no está recibiendo los datos de los forms y no sé porqué. Si es necesario puedo adjuntar fotos del código.

**Comment by ypne** [comment]
R: Cuál es la consulta específica?

**Comment by cattpuccino** [comment]
No es una consulta en sí. Aquí se muestra el form en cuestión
![image](https://github.com/IIC2413/Syllabus-2023-2/assets/101208672/9805f394-902b-4872-aca9-8b8513e300fc)
Donde estoy teniendo problemas es en `includes/signup.inc.php`
![image](https://github.com/IIC2413/Syllabus-2023-2/assets/101208672/48ff672e-bbc2-449d-9adc-c3ffd5c53df9)
Donde no está redirigiendo correctamente, esto lo asocio a que no está recibiendo correctamente los datos, pero no estoy 100% segura. 
Agradecería me pudieras ayudar.
PD: Las funciones se encuentran en otro archivo llamado `functions.php` donde ahí se realizan las respectivas consultas.

**Comment by ypne** [comment]
R: Si no tienes un debuger te recomiendo hacer Prints en cada paso crítico para ver dónde está fallando
