### ISSUE TITLE
Entrega3: videojuego preordenes y fechas

### ISSUE THREAD

**Issue by UCFelipeIGS** [IIC2413/Syllabus-2023-2#323]
Hola!

Nosotros hicimos una distincion en los videojuegos en base al atributo preorden true or false or null, y asi filtramos las preordenes. La pregunta viene siendo en que dependiendo de la fecha de inicio, si es que current date es mayor a la fecha de inicio, entonces deberia dejar de ser preorden? Pueden especificar porfavor. 

Muchas gracias!

**Comment by ypne** [comment]
R: en qué archivo?
