### ISSUE TITLE
Entrega 3: Consulta ejecución automática cancelación de suscripción 

### ISSUE THREAD

**Issue by ra-aguilera** [IIC2413/Syllabus-2023-2#324]
Hola, intentando realizar la ejecución automática de la cancelación de suscripción me encontré que puedo hacer uso de crontab, pero al configurar el archivo, no se ejecuta, probe ejecutando el código php directamente desde el servidor y funciona, intenté ver el status de crontab pero no tengo los permisos. Existe alguna otra manera de poder verificar si es que crontab está en funcionamiento?

**Comment by ypne** [comment]
consulta fuera de plazo
