### ISSUE TITLE
Entrega 3: Poblar tablas 

### ISSUE THREAD

**Issue by LunaGarces** [IIC2413/Syllabus-2023-2#327]
hola, con mi grupo (19-20) estamos intentado desde hace bastante pasar lo datos a la base de datos y no hemos podido hacerlo por php, estamos frenados en esa parte, ya que la pagina web la tenemos casi lista, nos falta realizar las consultas, las cuales no podemos hacer si no poblamos las tablas, donde podemos encontrar la información para hacer lo que nos falta?

**Comment by ypne** [comment]
consulta fuera de plazo

**Comment by lfb1206** [comment]
Lamentablemente, este tipo de issues se atendían hasta el lunes, según se encuentra explicitado en el enunciado. Te recomiendo buscar en issues pasadas si se preguntó algo similar, si no, investigar en internet.
¡Mucha suerte!
