### ISSUE TITLE
E3: Extensión plazo

### ISSUE THREAD

**Issue by panchouc** [IIC2413/Syllabus-2023-2#328]
Hola, quería consultar si es posible extender un poco el plazo de la E3 considerando los diversos infortunios a lo largo de este tiempo, como los errores en enunciado, errores y falta de datos entre otros, los cuales dificultan el avance del proyecto. De antemano gracias

**Comment by lolenn10** [comment]
Up

**Comment by carlos12b** [comment]
me sumo, agregando que el control quitó tiempo de trabajo igual

**Comment by ypne** [comment]
Estimados/as
Se dió un mes de plazo para un trabajo estimado de 2 semanas trabajando tranquilo.
Se insistió tanto en el enunciado como en las clases que el trabajo era largo
Cada grupo tiene a 4 personas
El enunciado se explicó en clase (al menos s3), 
Se hizo sesión de consultas en la ayudantía
La gran mayoría de las issues se respondieron en el mismo día
Se hizo sesión presencial de consultas el lunes y miércoles pasado
Se hicieron sesiones de zoom con los grupos que lo solicitaron desde el sábado al martes.
Se entregó el control 3 con varias horas de antelación para que tuviera más tiempo.
Lo "errores" si así se pueden llamar que en su mayoría eran aclaraciones de enunciados fueron corregidos hace tiempo.
Si demuestran que los argumentos esgrimidos los atrasaron y cuanto tiempo podríamos evaluar una extensión.

**Comment by panchouc** [comment]
Estimado si bien tiene razón en lo que comenta. Igual es un poco complicado trabajar de a dos grupos distinto intentando integrar ambas partes, esto tanto en términos de comunicación como coordinación y más aún si es que son dos grupos que son desconocidos. También pasa que como se menciona, este enunciado es complementario al de la entrega 1 y 2, y recién tuvimos acceso a la evaluación y feedback de nuestra entrega 2 el 13 de noviembre. Para esta entrega se nos pide tanto el modelo E/R como las bases de datos en BCNF O 3NF, para lo cual de alguna manera necesitabamos el feedback de la entrega 2 para ver si es que el razonamiento por detrás de cada una de las tablas era el correcto. Considerando que las consultas dependen directamente de como estén estructuradas las tablas, de alguna forma causa inseguridad seguir avanzando cuando no sabemos si el trabajo que hicimos con anterioridad se encontraba correcto, ya que de lo contrario habría que reestructurar todo de nuevo, corrigiendo todo lo de la entrega pasada junto a lo nuevo que se nos pide en esta entrega. Respecto a lo que mencionan mis compañeros, con el tema de la entrega del control pasa que también debemos ser capaces de discernir entre lo importante y lo urgente, y al menos en esos momentos uno se encuentra más centrado en terminar bien el control, hacerlo con tranquilidad para poder entregar un buen trabajo y considerando que el plazo de entrega de esa evaluación era más próximo al de proyecto, uno decide priorizar eso. Respecto a la extensión de plazo, pienso que tampoco debiese ser algo descabellado como semanas, sino un par de días para poder entregar un trabajo de calidad y que cumpla con los estándares esperados y que pueda demostrar que hemos adquirido los conocimientos necesarios. De antemano muchas gracias por su comprensión y sería de mucha ayuda una extensión de plazo.

**Comment by ypne** [comment]
Algunos comentarios
Igual es un poco complicado trabajar de a dos grupos distinto 
intentando integrar ambas partes, esto tanto en términos de comunicación como coordinación y más aún si es que son dos grupos que son desconocidos. 

R: El punto 4 del enunciado dice "Importante: Esta entrega requiere una coordinación entre los grupos que no siempre es sencilla. Se recomienda planificar con anterioridad y utilizar el todo el plazo"

También pasa que como se menciona, este enunciado es complementario al de la entrega 1 y 2, y recién tuvimos acceso a la evaluación y feedback de nuestra entrega 2 el 13 de noviembre. 
R: Esa condición era conocida desde el principio ya que por reglamento hay 15 días hábiles para corregir

Para esta entrega se nos pide tanto el modelo E/R como las bases de datos en BCNF O 3NF, para lo cual de alguna manera necesitabamos el feedback de la entrega 2 para ver si es que el razonamiento por detrás de cada una de las tablas era el correcto. Considerando que las consultas dependen directamente de como estén estructuradas las tablas, de alguna forma causa inseguridad seguir avanzando cuando no sabemos si el trabajo que hicimos con anterioridad se encontraba correcto, ya que de lo contrario habría que reestructurar todo de nuevo, corrigiendo todo lo de la entrega pasada junto a lo nuevo que se nos pide en esta entrega. 

R: El modelo E/R es muy similar a la E2 ya que se asan en los mismos dataset, solo se agregaron 3 atributos

Respecto a lo que mencionan mis compañeros, con el tema de la entrega del control pasa que también debemos ser capaces de discernir entre lo importante y lo urgente, y al menos en esos momentos uno se encuentra más centrado en terminar bien el control, hacerlo con tranquilidad para poder entregar un buen trabajo y considerando que el plazo de entrega de esa evaluación era más próximo al de proyecto, uno decide priorizar eso. 
R: Ese dato tamién era conocido desde el principio y por eso adelantamos la publicación del control

Respecto a la extensión de plazo, pienso que tampoco debiese ser algo descabellado como semanas, sino un par de días para poder entregar un trabajo de calidad y que cumpla con los estándares esperados y que pueda demostrar que hemos adquirido los conocimientos necesarios. De antemano muchas gracias por su comprensión y sería de mucha ayuda una extensión de plazo.
R: 1 mes es un plazo razonable para un trabajo tomando en cuenta que se reciclaba lo de la E2.

Es muy importante que aprendan que los plazos deben cumplirse y que trabajar con personas que no conocen es una práctica frecuente en la industria.
Por otra parte la carga de corrección es alta por lo que entregar más plazo atenta contra los plazos de entrega de las notas las cuales no se mueven.

**Comment by NicoSkritek** [comment]
Buenas tardes,
Me sumo a lo que dicen mis compañeros, ademas de la petición de extension de plazo. Por otro lado, aparte de todo lo que se ha dicho y de las instancias que mencionas @ypne como ayudantías, controles, clases, el enunciado esta super ambiguo y contradictorio en instancias. En el enunciado dice algo y en las issues dice otra. Ademas, como ya se mencionó, la materia de triggers, visualizaciones y transacciones se pasó después de que se publicó el enunciado formalmente. Por ultimo, me parecería más correcto al menos comentarle la situación al profesor y que él mande un anuncio mas que una negación directa y rotunda de la petición sin esta posibilidad.

Saludos!

**Comment by Amegonzale** [comment]
Buenas tardes, 
Sumandome a mis compañeros, queria agregar que las caidas del servidor dificultan el trabajo y avance del proyecto, estando dentro del plazo de entrega.

Saludos

**Comment by tomastrivino** [comment]
<img width="1264" alt="image" src="https://github.com/IIC2413/Syllabus-2023-2/assets/98418205/e1b3d98a-019f-49b2-80d9-4d7be7627666">

Ayuda D:

**Comment by NicoSkritek** [comment]
En efecto, se cae el servidor:
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  remaining connection slots are reserved for non-replication superuser connections

**Comment by panchouc** [comment]
Me pasa lo mismo que a mis compañeros: No se pudo conectar a la base de datos: PDOException: SQLSTATE[08006] [7] connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL: remaining connection slots are reserved for non-replication superuser connections in /home/grupo81/Sites/config/conexion.php:6 Stack trace: #0 /home/grupo81/Sites/config/conexion.php(6): PDO->__construct() #1 /home/grupo81/Sites/home.php(5): require('...') #2 {main}

**Comment by andrius6789** [comment]
Buenas tardes profesor, como usted comentó la entrega2 fue revisada y entregado el feedback hace 9 dias. Este feedback es esencial para realizar gran parte de la tarea pues al no tener seguridad del estado en el que se encontrarian las bases de datos cualquier cambio puede ser desecho en el segundo en que nos percatasemos que en el feedback nos dicen que es lo que esta mal. De este modo es que en la tarea para poder comenzar a trabajar en cualquier cosa se requiere la base de datos y esta al ser entregada 9 dias antes de la entrega final es que por lo menos quedariamos cortos en 5 dias de acuerdo a lo razonado anteriormente por usted. Es asi que " Esa condición era conocida desde el principio ya que por reglamento hay 15 días hábiles para corregir" implica que las entregas estan mal pensadas en terminos de fechas porque este mes desde que se libero el enunciado de la entrega 3 es virtualmente inutil sin un feedback de la entrega 2 (el pilar fundamental de la entrega 3) o bien una ayudantia que explicase que es lo que se deberia haber hecho en la E2 para lograr al 100%. Dado que este ultimo caso no fue asi, me parece solamente logico la prorroga de la entrega 3 considerando que realmente han sido solamente 9 dias de trabajo util.

**Comment by franancic** [comment]
Hola! les copio el anuncio que se acaba de mandar:)
----------------------------------------------------------------------------------------------------------------------------
Hola! 

Vengo con buenas noticias!!! la entrega 3 se ha cambiado para el día 24 de noviembre 23:59, con el fin de que puedan tener un par de días extras para desarrollar la entrega.

He visto todos los mails (no los he podido contestar todavía), y estaré revisando que está pasando con el servidor. 

De todas formas, tal cual se ha indicado en clases y en ayudantías, les recomendamos no dejar toda la entrega para el último día! ya que el servidor suele colapsar.

Espero que esto los alivie un poco, y ánimo con lo que queda!! 

Francisca Ancic
