### ISSUE TITLE
Peticion instalacion pandas en server

### ISSUE THREAD

**Issue by benjahuenchunir** [IIC2413/Syllabus-2023-2#329]
En algunos issues se aclaró que esta permitido utilizar pandas para ciertos casos, sin embargo, no he sido capaz de hacerlo funcionar en el server ya que no se encuentra instalado. Favor instalar pandas para poder utilizarlo.

**Comment by ypne** [comment]
issue fuera de plazo

**Comment by lfb1206** [comment]
Lamentablemente, este tipo de issues se atendían hasta el lunes, según se encuentra explicitado en el enunciado. Te recomiendo buscar en issues pasadas si se preguntó algo similar, si no, investigar en internet.
¡Mucha suerte!

**Comment by benjahuenchunir** [comment]
Gracias, logre solucionarlo.

**Comment by spoblete44** [comment]
Hola, como lo solucionaste?

**Comment by benjahuenchunir** [comment]
Creando un entorno virtual en tu directorio y ahi instalas pandas. Basicamente corre los siguientes comandos en tu directorio principal desde consola:
`wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py --user
echo "PATH=\$PATH:~/.local/bin" >> ~/.bashrc
source ~/.bashrc`

Si despues corres pip --version y te reconoce el comando entonces estas listo
Ya deberias poder instalar pandas u otra libreria con pip install nombre_libreria
