### ISSUE TITLE
Sobre los géneros y subgéneros

### ISSUE THREAD

**Issue by tomastrivino** [IIC2413/Syllabus-2023-2#33]
Hola,
en la pregunta 2.2.3, de la cual adjunto foto:
<img width="944" alt="image" src="https://github.com/IIC2413/Syllabus-2023-2/assets/98418205/3b382299-71ff-461d-a139-be2a6db073a1">

Nos surgió la siguiente duda: ¿ Un subgénero, es estrictamente subgénero de un único género?
Vale decir, "militar" puede ser subgénero de "guerra" y "FPS", o sólo podría serlo de "FPS"? (ejemplo charcha).

Finalmente, ¿podemos asumir que existirán juegos que no tengan subgénero, así como algunos que tengan más de un género y más de un subgénero?

Gracias!

**Comment by martineyz** [comment]
Respecto a esto, cules se consideran los subgeneros de FPS?

**Comment by RICARDOOVIEDO** [comment]
Ustedes tienen que crear los datos, por lo tanto también los géneros y los subgéneros.

**Comment by SantiagoDLCB** [comment]
> No necesariamente un subgénero es estrictamente de un solo género. Por la otra pregunta, dice en el enunciado que cada película tiene al menos un género y subgénero!
> 
> Update: Los profesores decidieron dejar que cada subgénero sea único a cada género!

En ese caso, ya que los profesores definieron que cada subgenero solo puede pertenecer a un genero.  Entonces en la pregunta 1.2.3 cuando se dice 
> Muestre todas las películas que pertenezcan al género ‘Ciencia Ficción’ o a alguno
de sus subgéneros.
Eso significa que ya no es necesario filtrar por los subgeneros de Ciencia ficcion porque ya con solo saber al que pertenece la pelicula sabes que es ciencia ficcion o no?

**Comment by martineyz** [comment]
Se puede conciderar que FPS es un subgénero de shooter o se tiene que considerar FPS como un genero en sí?

**Comment by eiacobelli** [comment]
Sobre esto, si un juego pertenece a un subgénero de FPS, necesariamente pertenece también al género FPS?

**Comment by tomastrivino** [comment]
@hansjkl
