### ISSUE TITLE
Problemas servidor

### ISSUE THREAD

**Issue by tgellonag** [IIC2413/Syllabus-2023-2#330]
Hola, estoy teniendo problemas con el servidor, pareciera que no me deja conectarme a veces, a veces recibo este error, Error: SQLSTATE[08006] [7] connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  remaining connection slots are reserved for non-replication superuser connections.

**Comment by tomas-jackson** [comment]
up, lo mismo nos está ocurriendo a nosotros

**Comment by domingov012** [comment]
mismo

**Comment by cgandarillas2** [comment]
tambien

**Comment by Gcamposbriceno** [comment]
Igual

**Comment by Nicolas413** [comment]
tambien

**Comment by Tamarindinho** [comment]
lo mismo

**Comment by NicoSkritek** [comment]
lo mismo

**Comment by panchouc** [comment]
Me ocurre lo mismo

**Comment by GuilleStanke** [comment]
me pasa lo mismo

**Comment by FernanSali** [comment]
lo mismo

**Comment by llambias** [comment]
mismo problema

**Comment by Srencoret** [comment]
lo mismo

**Comment by Bjnazar** [comment]
Tambien

**Comment by jorgee02** [comment]
+1

**Comment by JaviBLM** [comment]
A mi grupo también le pasa lo mismo

**Comment by Joselabatut** [comment]
x2 :(

**Comment by cebabeltran** [comment]
También

**Comment by maxo2727** [comment]
aca igual

**Comment by Amegonzale** [comment]
+1

**Comment by vicho14** [comment]
sigue caído

**Comment by ItsValkyrie** [comment]
=

**Comment by Paldana99** [comment]
El servidor no esta caído, solo esta colapsado (máximas conexiones alcanzadas). Como ya paso y se notifico/aviso en las entregas anteriores.

**Comment by LunaGarces** [comment]
De todas formas no me permite probar el correcto funcionamiento de mi página, y eso puede ser decisivo a la hora de calcular la nota

**Comment by panchouc** [comment]
![image](https://github.com/IIC2413/Syllabus-2023-2/assets/94400598/39f2b2ef-243a-4ead-acfa-5ae09f891150)
No me deja ni conectarme al postgre

**Comment by NicoSkritek** [comment]
Sea lo que sea que le ocurra no nos permite trabajar

**Comment by Alonsito1911** [comment]
demanda!

**Comment by LunaGarces** [comment]
Sigue el problema por lo que no podemos ingresar a nuestras tablas

**Comment by jorgee02** [comment]
Confirmo. Ingreso un comando y luego no puedo volver a hacerlo en un buen lapso de tiempo.

**Comment by tperezv2004** [comment]
Sigue el problema

**Comment by olguitab** [comment]
Sigue el problema :( no sabemos que hacer!

**Comment by renaa-m** [comment]
Es difícil avanzar cuando el servidor solo funciona por 1 minuto y luego se cae por más tiempo. A menos que exista una alternativa para saber si el código esta correcto sin el servidor.

**Comment by cattpuccino** [comment]
Aquí también estamos con problemas :(

**Comment by spoblete44** [comment]
Sigue dandome problemas y no puedo trabajar con mi grupo

**Comment by jorgee02** [comment]
holaa, el problema persiste

**Comment by caramelnico** [comment]
![image](https://github.com/IIC2413/Syllabus-2023-2/assets/89109742/552b6ac8-3605-459c-abe5-bb2872e8225a)
Quedo buen dia para terminar el trabajo

**Comment by jorgee02** [comment]
Gracias por la extensión de plazo :D
