### ISSUE TITLE
Clases proxima semana

### ISSUE THREAD

**Issue by martineyz** [IIC2413/Syllabus-2023-2#334]
Hola, quería preguntar si esque la proxima semana van a haber clases. En los contenidos del REAMDE dice que no hay clases la última semana pero tambien dice que la penúltima es Bases de datos de grafos couando en realidad fue NoSQL. 
![image](https://github.com/IIC2413/Syllabus-2023-2/assets/127438338/b8ded78e-290a-490f-a3ab-00fc3d1e6596)
Gracias.

**Comment by lfb1206** [comment]
No hay clases la semana que viene.
