### ISSUE TITLE
Plataforma requerida para bases entrega 1

### ISSUE THREAD

**Issue by josegarafulic** [IIC2413/Syllabus-2023-2#34]
Hola!

Estoy un poco perdido y creo que no se ha dado suficiente información a como es que se hacen las tablas requeridas para la primera entrega. También acerca de que plataforma hay que usar para crear las tablas.

Gracias

**Comment by RICARDOOVIEDO** [comment]
Hola! La información de eso se dio en la ayudantia 2, donde dimos información acerca del servidor. Las tablas tienen que crearse adentro del servidor adentro de la base de datos de su grupo de la entrega 1!

Saludos!

**Comment by franancic** [comment]
El ppt de la ayudantía 2 que mencionan arriba es el siguiente: https://github.com/IIC2413/Syllabus-2023-2/blob/main/Ayudantias/Ayudantia%202/ay2-servidor.pdf 
De todas formas se ha habilitado la wiki del curso para que la revisen: https://github.com/IIC2413/Syllabus-2023-2/wiki/Ayudantía-2---Servidor

De todas formas, les recomiendo asistir a las ayudantías que se harán con respecto al proyecto, ya que en esta se muestra presencialmente como se realizan las cosas, además de explicar aspectos claves sobre este.
