### ISSUE TITLE
Límite de reseñas por usuario para cada juego

### ISSUE THREAD

**Issue by hansjkl** [IIC2413/Syllabus-2023-2#35]
Saludos, leyendo el enunciado me surgió la siguiente duda. ¿Puede un usuario crear más de una reseña para el mismo juego?

**Comment by RICARDOOVIEDO** [comment]
Cada usuario puede dejar una única reseña por cada videojuego, pero cada usuario puede hacer reseña a todos los videojuegos existentes! No se si se entiende.

**Comment by hansjkl** [comment]
Sí se entiende! Muchas gracias.
