### ISSUE TITLE
Sobre los titulos de las peliculas y series

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#36]
Hola! Pueden existir 2 peliculas distintas o 2 series distintas con el mismo nombre o en su defecto una pelicula y una serie que se llamen igual?. En caso de poder existir algunas de las anteriores, se pueden crear propiedades extras a las peliculas y las series como un identificador?

**Comment by Paldana99** [comment]
Hola, efectivamente pueden tener el mismo nombre, tal como sucede hoy en día [ejemplo](https://www.imdb.com/list/ls058093044/)
En el enunciado se indica:
> Algunos aspectos son obligatorios, pero esperamos que ustedes creen otras tablas o atributos, de acuerdo a
lo que estimen conveniente para modelar el problema.

**Comment by SantiagoDLCB** [comment]
Entonces en ese caso si creo una tabla para las series y otras para las peliculas y les doy un id, puedo asumir que los id siempre van a ser unicos, en otras palabras, puedo manejar los ids tal que un id de una serie no se va a repetir en una pelicula?

**Comment by RICARDOOVIEDO** [comment]
Ustedes tienen que ver como hacerlo, pero ojo que tienen que ver como manejar bien que esos ids de las series y películas no sean iguales o que haga que la consultas den resultados erróneos!
