### ISSUE TITLE
Atributos mínimos

### ISSUE THREAD

**Issue by VicenteSanMartin** [IIC2413/Syllabus-2023-2#37]
Hola! En el caso de algunos atributos que se piden como mínimos para algunos esquemas, es posible que estos no estén directamente incluidos en dichos esquemas, sino que exteriorizarlos y llevarlos a otras relaciones?

Por ejemplo, los atributos género y subgénero de Pelicula, pueden no estar incluidos en la relación Pelicula y en lugar de eso crear otra relación que relacione los id_pelicula con los diferentes géneros?

**Comment by antoniablanco** [comment]
Hola, es una decisión de ustedes como separan los atributos en las distintas tuplas, lo que es obligatorio es que tiene que poderse realizar las consultas.
