### ISSUE TITLE
1.1 Proveedores y servicios multiples

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#38]
Hola! Nos surgio una duda respecto a los proveedores. Entiendo que los proveedores ofrecen el servicio de streaming, pero lo que no queda claro es si estos pueden ofrecer más de un servicio de streaming. Por ejemplo un proveedor que ofrezca un servicio de streaming de serie y otro aparte de peliculas, o dos packs distintos de peliculas, etc... 

En este contexto un proveedor =1 servicio o un proveedor puede ofrecer multiples de estos?

Por otra parte, se sabe si los proveedores vienen con algun nombre?

**Comment by RICARDOOVIEDO** [comment]
Dice en el enunciado que los proveedores tienen asociado un costo para la suscripción y que ofrecen distintas películas. Por lo tanto, los proveedores ofrecen un servicio único al tener un único costo asociado.

**Comment by SantiagoDLCB** [comment]
Y respecto al nombre de los proveedores, no se menciona que tengan uno pero en la 1.2.1 se pide `Muestre todas las películas y todos los proveedores que las ofrecen` por lo que habria que mostrar algo que los identifique. En este caso se puede asumir que tienen un nombre? y si es así los nombres son unicos o pueden existir dos proveedores con el mismo nombre?

**Comment by franancic** [comment]
Ustedes deben incluir los atributos necesarios para poder realizar las consultas. Pueden identificarlos a través de algún nombre, algún número, etc. Ahi es decisión de ustedes como modelarlo
