### ISSUE TITLE
Consulta servidor para proyecto

### ISSUE THREAD

**Issue by ssilvapinochet** [IIC2413/Syllabus-2023-2#39]
Hola! Me entró una duda sobre que servidor es el que hay que usar para el proyecto, puesto que al probar con el que sale en el enunciado (codd.ing.puc.cl) no nos funciona. Hay que usar el servidor que sale en la ayudantía (bachman)?

Saludos!

**Comment by RICARDOOVIEDO** [comment]
Efectivamente es un error del enunciado! Tienes que ocupar el de la ayudantia! 

Gracias por avisar

**Comment by ssilvapinochet** [comment]
super, gracias!
