### ISSUE TITLE
Juegos y proveedores

### ISSUE THREAD

**Issue by eiacobelli** [IIC2413/Syllabus-2023-2#40]
Hola! Somos grupo par y nos bajó la duda sobre los juegos y sus respectivos proveedores. ¿Pueden los juegos mediante suscripción o gratis tener más de un proveedor?

**Comment by RICARDOOVIEDO** [comment]
Los usuarios pueden tener mas de un proveedor, por lo tanto pueden tener juegos en los distintos proveedores. Los proveedores pueden tener juegos en común

**Comment by RICARDOOVIEDO** [comment]
Si, el proveedor 'X' y el proveedor 'Y' pueden tener el juego 'ABC'
