### ISSUE TITLE
Consulta número 4

### ISSUE THREAD

**Issue by TomasBeckdorf** [IIC2413/Syllabus-2023-2#42]
En la consulta 4 del punto 2.2, ¿se refieren a mostrar el proveedor respectivo de todos los juegos que adquirió Minanda, o a mostrar el proveedor respectivo del usuario Minanda?
En otras palabras, el enunciado es 

Muestre todos los juegos, junto con el nombre del proveedor respectivo del usuario ‘Minanda’.

o

Muestre todos los juegos, junto con el nombre del proveedor respectivo, del usuario ‘Minanda’.
(acá se le agrega una coma justo después de "respectivo")

**Comment by RICARDOOVIEDO** [comment]
La consulta es como esta escrita! Saludos
