### ISSUE TITLE
Duda juegos y sus plataformas

### ISSUE THREAD

**Issue by Josefinafp** [IIC2413/Syllabus-2023-2#43]
Hola! No entiendo si para efectos de esta tarea un videojuego que se juega en una plataforma es distinto al de otra plataforma (por ejemplo, Fifa para PS y Fifa para Xbox, son distintos en cuanto a precios, reseñas, formas de adquisición)?.

Un proveedor puede ofrecer un videojuego para algunas plataformas y para otras no? Por ejemplo, Falabella ofrece Fifa solo para PC y no para otro?

O solo vamos a tener datos de un videojuego (por ej Fifa para PC) y en la base de datos no va a existir el mismo videojuego para otra plataforma?

**Comment by franancic** [comment]
1. Si, es distinto. Por eso dentro de los proveedores se debe mencionar la plataforma por la que se está vendiendo.
2. Si, puede ofrecer un juego en X plataforma pero el mismo juego puede no estar disponible en la plataforma Y.
3. Los datos para esta entrega deben verlo ustedes, pero te recomiendo verlo como que existe un mismo juego en distintas plataformas, y que pueden ser ofrecidos por distintos proveedores.
Por ejemplo, para el juego Fifa, puede ofrecerlo en proveedor X en plataforma PC y Xbox, y puede ofrecerlo el proveedor Y en plataforma PC.

**Comment by Magda0n** [comment]
Es decir, FIFA en PS tiene distinta puntuación que FIFA en Xbox?
