### ISSUE TITLE
Formato entrega 1

### ISSUE THREAD

**Issue by CarlangaUC** [IIC2413/Syllabus-2023-2#44]
Hola buenas!

No me queda claro y lo comente con un ayudante y el profe, el metodo de entrega consiste en crear las tablas en nuestro repositorio asociado para luego especificar tanto las consultas que piden en algebra relacional y SQL en un pdf ? , que hay si creamos otras tablas y con la naturaleza de las variables? Hay que mencionarlas en el pdf? y en cuanto a la base de datos, podremos acceder a ella para probar si nuestras tablas con las consultas funcionan? (asumiendo que las podemos poblar) 

Muchas gracias

**Comment by RICARDOOVIEDO** [comment]
Hola, te explico. Ustedes tienen que crear las tablas que crean necesarias para el proyecto y para poder realizar las consultas que les pedimos. Ustedes en su informe tienen que poner **todas** las tablas que ustedes piensen necesarias con sus respectivos atributos, y después crear y subir esas tablas al servidor a través de la terminal como se explico en la ayudantía! Después tienen que poblar las tablas para ver si sus consultas realmente funcionan en SQL.
Espero que se entienda.

**Comment by CarlangaUC** [comment]
Holi! , Como las podemos poblar? Hay alguna base de datos publica que podamos ir testeando?

**Comment by RICARDOOVIEDO** [comment]
Eso esta explicado en la ayudantía 2! Revisa el pdf

**Comment by CarlangaUC** [comment]
Holi, se explica como poblar tablas pero no encuentro ningun archivo csv o demas para poder realizar eso

**Comment by RICARDOOVIEDO** [comment]
Es que para esta vez ustedes tendrán que poblar las tablas de manera manual, es decir uno por uno! Hay un comando que haces que puedas crear manualmente!
