### ISSUE TITLE
Consulta 1 grupo par

### ISSUE THREAD

**Issue by martineyz** [IIC2413/Syllabus-2023-2#45]
Es valido una consulta que muestre varias columnas del estilo 
juego_1,proveedor_a
juego_1,proveedor_b
juego_2,proveedor_a
o tiene que ser el juego y en la misma file todos sus proveedores.

**Comment by RICARDOOVIEDO** [comment]
Las consultas saldrán asi siempre. No entiendo a que te refieres con el juego y en la misma fila todos sus proveedores

**Comment by martineyz** [comment]
algo asi como
juego_1,"proveedor_a,proveedor_b"

**Comment by RICARDOOVIEDO** [comment]
En realidad podrías realizar una consulta que haga que el resultado sea asi, pero en general te va a dar como lo pusiste al principio! Igualmente depende de como realices tus tablas!
