### ISSUE TITLE
2.2.2: Uso de "count" en álgebra relacional

### ISSUE THREAD

**Issue by hansjkl** [IIC2413/Syllabus-2023-2#47]
Hola, tengo una duda respecto a como realizar la siguiente consulta en álgebra relacional:

"Muestre todos los juegos con al menos 5 reseñas positivas"

Mi duda es si sería posible utilizar la función count de SQL para escribir esto en álgebra lineal, o si únicamente podemos utilizar los operadores presentados en la clase de álgebra relacional. Hago la pregunta porque, habiendo hablado con un ayudante, representar esto en álgebra relacional parece demasiado complicado.

**Comment by RICARDOOVIEDO** [comment]
La verdad no se si existe una función equivalente de count en álgebra relacional, podrías buscar en internet.

Pero no es válido ocupar cosas de sql en álgebra relacional si es que no existen.

**Comment by UCFelipeIGS** [comment]
Seria legal crear un atributo en la tabla de videojuegos con la cantidad de reseñas positivas y negativas? Luego, filtrar en base a eso
