### ISSUE TITLE
Peliculas accesibles

### ISSUE THREAD

**Issue by lfarr1110** [IIC2413/Syllabus-2023-2#48]
Con respecto a la consulta 4, donde hay que mostrar las peliculas que tiene acceso un usuario. Una pelicula que es ofrecida por un servicio de streaming que el usuario tiene contratado, pero se debe arrendar, se considera que el usuario tiene acceso a ella si es que **no** la ha pagado?
gracias

**Comment by RICARDOOVIEDO** [comment]
No entendí, es el caso cuando el servicio de streaming tiene una película pero esa película hay que pagarla aparte??

**Comment by lfarr1110** [comment]
eso mismo, en ese caso se considera que el usuario tiene acceso a ella?

**Comment by RICARDOOVIEDO** [comment]
No tendría acceso, ya que necesitas pagar la película a pesar de haber pagado la suscripción!
