### ISSUE TITLE
Postgresql y server

### ISSUE THREAD

**Issue by UCFelipeIGS** [IIC2413/Syllabus-2023-2#49]
Holaa!
Una duda respecto a la plataforma y los comandos que mencionaban en la ayudantia, como psql, etc. En donde se supone que debo correr dichos comandos, en la terminal? Ademas, cuantas aplicaciones debo descargar, por ejemplo hay que descargar Postgresql o Filezilla.

En resumen estoy medio perdido en el procedimiento mismo de conectarse y de donde escribir el codigo de sql, asi que feliz si pueden explicar mas a detalle, muchas gracias!!

**Comment by RICARDOOVIEDO** [comment]
Hola! Está detallado en la ayudantía, pero básicamente tienes dos opciones donde subir tus archivos. Una es en Github (que no recomiendo) y otra es FileZilla. FileZilla tienes que descargarlo.

Postgresql quizás tengas que descargarlo. Muchas veces ya viene incluido en tu computador. Si es que no, creo qué hay una wiki del github donde explican cómo instalarlo. 

Por último, psql de corre adentro de la terminal después de haber entrado  al usuario de tu grupo de bachman@...

Ojalá se haya entendido!

**Comment by franancic** [comment]
Te recomiendo ver el [pdf de la ayudantía 2](https://github.com/IIC2413/Syllabus-2023-2/blob/main/Ayudantias/Ayudantia%202/ay2-servidor.pdf) y la [wiki del curso](https://github.com/IIC2413/Syllabus-2023-2/wiki).
