### ISSUE TITLE
Path relativo para copiar CSV a tabla creada en el servidor

### ISSUE THREAD

**Issue by franfonte** [IIC2413/Syllabus-2023-2#50]
Cual es el path relativo de los archivos dentro del servidor? ya que he tratado diversas combinaciones y siempre recibo el mismo error "No such file or directory"

**Comment by RICARDOOVIEDO** [comment]
La verdad para esta entrega la idea es que creen los datos manualmente, pero si quieren hacerlo con archivos csv tienen que poner los datos adentro del servidor, yo lo que hacía era crear una carpeta, y con eso copiaba el path relativo que me daba.

Ojalá que sirva

**Comment by franfonte** [comment]
Esque tendria que subir como 400 lineas a mano una por una, en filezilla me aparece lo siguiente:
<img width="598" alt="Captura de pantalla 2023-08-31 a la(s) 19 14 12" src="https://github.com/IIC2413/Syllabus-2023-2/assets/111889435/b7e1b8a3-71ca-4b49-b9ef-e3be9668b005">
y de ruta trate de usar:
<img width="185" alt="Captura de pantalla 2023-08-31 a la(s) 19 15 49" src="https://github.com/IIC2413/Syllabus-2023-2/assets/111889435/2299d7d7-be0a-4623-ae11-7886d3c79e84">
pero esa ruta no sirve, tienes alguna idea de que puede ser?

**Comment by RICARDOOVIEDO** [comment]
Es que no es necesario crear 400 datos para cada tabla, solo los suficientes para que las consultas funcionen. Para la próxima entrega se verá el tema de los csv.

En todo caso, quizás el path falta que lo pongas entre comillas o algo por ese estilo, porque debería estar funcionando!

**Comment by franancic** [comment]
Hola! te recomiendo ver en la wiki del curso la sección correspondiente a [Importar datos en Postgres](https://github.com/IIC2413/Syllabus-2023-2/wiki/Ayudantía-2---Servidor#importar-datos-en-postgres)

**Comment by franfonte** [comment]
Gracias, lei la wiki y puse el path relativo correcto
<img width="542" alt="Captura de pantalla 2023-09-04 a la(s) 15 05 23" src="https://github.com/IIC2413/Syllabus-2023-2/assets/111889435/98841fb8-91c8-459a-825a-89d5a7335a17">
<img width="572" alt="Captura de pantalla 2023-09-04 a la(s) 15 05 39" src="https://github.com/IIC2413/Syllabus-2023-2/assets/111889435/52c4e9e2-e22c-46d7-b181-b8a50f38f7c6">
Ahi se puede ver mi carpeta en el servidor y el codigo del terminal, se te ocurre que puede estar mal?

**Comment by adribastiasm** [comment]
Hola, a nosotros nos pasa lo mismo, cómo se puede arreglar?
