### ISSUE TITLE
Suscripciones y arriendos películas. (Grupo Impar)

### ISSUE THREAD

**Issue by josegarafulic** [IIC2413/Syllabus-2023-2#51]
Tenemos varias dudas acerca de las suscripciones y arriendos de las películas:
1- Todas las películas tienen suscripción?
2- El dato de suscripción en la base de datos debería ser un "si/no" o un "Netflix/Hbo..."? 

Muchas gracias, creo que el enunciado es un poco confuso y no abarca estos detalles

**Comment by RICARDOOVIEDO** [comment]
Para la primera pregunta, confirmaré con los profesores.

Con respecto a la base de datos, eso dependerá de cómo ustedes plantean las tablas de su base de datos! Saludos

**Comment by VicenteSanMartin** [comment]
Hola! En relación a esto mismo, nos surgió la duda sobre que ocurría con las películas que se debe pagar un monto extra para poder verlas: cualquier usuario puede verlas al pagar el monto? O por el contrario, también debe tener acceso a la película mediante la suscripción a algún proveedor?

Con lo primero me refiero a si aquellas películas con monto extra no están incluidas en ningún plan de suscripción

**Comment by RICARDOOVIEDO** [comment]
Todas tienen que que estar incluidas en algún proveedor! En el enunciado sale en la parte de los proveedores!

**Comment by VicenteSanMartin** [comment]
Disculpa, no nos queda claro. Si todas las películas están incluidas en algún proveedor, entonces la consulta 6 del grupo impar no tendría sentido, ya que esta pide "mostrar la suma de dinero que cada usuario ha gastado en películas no incluidas en planes de suscripción".

En ese caso, lo lógico sería que para ver las películas con monto extra el usuario también debe tener acceso a la película mediante la suscripción a algún proveedor, por lo que habría que reformular la consulta 6

**Comment by RICARDOOVIEDO** [comment]
Las películas que tienen que pagar, están adentro del proveedor pero no dentro de la suscripción del proveedor, entonces tienes que pagar la suscripción a tal proveedor y además pagar por la película, no sé si ahí se entiende.

**Comment by VicenteSanMartin** [comment]
Ahora se entiende. Muchas gracias!
