### ISSUE TITLE
subgeneros y pregunta 3 Grupo Impar 

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2413/Syllabus-2023-2#52]
En la issue #33   anuciaron para los grupos pares:  ` Los profesores decidieron dejar que cada subgénero sea único a cada género!`

En este caso eso aplica tambien para los grupos impares? Y si es asi en la pregunta 1.2.3 cuando se dice
```
Muestre todas las películas que pertenezcan al género ‘Ciencia Ficción’ o a alguno
de sus subgéneros.
```
Puede existir un caso en que una pelicula pueda pertenecer a 2 generos y a un 1 solo subgenero?. Tal que pertenezca al genero A y B y a un subgenero C, siendo C un subgenero de A. De manera que la pelicula no pertenezca a ningun subgenero de B. O necesariamiente si pertenece a un genero tambien debe de pertenecer a algun subgenero de este?

**Comment by RICARDOOVIEDO** [comment]
Si, aplica lo mismo para los grupos impares. 

Y con los casos que planteaste, el primer caso es el correcto! Es decir, puede pertenecer a dos géneros y solo a un subgénero de A.
