### ISSUE TITLE
Consulta datos grupo par

### ISSUE THREAD

**Issue by adribastiasm** [IIC2413/Syllabus-2023-2#53]
Hola! Quería saber si hay una cantidad mínima o máxima de tuplas necesarias para el trabajo. Por ejemplo en el caso de videojuegos, hay una cantidad mínima de juegos que tengamos que ingresar?

**Comment by RICARDOOVIEDO** [comment]
La cantidad es la necesaria para que en cada consulta salga una tabla no vacía, es decir, mínima una tupla por consulta. Yo recomiendo que sean 3 tuplas para que se aseguren que la consulta realmente funciona.

Saludos
