### ISSUE TITLE
Nombres usuarios proyecto

### ISSUE THREAD

**Issue by Mcroquevielle** [IIC2413/Syllabus-2023-2#54]
Hola!! Quería saber si se puede asumir que los nombres de usuarios y los nombres de los proveedores no se repiten

**Comment by RICARDOOVIEDO** [comment]
Los nombres de usuarios y proveedores se pueden repetir, así que no pueden asumir eso!

Saludos!

**Comment by RICARDOOVIEDO** [comment]
Los nombres de usuarios y proveedores se pueden repetir, así que no pueden asumir eso!

Saludos!
