### ISSUE TITLE
grupo par - videojuegos y proveedores

### ISSUE THREAD

**Issue by DiegoAHA** [IIC2413/Syllabus-2023-2#56]
Hola!
¿Puedo asumir que si un proveedor vende juegos de cierta plataforma (por ejemplo PC) y tengo un juego que es de esa misma plataforma, entonces el proveedor vende ese juego?

**Comment by RICARDOOVIEDO** [comment]
Un proveedor vende de varias plataformas, no solamente vende de una única plataforma, por lo tanto no puedes asumir eso!

Saludos
