### ISSUE TITLE
Duda sobre proveedores y suscripciones de servicios de Streaming

### ISSUE THREAD

**Issue by ibgarrido** [IIC2413/Syllabus-2023-2#58]
En el enunciado dice "pueden suscribirse a uno o mas servicios de streaming ofrecidos por los diferentes proveedores". (En el apartado usuarios). Esto quiere decir que cada proveedor puede tener distintos planes de servicios de streaming?

Saludos.

**Comment by franancic** [comment]
Efectivamente

**Comment by blampasona18** [comment]
Hola! Si cada proveedor puede tener distintos servicios de streaming, el costo de suscripción es del proveedor o de cada servicio? Lo lógico sería q esté asociado a cada plan de servicio, pero en el enunciado se entiende que el costo es por proveedor

**Comment by blampasona18** [comment]
Dentro de esto mismo, para las series es lógico que un usuario deba estar suscrito a un proveedor para poder verlas, ya que no hay formato de arriendo (vienen incluidas en un plan si o si). Pero para las películas, un usuario puede pagar una película sin estar suscrito a un proveedor?

**Comment by rmezaa** [comment]
Pero en la issue 38 dice que cada proveedor solo tiene un plan de acuerdo al enunciado, no se están contradiciendo?
https://github.com/IIC2413/Syllabus-2023-2/issues/38#issuecomment-1698457055
