### ISSUE TITLE
Duda enunciado Control 1 - preguntas 1b y preguntas 2 a 6

### ISSUE THREAD

**Issue by cebabeltran** [IIC2413/Syllabus-2023-2#6]
Hola! Tengo unas consultas con el control 1:

- En la pregunta 1b, cuando dice "en términos de cantidad", ¿se refiere a que hay que indicar cuántas duplas resultan, al igual que en la pregunta anterior, sin incluir nada más?
- En las preguntas 2 a 6, cuando dice "liste todos...", ¿Sólo hay que dar el nombre de los autores, sin necesidad de incluir desarrollo ni la fórmula de álgebra relacional para cada caso?

Gracias!

**Comment by lfb1206** [comment]
Hola!

Sobre la pregunta 1b, claro, hay que responder cuantas tuplas resultan.
Sobre la pregunta 2 a 6 se debe realizar la consulta en álgebra relacional que liste lo solicitado.

¡Mucha suerte!
