### ISSUE TITLE
Grupo par, consulta 1 

### ISSUE THREAD

**Issue by TomasBeckdorf** [IIC2413/Syllabus-2023-2#60]
"Muestre todos los juegos y los proveedores que los ofrecen."

Ahí tenemos que especificar todos los atributos de los juegos? (título, puntuación, clasificación (PG13), fecha de lanzamiento y uno o más géneros y subgéneros.), o solamente con el nombre del juego está bien

**Comment by tomastrivino** [comment]
Lo otro, consultar si podemos asumir que el nombre del juego será único (no podrá haber dos juegos con el mismo nombre).

**Comment by TomasBeckdorf** [comment]
Hola por favor si pueden responder esta Issue
