### ISSUE TITLE
Grupo par (Consulta Reseñas)

### ISSUE THREAD

**Issue by ignaciadelacuadraf** [IIC2413/Syllabus-2023-2#61]
Hola! para la consulta que nos piden "Mostrar todos los juegos con al menos 5 reseñar positivas", queriamos saber si es posible realizar un atributo a los videojuegos con la cantidad de reseñas positivas, ya que realizar la consulta con álgebra relacional resulta muy complejo y difícil. O si es posible utilizar alguna función similar al count. 
Muchas gracias!!

**Comment by Paldana99** [comment]
Pueden crear todos los atributos que consideren necesarios, por lo que si desean seguir de esta forma pueden sin problema.
