### ISSUE TITLE
Grupo Par (Plataforma)

### ISSUE THREAD

**Issue by ignaciadelacuadraf** [IIC2413/Syllabus-2023-2#62]
Hola!! Tenemos una duda cin respecto a las plataformas... 
¿Un juego pertenece a una plataforma (ej: un juego tiene formato Wii y formato XBox), ó un proveedor pertenece a una plataforma?
Porque en el enunciado salen varios puntos con respecto a estas:
**Usuario:**
-- La plataforma tambien mantiene un registro de las horas de juego de los usuarios en cada juego y un registro historico de las subscripciones y su estado (activa, inactiva).
**Preordenes:**
--  Cuando un usuario adquiere un juego mediante pre orden esto debe quedar registrado para que pueda quedar visible para siempre en la plataforma (a que se refiere con estar visible o quedar registrado)
**Proveedores:**
-- Los proveedores tienen nombre y plataforma. (concepto de plataforma difuso, no deberia estar asociado a videojuego ya que un juego esta en plataforma Xbox, PS, PC, etc.)

Feliz si nos pueden explicar un poco más a que se refiere con plataforma y como se integran a estas funcionalidades. 
Gracias!

**Comment by Paldana99** [comment]
Hola! 
- Un proveedor puede vender en varias plataformas. Y un videojuego puede estar presente en varias plataformas a la vez.
- Cuando se realiza una preorden (solo pago único) debe quedar registrado que ese usuario realizo una preorden de por vida) 

Espero que quede más claro
