### ISSUE TITLE
Duda Enunciado y Estructuracion

### ISSUE THREAD

**Issue by UCFelipeIGS** [IIC2413/Syllabus-2023-2#63]
Hola!
Tenemos dudas respecto a ciertas partes del enunciado.
VideoJuegos.
"Los juegos de pago unico pueden encontrarse en distintos proveedores y pueden no tener el mismo precio."
**En el caso de tener una tabla acerca de los metodos de pago de forma general (sin especificar tabla suscripcion, pago unico, etc) sino que tenerlo de atributo de tal tabla, como se podria linkear a proveedor en el caso que tal atributo sea igual a pago unico siendo que no todos van a estar conectados con proveedor pero si con la compra anterior**

Preordenes:
"Los Juegos de pago unico pueden encontrarse en distintos proveedores y pueden no tener el mismo precio."
**Duda: Se suma un poco a la integracion de la duda 1)**

Usuarios:
"pueden tener una cantidad arbitraria de juegos en los distintos
proveedores en los que tienen cuenta, ya sean de pago unico o por suscripcion"
**No entiendo a lo que se refiere, un usuario puede tener varios videojuegos??**

Muchisimas gracias de antemano,

**Comment by Paldana99** [comment]
Hola!
- Con respecto al pago, deben ver que un pago esta relacionado con un usuario, juego, proveedor, tipo de pago y precio. Por lo que pueden hacer una relación con id entre los implicados. Y esta relación se puede hacer en varias tablas, dándole un id a cada pago. 
- Lo mismo, una preorden siempre sera de tipo pago único (por enunciado) y implica a un usuario, juego y proveedor. 
- Si, un usuario puede tener cuentas en vario de los proveedores. Y en cada proveedor este puede tener varios videojuegos (numero arbitrario)

**Comment by UCFelipeIGS** [comment]
muchisimas gracias!
