### ISSUE TITLE
Duda PSQL \c grupoXXe1 y Filezilla

### ISSUE THREAD

**Issue by cebabeltran** [IIC2413/Syllabus-2023-2#64]
Hola! Tengo una duda con respecto a como funciona lo de desarrollar y subir las tablas creadas en SQL. Tengo entendido que una vez iniciado el servidor y con el comando \c grupoXXe1, se empiezan a crear las tablas ahí. Mi duda es, ¿dónde se guarda esta información? ¿Hay que subirla manualmente con Filezilla o se guardan directamente en el servidor? También se menciona en el enunciado que se suben los documentos a la carpeta "/Entrega1, donde XX es el número de grupo"; ¿Esta carpeta hay que crearla? no entiendo si se refiere a la carpeta de grupo (grupoXX) o si la carpeta de entrega debe llevar el número de grupo.
Gracias!

**Comment by Paldana99** [comment]
Hola!
Cuando ingresas a PostgreSQL a través del comando `psql` luego de haber hecho ssh, toda la informacion se guarda en el servidor. Por lo que no es necesario hacer nada con respecto a eso.

La carpeta "/Entrega1" se debe de crear en el home de tu usuario. Es decir cuando ingresas con `ssh` si ejecutas `ls` para listar todos los archivos y carpetas deberia aparecer como:
-Entrega1
-Sites
