### ISSUE TITLE
Duda sobre consultas grupos impar

### ISSUE THREAD

**Issue by tgellonag** [IIC2413/Syllabus-2023-2#68]
Cuando nos piden en la primera consulta (1. Muestre todas las peliculas y todos los proveedores que las ofrecen) tenemos que mostrar los titulos de las peliculas o toda la informacion de las peliculas.

**Comment by RICARDOOVIEDO** [comment]
Eso es parte del desafío de las consultas, saber que es lo que piden!

Saludos
