### ISSUE TITLE
Grupo par: Videojuegos, plataformas y proveedores

### ISSUE THREAD

**Issue by Magda0n** [IIC2413/Syllabus-2023-2#69]
Hola!

En el enunciado dice:
<img width="556" alt="image" src="https://github.com/IIC2413/Syllabus-2023-2/assets/105729405/16631900-8fa3-47f0-99b6-6e5fd1dd2b34">
Creo que esto no tiene sentido: ¿Cada proveedor tiene solo una plataforma? ¿O más de una? Si tiene más de una, ¿Significa que TODOS los juegos que vende este proveedor los vende para TODAS esas plataformas? Es decir, si tiene plataformas Xbox y PS, todos los juegos que vende tienen plataforma Xbox y PS.
Si no es así, y sólo depende de cada juego, no veo porque proveedor tendría un atributo plataforma.

**Comment by RICARDOOVIEDO** [comment]
La issue #62 Creo que responde tu pregunta de buena manera. 

Saludos
