### ISSUE TITLE
Libro.editor y relacion entre Libro y Publicacion

### ISSUE THREAD

**Issue by Nicolas413** [IIC2413/Syllabus-2023-2#7]
Los editores de un libro se consideran como "autores" del libro?

**Comment by Nicolas413** [comment]
Con respecto relacion entre Libro y Publicacion tengo una duda en como se relacionan estas dos tablas de datos?

**Comment by panchouc** [comment]
Respecto a esto, tengo una duda sobre a que hace referencia el atributo de editor y los números que aparecen.

**Comment by antoniablanco** [comment]
Hola, los editores y autores de libros no son necesariamente iguales. Son dos atributos que pueden o no ser diferentes para el mismo libro. Un autor puede ser editor de otro libro, el editor hace referencia al id_autor.
