### ISSUE TITLE
Reseñas y plataforma Videojuegos Grupo Par

### ISSUE THREAD

**Issue by TomasAltermatt** [IIC2413/Syllabus-2023-2#70]
De lo que entiendo un videojuego puede estar en más de una plataforma, pero tengo la duda de si las reseñas para un juego son o no independientes de su plataforma.

Por ejemplo si 2 usuarios hacen una reseña para FIFA, en el que uno lo tiene para PS5 y el otro para Xbox, ¿se registran ambas como reseñas para FIFA, o queda una reseña FIFA-PS5 y una reseña FIFA-Xbox?

**Comment by RICARDOOVIEDO** [comment]
La reseña es para un juego en particular, por lo tanto hay que tomar en cuenta la plataforma en la que el juego se esta jugando. Igual ahi depende como plantees tu modelo de tablas.

**Comment by MariaJoseSilva** [comment]
Hola!
Respecto a esta pregunta y a la consulta  _2 Muestre todos los juegos con al menos 5 reseñas positivas_ del enunciado, en este caso es relevante la plataforma o solo se considera el nombre del juego?
Por ejemplo, si FIFA-PS5 tiene 2 comentarios positivos y FIFA-Xbox tiene 3 comentarios positivos, entraría FIFA dentro de los resultados de la consulta?
