### ISSUE TITLE
Duda grupo impar sobre series

### ISSUE THREAD

**Issue by LunaGarces** [IIC2413/Syllabus-2023-2#72]
hola, para generar la base de datos de series, se debe por serie colocar la cantidad de capítulos y temporadas en total, o se debe hacer por cada capítulo especificar su información, es decir una fila por capitulo?

**Comment by RICARDOOVIEDO** [comment]
Eso es parte del desafío de la entrega, es decir, ver si es que te lo piden en el enunciado y si es asi, como hacer las tablas para que tenga toda la información.

Saludos
