### ISSUE TITLE
duda grupo impar películas (géneros y subgéneros)

### ISSUE THREAD

**Issue by LunaGarces** [IIC2413/Syllabus-2023-2#73]
tengo una duda con la consulta 3, Muestre todas las películas que pertenezcan al genero ‘Ciencia Ficción’ o a alguno de sus subgéneros, se refiere a tomar todas las películas de ciencia ficción con un subgénero especifico, o un genero puede ser un subgénero de otra película? 
puedo tener películas que su genero sea ciencia ficción y otras que su sub genero sea ciencia ficción? o a que se refieren con la consulta?

**Comment by RICARDOOVIEDO** [comment]
Las películas tienen géneros y/o subgéneros. Si es que la película es de género ciencia ficción o  alguno de los subgéneros de ciencia ficción es el subgenero se alguna película, entonces entra en la consulta.

**Comment by maxo2727** [comment]
Hola! Con respecto a esta pregunta:
1.- Creo que la pregunta anterior se refería a que si algún género puede ser el subgénero de otra película, y viceversa.
2.- Todos los géneros tendrán subgéneros específicos, o puede que éstos subgéneros se repitan entre otros géneros?

**Comment by RICARDOOVIEDO** [comment]
No, un género no puede ser subgénero.

Con respecto a la segunda pregunta, ya está respondida en más de una issue, así que les recomiendo revisarlas!
