### ISSUE TITLE
Duda sobre consultas que el esquema debe soportar

### ISSUE THREAD

**Issue by panchouc** [IIC2413/Syllabus-2023-2#75]
Hola, tengo una duda sobre el enunciado, ya que dice que debemos escribir, la primera, segunda y tercera consulta en álgebra relacional y SQL, pero que pasa con las otras 3? Tenemos que hacerlas en SQL? O que tenemos que hacer en específico con esas consultas que se menciona. Esto, pues con el enunciado no queda claro cuando dice que el esquema debe soportar tales consultas, pero no se indica a si se deben ejecutar y adjuntar o algo por el estilo.

**Comment by panchouc** [comment]
Además, respecto a las consultas en SQL, debemos poner sobre como se haría la consulta? O también quizás poner un pantallazo de lo que obtenemos al ejecutar cierta consulta con los datos que tenemos en el servidor.

**Comment by RICARDOOVIEDO** [comment]
Hola! Solo tienes que hacer las primeras 3 consultas en SQL y álgebra relacional, y las otras 3 tienen que ser soportadas por tu esquema, es decir, por las tablas y los atributos de esas tablas. No es necesario mostrar el resultado en el informe, pero lo que sí se recomienda que hagan, es probar las consultas adentro del servidor en la terminal.

Espero que se haya entendido.

**Comment by panchouc** [comment]
Hola! Si muchas gracias, se entendió perfecto.
