### ISSUE TITLE
Grupo Par - Videojuegos y formas de pago

### ISSUE THREAD

**Issue by fvidalf** [IIC2413/Syllabus-2023-2#76]
Hola!

Acerca de los videojuegos, leyendo el enunciado me queda una duda: ¿Los juegos son necesariamente de un solo tipo de pago? Desde el enunciado y la issue #40 se entiende que tanto juegos de suscripción, como de pago fijo, pueden hallarse en más de un proveedor. Pero, ¿puede un juego ser de más de un tipo de pago a la vez? ¿Puede existir el juego "A" como de suscripción en un proveedor, y como de pago en otro?

Si fuese así, ¿podría además un proveedor ofrecer el mismo juego "A", con dos modalidades de pago distintas?

**Comment by RICARDOOVIEDO** [comment]
Con respecto a la primera parte de tu pregunta, si puede ser así. Puede existir un juego con distintos tipos de pagos en distintos proveedores. 

Lo segundo es incorrecto, no puede el mismo proveedor ofrecer dos tipos de pagos para el mismo juego.

Saludos!
