### ISSUE TITLE
Videojuegos y sus plataformas

### ISSUE THREAD

**Issue by eiacobelli** [IIC2413/Syllabus-2023-2#77]
Hola! Se mencionó que una reseña al mismo juego en 2 plataformas son distintas, siendo que en el enunciado dice que las reseñas solo se escriben sobre un videojuego, y no sobre un videojuego en cierta plataforma. 
Me baja la duda si entonces se considera que 2 videojuegos en distintas plataformas pueden diferir en sus otras características, como por ejemplo su puntuación, clasificación y/o fecha de lanzamiento.

**Comment by Paldana99** [comment]
El mencionar que son independientes quiere decir que si queremos hacer un análisis global de un juego. Por ejemplo cuantas reseñas positivas tiene, este no dependerá del proveedor.

**Comment by eiacobelli** [comment]
Mi pregunta era sobre las plataformas, no los proveedores. No me queda claro si se considera que, por ejemplo, SIMS en PlayStation y SIMS en PC tienen las mismas características (puntuacion, clasificación, etc), ya que según la issue #70 si tienen reseñas distintas.

**Comment by Paldana99** [comment]
Perdona, me confundí. 
Puedes considerar que las demás características serán compartidas.
