### ISSUE TITLE
Consulta grupos par, "registro histórico de las subscripciones" en usuarios.

### ISSUE THREAD

**Issue by Nicolas413** [IIC2413/Syllabus-2023-2#79]
Hola tengo una duda a que se refiere que haya un registro historico, esto debe ser tipo el usuarios pago los meses junio, julio, septiembre de tal año (En el contexto de los juegos de pago mensual") o ¿es referente a la primera vez que compro el juego?.

**Comment by Paldana99** [comment]
En contexto a los pagos mensuales debe de haber un registro mes a mes. Para el pago único, sola la fecha en que se realizo.
