### ISSUE TITLE
Fecha de entrega

### ISSUE THREAD

**Issue by rmezaa** [IIC2413/Syllabus-2023-2#83]
Hola! Para corroborar, la entrega es el sábado 16/09 a las 23:59 como dice el enunciado cierto? Que en el README del Syllabus dice que es para el 15-09.

**Comment by RICARDOOVIEDO** [comment]
Sisi, la fecha del enunciado es la qué hay que seguir. Las fechas del ReadMe son tentativas.

**Comment by TomasAltermatt** [comment]
Hola, respecto a esto mismo, en el enunciado dice que la entrega es "antes del Sábado 16 de septiembre a las 23:59". Mi duda es si esto se refiere que tuvimos hasta las 23:59:59 o 23:58:59? 

Pregunto porque hoy tuve muchos problemas de internet subiendo mi PDF definitivo y se entregó a las 23:59:53, por lo que quería saber si cuenta como dentro del plazo.
