### ISSUE TITLE
Duda consulta 6 grupo impar

### ISSUE THREAD

**Issue by Calculous5** [IIC2413/Syllabus-2023-2#84]
Para poder encontrar el monto total de cada usuario, se puede asumir que podemos realizar operaciones aritméticas o funciones como SUM, COUNT, o se debe definir el monto dentro de una tabla especifica?

**Comment by RICARDOOVIEDO** [comment]
Como planteas las consultas depende completamente como tu haces las tablas de tu esquema. Ahi tienen que ver ustedes como grupo. Con respecto a lo de realizar operaciones aritméticas o las funciones, si es que fueron enseñadas en clases pueden ser utilizadas.

Saludos

**Comment by Calculous5** [comment]
Muchas graciaas
