### ISSUE TITLE
Como subir la entrega 1 a Bachman

### ISSUE THREAD

**Issue by JaviL13** [IIC2413/Syllabus-2023-2#85]
Queria consultar como subimos la entrega 1 a bachman, actualmente la tenemos dentro en el repositorio de nuestro proyecto, dentro de la carpeta Entrega 1. Pero no estamos seguro de si debe estar así o dónde ponerlos de manera adecuada. 

Gracias y saludos

**Comment by RICARDOOVIEDO** [comment]
Para aclarar, la carpeta se tiene que llamar **"Entrega1"** sin espacio y con la E mayúscula.

Efectivamente tu entrega pdf tiene que estar adentro de esa carpeta con cualquier nombre que señale cuál es su grupo y sus nombres.

La entrega tiene que ser adentro del servidor como se muestra en la ayudantía.

**Comment by Rvcumsille** [comment]
Pero si dentro de la carpeta Entrega1 esta nuestro repositorio privado, y el archivo pdf esta dentro de la carpeta del repo, eso esta bien, que no entendi como dejarla fuera de la carpeta del repo. Gracias
