### ISSUE TITLE
Base de Datos equivocada

### ISSUE THREAD

**Issue by CValenzuela2** [IIC2413/Syllabus-2023-2#86]
Hola, soy del grupo 26 y en vez de agregar todos los datos en la base grupo26e1 lo hicimos en la base grupo26. Es muy grave o tenemos que traspasar todos los datos de una base a otra? 

Si lo último es el caso, ¿cómo se hace para importar datos de una base a otra?

**Comment by RICARDOOVIEDO** [comment]
La verdad es que si tienen que cambiarlos datos a la base de datos de grupo26e1. No tengo conocimiento de como importar datos de una base a otra, creo que tendrían que hacer todo de nuevo, pero lo que podrían hacer seria copiar todos los comandos que ocuparon en una nota o algo por el estilo, y después copian y pegan en su terminal.
