### ISSUE TITLE
Duda enunciado incompleto formato entrega y fecha

### ISSUE THREAD

**Issue by panchouc** [IIC2413/Syllabus-2023-2#87]
Hola! Revisando el formato de entrega y fecha aparece esto

![image](https://github.com/IIC2413/Syllabus-2023-2/assets/94400598/409d4631-0912-475a-ac0d-1f56625a76c3)

donde dice subir ambas cosas, pero no dice que cosas y habla de XX número de grupo, pero en ningún momento se hace referencia al grupo y su número. ¿Qué archivos hay que subir y con que nombre?

**Comment by RICARDOOVIEDO** [comment]
Dice que ambas cosas que piden en el enunciado, lo tienen que agregar a un archivo pdf y ese archivo tienen que subirlo a su carpeta Entrega1. Creo que falta mencionar que esa carpeta tiene que ir adentro del servidor de su grupo XX. No se si se entiende ahora.

**Comment by panchouc** [comment]
Creo que ya entendí, con ambas cosas se refiere a los requerimientos obligatorios y consultas que debe soportar. Y respecto a lo del grupo, ¿Debería decir quizás `grupoXX/Entrega1`?. De antemano gracias!

**Comment by RICARDOOVIEDO** [comment]
Asi es a ambas cosas. En filezilla, su carpeta tiene que estar adentro de la carpeta de su grupo. Saludos
