### ISSUE TITLE
Duda archivos en Filezilla

### ISSUE THREAD

**Issue by diegoherrerag2000** [IIC2413/Syllabus-2023-2#89]
Hola!! tengo una duda sobre la entrega en Filezilla. 

Si la entrega es en la base datos grupo98e1 (mi numero de grupo), como accedemos a esa base de datos en filezilla?? Porque al conectarnos desde filezilla estamos en el grupo 98 pero en el terminal haciendo psql y luego "\c grupo 98e1" si podemos conectarnos.

Y para subir el pdf de la entrega, este se debe hacer en "grupo98 -> Entrega1" o en grupo98e1 -> Entrega1"???

**Comment by RICARDOOVIEDO** [comment]
La entrega en el filezilla es con respecto al archivo adentro de la carpeta. Las tablas son las que tienen que estar adentro de la base de datos grupoXXe1!

Saludos!

**Comment by diegoherrerag2000** [comment]
Entonces la entrega del pdf debe estar en  grupo98 -> Entrega1, y las tablas en grupo98e1??

**Comment by RICARDOOVIEDO** [comment]
Así es!

**Comment by TomasBeckdorf** [comment]
Pero como se puede acceder a grupoXXe1? Para verificar que todo este funcionando bien
