### ISSUE TITLE
Nombres en control 1

### ISSUE THREAD

**Issue by tomastrivino** [IIC2413/Syllabus-2023-2#9]
<img width="691" alt="image" src="https://github.com/IIC2413/Syllabus-2023-2/assets/98418205/1b37e247-efad-4edf-9010-a4d59e106d09">

Hola! En el control se pide listar los nombres de los autores bajo ciertos criterios. Esto es sólo nombre o es también con apellidos? ya que la tabla de autores también contiene apellidos.

Gracias!

**Comment by Paldana99** [comment]
Ambas son validas

**Comment by RICARDOOVIEDO** [comment]
Hola! Solamente considera el nombre del autor, no el apellido! Saludos
