### ISSUE TITLE
Consulta sobre la utilización de funciones agregadas en álgebra relacional

### ISSUE THREAD

**Issue by DTP-2B** [IIC2413/Syllabus-2023-2#90]
Al revisar las issues y buscar información en Internet, encontré la siguiente referencia: [Relational Algebra](https://en.wikipedia.org/wiki/Relational_algebra), donde se mencionan funciones agregadas en el contexto del álgebra relacional. ¿Es posible utilizar estas funciones agregadas en nuestro proyecto?

**Comment by RICARDOOVIEDO** [comment]
No hay problema mientras esas funciones queden en forma de operadores de álgebra relacional.

Saludos.
