### ISSUE TITLE
Suscripción usuarios grupo impar

### ISSUE THREAD

**Issue by maxo2727** [IIC2413/Syllabus-2023-2#91]
Hola. Con respecto al registro histórico de los usuarios a los proveedores, debemos registrar sólo una vez cuando el usuario se suscriba (activo) y cuando se desuscriba (inactivo), o registramos cada mes que pasa que el usuario este suscrito? Estuve revisando en otras issues pero no queda muy claro este aspecto.

**Comment by RICARDOOVIEDO** [comment]
Solo tienes que verlo desde el sentido activo/inactivo del usuario. Saludos
