### ISSUE TITLE
Poblar tablas con csv

### ISSUE THREAD

**Issue by TomasBeckdorf** [IIC2413/Syllabus-2023-2#92]
Hola, estamos teniendo problemas para poblar las tablas que insertamos en grupo34e1 con los archivos csv. Esos (los archivos csv) los pusimos en la carpeta g34_bdd pero no nos funciona la ruta relativa, nos dice que los archivos csv no existen. Ayuda por favor

**Comment by RICARDOOVIEDO** [comment]
Hola, necesito más información pero tienen los archivos adentro del servidor?
