### ISSUE TITLE
Problema servidor

### ISSUE THREAD

**Issue by rvcruz** [IIC2413/Syllabus-2023-2#93]
No puedo entrar al servidor del curso:

PS C:\Users\Rodolfo> ssh grupo29@bachman.ing.puc.cl
ssh: Could not resolve hostname bachman.ing.puc.cl: \311ste es normalmente un error temporal durante la resoluci\363n de nombres de host y significa que el servidor local no recibi\363 una respuesta de un servidor autoritativo.

**Comment by Paldana99** [comment]
Hola,
El error persiste? Acabo de probar y el servidor esta funcionando

**Comment by rmezaa** [comment]
Hola, a mi ni a mi compañero nos funciona, y en el grupo de Telegram también hay más gente diciendo que nos tira el mismo error. No nos hemos podido meter hoy

**Comment by rvcruz** [comment]
Algo debe pasar con los proveedores de internet. Pude acceder al servidor utilizando datos moviles.

**Comment by cataguzmanw** [comment]
hola yo intente con mis datos móviles y tampoco me funciono, me dice que se estableció la conexión pero luego falla

**Comment by catalinamirandah** [comment]
Hola, nosotros también lo intentamos y tampoco nos dejó.

**Comment by andrius6789** [comment]
Hola, nosotros tampoco podemos acceder. Con el wifi llego solo a poder usar el ssh grupoxx@bach.... pero con datos moviles entro a psql pero no me deja usar \c grupo....

**Comment by ItsValkyrie** [comment]
Tengo el mismo problema que @andrius6789. Más específicamente, la consola entrega el siguiente error:

Input:
`grupo50@bachman:~$ psql`
Output:
`psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  remaining connection slots are reserved for non-replication superuser connections`

**Comment by andrius6789** [comment]
Precisamente ese error 🤝

**Comment by rominaarancibia** [comment]
Hola, a mi pasa lo mismo.

**Comment by JaviBLM** [comment]
Hola a mi y a mi compañera nos pasa lo mismo

**Comment by 0Cris0** [comment]
Holaa me está pasando lo mismo
:' (

**Comment by franancic** [comment]
Hola! me podrían entregar sus credenciales por interno? (francisca.ancic@uc.cl).
Con los ayudantes hemos probado distintos users, en diferentes computadores, y proveedores de internet, y a todos nos funciona (a ninguno le aparece ningún error)

**Comment by franancic** [comment]
Revisen si es un problema con su internet, porque en el servidor me aparecen 42 usuarios conectados en este momento!
