### ISSUE TITLE
Algebra vs SQL

### ISSUE THREAD

**Issue by jdelvalle2002** [IIC2413/Syllabus-2023-2#94]
Hola! en la parte 2 puedo modificar un poco la respuesta en SQL respecto la de álgebra relacional con tal de que se mantengan equivalentes, a fin de evitar líneas muy largas u otros inconvenientes?

gracias :)))

**Comment by antoniablanco** [comment]
Hola, lo ideal es que sean exactamente iguales. A menos que sea muy evidente que el pequeño cambio no afecta el resultado de la consulta. 
saludos!
