### ISSUE TITLE
Control 2

### ISSUE THREAD

**Issue by rmezaa** [IIC2413/Syllabus-2023-2#95]
Hola! Un par de dudas, qué materia entrará en el control 2? Y cuál será el plazo oficial? Como no han subido el enunciado de proyecto ni hubo ayudantía esta semana.

**Comment by RICARDOOVIEDO** [comment]
La fecha del control está en el readme del repositorio!

**Comment by rmezaa** [comment]
Oka, que preguntaba porque el readme decía que había ayudantía la semana pasada, y varios llegamos a las tres salas y no había nadie :/

**Comment by MariaJoseSilva** [comment]
Hola!
Me sumo a la pregunta sobre el contenido que entra en el control, será solo SQL?

**Comment by RICARDOOVIEDO** [comment]
Contenido es SQL y diseño de BDD.

Saludos!
