### ISSUE TITLE
2da consulta Control 2

### ISSUE THREAD

**Issue by jorgee02** [IIC2413/Syllabus-2023-2#98]
Hola, buenas.
En la pregunta 2 de las consultas, dice que entreguemos el ganador de la partida 12345. 
Resulta que dice que está en progreso, entonces, sería correcto asumir que se debe entregar el ganador _hasta ese momento_, o entregar derechamente nulo? 
O en verdad no es relevante?

De antemano, gracias!

**Comment by lfb1206** [comment]
Hola! Se debe entregar el ganador en ese momento, en otras palabras, se debe entregar el equipo ganador, independiente de que esté en progreso.

**Comment by Tomas2424** [comment]
Solo hay que entregar el equipo ganador ósea rojo o azul o también sus integrantes?
