### ISSUE TITLE
KO y Asistencia

### ISSUE THREAD

**Issue by MariaJoseSilva** [IIC2413/Syllabus-2023-2#99]
Hola!
1. En la relación ko el atributo id_jugador, es el jugador que le dio el último golpe a la victima?

2. En la descripción del juego se indica que "cuando un jugador participa en dejar KO a un oponente, aquellos que no dieron el último golpe reciben una asistencia", entonces en la tabla asistencia el id_jugador es quien entrega la asistencia? y el jugador que recibe la asistencia es el mismo que realizó el último golpe en el KO?

Muchas gracias!

**Comment by antoniablanco** [comment]
Hola!
1. Sí, el id_jugador es el jugador que produjo el KO.
2. En la tabla asistencia el id_jugador es el jugador que entrego la asistencia a ese KO_id
